### ISSUE TITLE
Clicking on playing music should open app

### ISSUE THREAD

**Issue by Elttob** [ShankarBUS/ModernFlyouts#1]
![image](https://user-images.githubusercontent.com/11815374/87213400-971d4580-c31c-11ea-9a15-51c05fa9dd51.png)

Clicking on the album art or name of the currently playing song should open up the app where the music is playing. I use this feature all the time with the regular Windows flyout, so having this be reimplemented if possible would be appreciated.

**Comment by ShankarBUS** [comment]
It would be a nice addition. Thanks for opening this issue ✌

**Comment by ShankarBUS** [comment]
It seems do-able I can get the `SourceAppUserModelId` for the session and can activate the app.

For a UWP app it gives the `AppUserModelId` : eg : **`Microsoft.ZuneMusic_8wekyb3d8bbwe!Microsoft.ZuneMusic`**

For a Win32 app it gives the process name : eg : **`msedge.exe`**

**Comment by ShankarBUS** [comment]
It has been [implemented](https://github.com/ShankarBUS/ModernFlyouts/commit/ef3612223e27bbcb72e070d3f2f47fe0ea407cbb) and will be available in the next release.

But there are some defects with this implementation such as :
- I doesn't open the correct window playing the media if there are multiple windows or processes of the same app
- UWP apps may behave incorrectly and make take a while.
