### ISSUE TITLE
Bug: Volume slider is not shown

### ISSUE THREAD

**Issue by Samuel12321** [ShankarBUS/ModernFlyouts#10]
Have recently noticed that after a while modern flyouts does not show volume slider as volume is being changed via keys. Just displays the second popup with what is playing.

**Comment by ShankarBUS** [comment]
Can you provide a gif or a video?

**Comment by Samuel12321** [comment]
Have not been able to reproduce since reinstall, seems to have been resolved.

**Comment by ShankarBUS** [comment]
What version did you experience this bug?

**Comment by Samuel12321** [comment]
0.3

**Comment by Samuel12321** [comment]
Unfortunately the issue has occurred again, so reinstall didn't fix it.
Have attached a screenshot.

![Screenshot 2020-08-19 112027](https://user-images.githubusercontent.com/35312698/90574823-06d0fb00-e20e-11ea-88e3-b9ca44bb8a5f.png)
This is all that is displayed, whether increasing, decreasing or muting volume.

**Comment by ShankarBUS** [comment]
How often does it occur? How can one reproduce it?
If you have brightness keys, can you check whether the brightness controls work?

Check whether the top bar is visible when turned on.
This is some real serious issue, I'll look into it.

**Comment by Samuel12321** [comment]
It occurs occasionally, but once it starts doing it, it wont stop until computer is rebooted. 
I can't change brightness from 100% as it is a desktop, however with the brightness keys i can trigger the popup (it just doesn't change from 100%). While the volume slider doesn't appear, the brightness one still does.
I usually have the top bar turned off, however when it is turned on and the slider is not working, the top bar still appears but the volume slider does not.
I am not sure exactly how to reproduce it yet, however i think it is occurring after the computer has been on for a while after resuming from hibernation.
It is a bit annoying, but the volume still changes, i just cant see by how much.

**Comment by Samuel12321** [comment]
Update:
Killing the task then restarting ModernFlyouts seems to temporarily resolve the problem

**Comment by ShankarBUS** [comment]
You can easily close it it from the tray icon's context menu.

So only the volume slider is not showing but the brightness slider and top bar are shown.

Thanks for the full information, pal 👏😁.

**Comment by ShankarBUS** [comment]
After looking into the code
https://github.com/ShankarBUS/ModernFlyouts/blob/6bc3bac46bb709c36b32a91c81459bd7a5628a06/ModernFlyouts/Flyout%20Helpers/AudioFlyoutHelper.cs#L98-L104

I found out that the volume slider will only be hidden when there are no audio devices.

Are you sure there are no problems with your machine?

Because you opened another saying that there should a message about no device are connected #14.
When there are no devices the volume slider won't be shown. I'm confused 😕

**Comment by Samuel12321** [comment]
Completely separate, can occur while listening to audio on Bluetooth audio device.
Hasn't happened recently, will reopen if it occurs again.
