### ISSUE TITLE
Bug: App crashes while changing media tracks

### ISSUE THREAD

**Issue by smdx** [ShankarBUS/ModernFlyouts#100]
@exzenous

**Describe the bug:**
Crashes when the cover art hasn't finished download and I want to adjust the volume, the window pops up and shows placeholder cover art and crashes. Tried on Apple Music Web Player (Third-party one but should be the same across web based players), Spotify doesn't has this problem, maybe because it could be done just in time.

**To Reproduce:**
1.Skip or wait until the song is changing
2.Adjust the volume

**Screenshot:**
[Imgur](https://imgur.com/QEMiwrc)

**OS Version:**
 - Windows 10 Insider Beta Channel version 20H2 build 19042.572

**ModernFlyouts Version:**
 - Version: 0.7.1

**Additional context:**
It seems that when I switch between Spotify and Apple Music Web App, ModernFlyout doesn't update itself to match the current player

------

@NotExactlyMeButMeh

I've got a similar issue, however it seems to be caused by media such as music from Spotify changing too many times. Cover art will eventually fail to update on song change until it will inevitably crash and you must restart the program. Last time it crashed it caused the start menu and other explorer aspects to lag behind inputs by a number of seconds.

**To Reproduce:**
1. Open ModernFlyouts
2. Ensure that it is working by toggling something such as Caps Lock/Num Lock.
3. Start playing or if you are already playing media through a platform such as Spotify, continue.
4. Attempt to change songs multiple times, forwards or backwards it does not matter. Use the media keys or the buttons on the flyout to do this.
5. Watch as cover art will stop updating and the app will eventually crash.

**OS Version:**

- Windows 10 Version: Windows 10 1909 Home Edition

**ModernFlyouts Version:**

 - Version: v0.7.1 (installed from the GitHub Mxis-bundle package)

-----

@smdx

Hello, the app crashes while running in the background.
Windows 10 Pro For Workstations-64bit-19042.508
====================================================
.NET Runtime：

日志名称:          Application
来源:            .NET Runtime
日期:            2020/10/11/周日 13:18:22
事件 ID:         1026
任务类别:          无
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           DESKTOP-98989856
描述:
Application: ModernFlyouts.exe
CoreCLR Version: 5.0.20.45114
.NET Version: 5.0.0-rc.1.20451.14
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ObjectReference'.
   at WinRT.IObjectReference.ThrowIfDisposed()
   at WinRT.IObjectReference.AsType[T]()
   at ABI.Windows.Foundation.IAsyncOperationWithProgress`2.As[A]()
   at ABI.Windows.Foundation.IAsyncOperationWithProgress`2.global::Windows.Foundation.IAsyncInfo.Cancel()
   at System.IO.StreamOperationAsyncResult.CancelStreamOperation()
   at System.IO.StreamOperationAsyncResult.Finalize()

事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-10-11T05:18:22.7919617Z" />
    <EventRecordID>7506</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-98989856</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: ModernFlyouts.exe
CoreCLR Version: 5.0.20.45114
.NET Version: 5.0.0-rc.1.20451.14
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ObjectReference'.
   at WinRT.IObjectReference.ThrowIfDisposed()
   at WinRT.IObjectReference.AsType[T]()
   at ABI.Windows.Foundation.IAsyncOperationWithProgress`2.As[A]()
   at ABI.Windows.Foundation.IAsyncOperationWithProgress`2.global::Windows.Foundation.IAsyncInfo.Cancel()
   at System.IO.StreamOperationAsyncResult.CancelStreamOperation()
   at System.IO.StreamOperationAsyncResult.Finalize()
</Data>
  </EventData>
</Event>

====================
日志名称:          Application
来源:            Application Error
日期:            2020/10/11/周日 13:18:22
事件 ID:         1000
任务类别:          (100)
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           DESKTOP-98989856
描述:
错误应用程序名称: ModernFlyouts.exe，版本: 0.6.5.0，时间戳: 0x5f4ed7fa
错误模块名称: KERNELBASE.dll，版本: 10.0.19041.488，时间戳: 0x42f14898
异常代码: 0xe0434352
错误偏移量: 0x00129962
错误进程 ID: 0x2a0c
错误应用程序启动时间: 0x01d69f6caf7f250b
错误应用程序路径: C:\Program Files\WindowsApps\32669SamG.ModernFlyouts_0.6.5.0_x86__pcy8vm99wrpcg\ModernFlyouts\ModernFlyouts.exe
错误模块路径: C:\Windows\System32\KERNELBASE.dll
报告 ID: 04fe0639-f247-4c58-b8e6-7d425e1ddb96
错误程序包全名: 32669SamG.ModernFlyouts_0.6.5.0_x86__pcy8vm99wrpcg
错误程序包相对应用程序 ID: App
事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-10-11T05:18:22.9120711Z" />
    <EventRecordID>7507</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-98989856</Computer>
    <Security />
  </System>
  <EventData>
    <Data>ModernFlyouts.exe</Data>
    <Data>0.6.5.0</Data>
    <Data>5f4ed7fa</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.488</Data>
    <Data>42f14898</Data>
    <Data>e0434352</Data>
    <Data>00129962</Data>
    <Data>2a0c</Data>
    <Data>01d69f6caf7f250b</Data>
    <Data>C:\Program Files\WindowsApps\32669SamG.ModernFlyouts_0.6.5.0_x86__pcy8vm99wrpcg\ModernFlyouts\ModernFlyouts.exe</Data>
    <Data>C:\Windows\System32\KERNELBASE.dll</Data>
    <Data>04fe0639-f247-4c58-b8e6-7d425e1ddb96</Data>
    <Data>32669SamG.ModernFlyouts_0.6.5.0_x86__pcy8vm99wrpcg</Data>
    <Data>App</Data>
  </EventData>
</Event>

**Comment by ShankarBUS** [comment]
Thanks for reporting the bug!

I'll will look into this

**Comment by ShankarBUS** [comment]
Does this issue still persists in v0.6.8?

Could you try updating the app and report to me whether or not this bug occurs?

**Comment by smdx** [comment]
Okay, update this version now. I will report if there is a problem.

**Comment by smdx** [comment]
> Does this issue still persists in v0.6.8?
> 
> Could you try updating the app and report to me whether or not this bug occurs?

There is no version 0.6.8 available for download？

**Comment by ShankarBUS** [comment]
Did you check MS store?

**Comment by smdx** [comment]
The version number in the MS market is incorrectly marked and has been successfully updated. Observe for a period of time if there is a problem and then report it.

**Comment by ShankarBUS** [comment]
Thanks for the quick response 👍.

Take your time and report to me once this happens again.

**Comment by Samuel12321** [comment]
yes the store page is incorrect, i wrote 0.6.5 when it should say 0.6.8. The actual package from the store is 0.6.8.

Will fix the store page now.

**Comment by SouLXH** [comment]
我是 0.6.8 还是崩溃

**Comment by smdx** [comment]
> 我是 0.6.8 还是崩溃
> 
> Translation: I am using v0.6.8 but it still crashes

我昨晚更新到现在还没遇到崩溃的现象，你系统什么版本啊？另外提供一下崩溃日志给作者吧。
开始菜单左下角右键-事件查看器-Windows日志-应用程序 找一下崩溃日志。

**Comment by SouLXH** [comment]
日志名称:          Application
来源:            .NET Runtime
日期:            10/13 星期二 15:52:12
事件 ID:         1026
任务类别:          无
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           TXH‘s-Y7000P
描述:
Application: ModernFlyouts.exe
CoreCLR Version: 5.0.20.45114
.NET Version: 5.0.0-rc.1.20451.14
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ObjectReference'.
   at WinRT.IObjectReference.ThrowIfDisposed()
   at WinRT.IObjectReference.AsType[T]()
   at ABI.Windows.Foundation.IAsyncOperationWithProgress`2.As[A]()
   at ABI.Windows.Foundation.IAsyncOperationWithProgress`2.global::Windows.Foundation.IAsyncInfo.Cancel()
   at System.IO.StreamOperationAsyncResult.CancelStreamOperation()
   at System.IO.StreamOperationAsyncResult.Finalize()

事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-10-13T07:52:12.4566391Z" />
    <EventRecordID>9294</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>TXH‘s-Y7000P</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: ModernFlyouts.exe
CoreCLR Version: 5.0.20.45114
.NET Version: 5.0.0-rc.1.20451.14
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ObjectReference'.
   at WinRT.IObjectReference.ThrowIfDisposed()
   at WinRT.IObjectReference.AsType[T]()
   at ABI.Windows.Foundation.IAsyncOperationWithProgress`2.As[A]()
   at ABI.Windows.Foundation.IAsyncOperationWithProgress`2.global::Windows.Foundation.IAsyncInfo.Cancel()
   at System.IO.StreamOperationAsyncResult.CancelStreamOperation()
   at System.IO.StreamOperationAsyncResult.Finalize()
</Data>
  </EventData>
</Event>

**Comment by ShankarBUS** [comment]
Woah! @Samuel12321, this is the bug I told you about on discord.

It now throws this `System.ObjectDisposedException: Cannot access a disposed object.` instead of invalid cast exception.

This exact same bug happens now.

Thanks @smdx for filing this issue and providing us the crash dump

This big is also related to the thumbnail bug.

What should we do now Sam?

**Comment by ShankarBUS** [comment]
Yes I'm aware this issue still happens.

I'll will fix it as quick as possible

**Comment by ShankarBUS** [comment]
@Samuel12321, disabling the thumbnails again would be the only way to solve this 😔.

I will re-enable it the moment it starts working properly again.

Having a working app is better than a visually appealing one.

Any thoughts?

**Comment by Samuel12321** [comment]
agreed, only other option would be to give user a choice between enabling with potential crashes or disabling (default)

**Comment by ShankarBUS** [comment]
A dirty fix has been done in e782da0e9e52013619c2139f54e0b01fab113faa

I will re-enable the thumbnails once the bug is fixed
