### ISSUE TITLE
more modification features required

### ISSUE THREAD

**Issue by ZzzzzzzSkyward** [ShankarBUS/ModernFlyouts#101]
feature 1 modify the width of the top bar.  
feature 2 modify the string "CapsLock is on." as I would prefer "On" for simplicity.  
feature 3 add events to the toolbar icon's menu to manually show the top bar.

**Comment by ShankarBUS** [comment]
@ZzzzzzzSkyward

> feature 1 modify the width of the top bar.

Do you really mean the **"Width"** or did you wanted to mention **"Height"**?

> feature 2 modify the string "CapsLock is on." as I would prefer "On" for simplicity.

There are NumLock and ScrollLock keys too. They will also trigger the flyout. Wouldn't it be confusing if there was just **"On/Off"**? How could users distinguish between the lock keys?

> feature 3 add events to the toolbar icon's menu to manually show the top bar.

I'm sorry what? What toolbar? What menu?
Could you please explain more clearly?

**Comment by Samuel12321** [comment]
i agree with @ShankarBUS just "on" could be confusing

don't understand 1 and 3
