### ISSUE TITLE
Proposal: Switch from MDL 2 icons to Fluent UI icons

### ISSUE THREAD

**Issue by WindowsFanBoi** [ShankarBUS/ModernFlyouts#109]
In case you are not aware, Fluent UI icons is set of open source icons designed by MS which are already being used on MS mobile apps (Office apps, Outlook, MS Edge mobile app, MS Launcher & etc.)

https://github.com/microsoft/fluentui-system-icons

This app uses the built-in Segoe MDL2 Assets glyphs for iconography which is fine and looks consistent with the current ecosystem of Windows.

All WinUI/UWP apps currently use the MDL2 icons but there are some user request to provide an option to switch to Fluent UI icons

https://github.com/microsoft/microsoft-ui-xaml/issues/2439

Uno platform already provides a way to use Fluent UI icons (they have 1:1 replacement font file for Segoe MDL2 Assets font)

https://github.com/unoplatform/uno.fonts

Files UWP already made the switch to Fluent UI icons.

![](https://github.com/files-community/Files/blob/master/Files/Assets/FilesHome.png)

Why not you?

Even if not enabled by default, please provide an option to swap the fonts. Have a nice day!

**Comment by ShankarBUS** [comment]
Could we use the fonts provided by Uno. They are Apache 2.0 Licensed. Would we get into some troubles if we use it?

**Comment by Poopooracoocoo** [comment]
https://github.com/microsoft/fluentui-system-icons/issues/15
https://github.com/1217950746/Fluent-System-Icons

**Comment by ShankarBUS** [comment]
Looks like we have either one of those not both interchangably.

What do say guys?

**Comment by Poopooracoocoo** [comment]
Are there enough Fluent UI icons for ModernFlyouts? If so, I reckon you should switch to 'em.

**Comment by Samuel12321** [comment]
I think this should wait till support grows and we have sorted more serious issues.

**Comment by ShankarBUS** [comment]
@Poopooracoocoo,

> Are there enough Fluent UI icons for ModernFlyouts? If so, I reckon you should switch to 'em.

There are more than enough icons.

@Samuel12321,

> I think this should wait till support grows and we have sorted more serious issues.

☹️ 😞 Yup, let's complete some high priority tasks first.

**Comment by ShankarBUS** [comment]
Edge Canary (88.0.697.0) finally made the switch to Fluent UI/System Icons.

![image](https://user-images.githubusercontent.com/63704247/98897122-ac73cd80-24d0-11eb-9d3f-e1e85633c6f4.png)

So I guess we should also make the switch once we stabilize the app.

**Comment by ShankarBUS** [comment]
Ok, why did no one tell me that MS officially provide us the **"FluentSystemIcons"** as a font?
https://github.com/microsoft/fluentui-system-icons/tree/master/fonts

### I hate y'all 😠😤
JK 😄

The migration is so easy now! We just have to remap the glyphs to this new font. That's it!
We don't need 3rd party libs! YAY!
I'm gonna update the UI immediately!

Any objections pals?

**Comment by ShankarBUS** [comment]
Woah!

Some icons look awfully bad (design wise) and some are scaled improperly (could be worked around).

![image](https://user-images.githubusercontent.com/63704247/99542449-1c55ec80-29d8-11eb-8146-e3866ed20dea.png)

I'm not sure if it's a good move to use Fluent System Icons at this stage.

I'll focus on high priority tasks first. Let's consider this for a future release (v0.9 maybe?)

**Comment by ShankarBUS** [comment]
Should I make the switch?

Guide me pals I'm literally confused 😅.

**Comment by Poopooracoocoo** [comment]
I think that you should go with the icons that _you_ prefer. If you don't like the look of the Fluent UI icons, don't go with them. :) 

P.S. Falling is so good. 😁

**Comment by ShankarBUS** [comment]
D O N ' T C O N F U S E M E!

Fluent or MDL2?

> P.S. Falling is so good. 😁

Couldn't agree more.

**Comment by WindowsFanBoi** [comment]
All Fluent Design based applications will use Fluent System Icons in the future.

My vote is for Fluent System Icons.

Even though it looks bad right now, it's evolving faster and will definitely look better in the future.

It's the best option for us.

**Comment by ShankarBUS** [comment]
Ok, let me add it to the next version.

If anyone complaints about it being ugly, we could revert it.

Alright?

**Comment by ShankarBUS** [comment]
I've done a half-ass implementation of the iconography update. Don't blame 😅. I'll try to fix the issues in upcoming commits.

**Comment by Samuel12321** [comment]
I personally think this looks a lot worse. Perhaps we should stay with MDL2 till they sort their icons out.

**Comment by ShankarBUS** [comment]
Oopsie I already commited it 😬.

I will revert just those changes which were made for the iconography switch.

> I personally think this looks a lot worse.

Had the same thought.

But MS Edge looks a lot cooler with the Fluent System Icons.
Why does ours just look ugly with it?

**Comment by Samuel12321** [comment]
> Why does ours just look ugly with it?

Don't know.
Remember that MDL2 is a well established icon set adapted to suit a wide range of conditions. Fluent icons are still new.

**Comment by ShankarBUS** [comment]
The main reason Segoe MDL2 Assets iconography suit desktop apps is its size grid!

It's designed for 16px icon grids.
While Fluent System Icons have mixed sizes (24px predominantly, 20px then, 16px then and so on).

MDL2 Assets is designed keeping Windows shell and apps in mind. While Fluent System Icons is designed keeping mobile shell and apps in mind.

Some Icons are mutually exclusive between both these, some have completely different styles and some are absent (I can't believe they didn't make an icon for **"SHUFFLE"**!!!!!!). 

We can't blame anyone!

You don't know how long it took me to find the best icon for a specific thing (I also had to select 20px size glyphs instead of 16px since most of the glyphs are either 20 or 24px).

I simply couldn't believe I wasted a whole day doing a useless task. I'm disappointed by the outcome 😢.

**Comment by yoshiask** [comment]
I personally think you should stick to MDL2 for now, but if you ever want to try switching to FSI again, I have a library on NuGet that allows access to the icons in the same way as the system ones in UWP. I briefly looked at the project file, and I can't determine if it's UWP or not. Either way, it's .NET 5 and I'm not entirely sure if my library would work at all on it.

**Comment by ShankarBUS** [comment]
@yoshiask,

No problems!

I could port your library to work on top of ModernWpf/WPF.

I was just lazy 😁.

**Comment by foursplaysroblox** [comment]
I think you should add a toggle to switch from MDL2 to Fluent Icons
