### ISSUE TITLE
Multi-lingual support bug

### ISSUE THREAD

**Issue by DengYi1** [ShankarBUS/ModernFlyouts#111]
I Can't find  the multilingual option in the latest version.

**Comment by ShankarBUS** [comment]
@Samuel12321 FYI

**Comment by Samuel12321** [comment]
0.7.0?
there isn't an option to select it, it sets itself to the display language

**Comment by DengYi1** [comment]
> 0.7.0?
> there isn't an option to select it, it sets itself to the display language

but my computer 's display language is Chinese

**Comment by Samuel12321** [comment]
what version are you running?

**Comment by DengYi1** [comment]
> what version are you running?

0.7.0

**Comment by Samuel12321** [comment]
are any parts of the settings menu translated?

**Comment by DengYi1** [comment]
> are any parts of the settings menu translated?

no

**Comment by ShankarBUS** [comment]
Ok @Sameul12321, let's add the option to change the language in v0.7.5

**Comment by Samuel12321** [comment]
agreed, although I'm confused why it isn't working automatically for @DengYi1

**Comment by ShankarBUS** [comment]
It must automatically find the system language.

I'm not sure if they set their display language as Chinese in the Windows Settings.

Could be due to regional differences.

**Comment by DengYi1** [comment]
![image](https://user-images.githubusercontent.com/52767905/96209355-f638c900-0fa1-11eb-836e-e07afca79230.jpeg)
Are you saying this?

**Comment by ShankarBUS** [comment]
Exactly!

There must be some issues. I'll look into it.

**Comment by ShankarBUS** [comment]
@DengYi1 @Gaoyifei1011,

I have added the ability to change the display language in d4fe47ba4c76806c59ad88129c398693d2894c25.
Please wait until we release v0.8.

**Comment by ShankarBUS** [comment]
![image](https://user-images.githubusercontent.com/63704247/96430968-7d937000-1220-11eb-9380-5cbb93094a62.png)

_Screenshot of the feature._

But there is a problem, **you need to manually restart the app to change the language properly.**
