### ISSUE TITLE
Launch bug, old flyout displayed

### ISSUE THREAD

**Issue by Samuel12321** [ShankarBUS/ModernFlyouts#115]
> bug when the application first launches, a 98% volume notification will appear on the flyout display

**Comment by ShankarBUS** [comment]
Yes, this is a known issue.

I'm aware of this and constantly trying to create another method to fetch the old flyouts' info.

TBH it is annoying during startup.

**Comment by ShankarBUS** [comment]
Fixed by 0dbf40f88b7619aca1eead72ca375ccbf603c6d5.

No more annoying old flyout at the start-up!
Thanks to myself! (😅)
