### ISSUE TITLE
Reports of instability on recent versions of ModernFlyouts

### ISSUE THREAD

**Issue by Samuel12321** [ShankarBUS/ModernFlyouts#116]
I have frequently been getting reports of instability and crashing with recent versions of ModernFlyouts.
I have attached what the MS store can tell us about these bugs.
[tableChart.txt](https://github.com/ShankarBUS/ModernFlyouts/files/5394958/tableChart.txt)

**Comment by ShankarBUS** [comment]
I'm sure this also includes #100.

I'm not sure what the `unknown function` refers to. It could be due to CsWinRT and .NET 5 🤷‍♂️.

Are these user reported?

Does store automatically do the telemetry?

Would have to take some time and analyse this.

**Comment by Samuel12321** [comment]
> I'm not sure what the unknown function refers to. It could be due to CsWinRT and .NET 5 🤷‍♂️.

the "unknown function" is things that the store cant fully report on due to user privacy settings or it doesn't recognise the problem. Not related to .net5, saw that before we migrated to .net5. 

> I'm sure this also includes #100.

Yes

They are automated telemetry
>

**Comment by Poopooracoocoo** [comment]
I've always (as in version wise, both .NET 5 and before) experienced crashes when I interact with the settings or systray menu. lmk if there's a way for me to send you the crash logs

**Comment by ShankarBUS** [comment]
> I've always (as in version wise, both .NET 5 and before) experienced crashes when I interact with the settings or systray menu.

I'm sorry that it crashes often 😅. Some of the minor bugs have been fixed but there are still lot of bugs to fix. I'll do my best.

> lmk if there's a way for me to send you the crash logs

TBH, I don't know anything about that 😅.

But @smdx suggested a way to collect crash reports - https://github.com/ShankarBUS/ModernFlyouts/issues/100#issuecomment-708149849.
You can try this the next time it crashes. I'll let you know if I find a more efficient way to collect crash dumps.

**Comment by Poopooracoocoo** [comment]
Oh sorry. It's not a crash. The app goes unresponsive and the app appears black. I can still close the window using the upper right corner button but the app is still unresponsive. I cannot open its systray menu anymore and nor does the flyout appear. I then have to go to Settings and terminate it. 

I can't find any crash reports in Event Viewer.

**Comment by ShankarBUS** [comment]
😞 This is a known issue #12. I'm working on it.

**Comment by KYatoo** [comment]
> 😞 This is a known issue #12. I'm working on it.
Looking forward to an early solution, it is much more beautiful than ms'

**Comment by ShankarBUS** [comment]
Hey @Samuel12321, most of the exceptions (except the one reported on #100) in the list you provided won't crash the application.
Most of them are handled properly. As #100 has been fixed, there won't be any instabilities that crashes the application.

What are your thoughts?

**Comment by Samuel12321** [comment]
Closing as number of reported crashes is significantly reduced and this report isn't specific to an actual bug.
