### ISSUE TITLE
Icon not vertically centered in Airplane flyout

### ISSUE THREAD

**Issue by Cyberdroid1** [ShankarBUS/ModernFlyouts#117]
![image](https://user-images.githubusercontent.com/51435948/96331561-e392c280-107b-11eb-8998-08d71eb3248f.png)

The icon is not vertically centered and seems to be at a low height.
Ignore background please, the transparency is less, the right side is a peep of a document.

**Comment by Cyberdroid1** [comment]
Ignore background please, the transparency is less, the right side is a peep of a document.

**Comment by ShankarBUS** [comment]
![image](https://user-images.githubusercontent.com/63704247/96332567-60289f80-1082-11eb-9389-ef51c98ee179.png)
![image](https://user-images.githubusercontent.com/63704247/96332527-09bb6100-1082-11eb-960e-c92a56fd3d1b.png)

The icon control is vertically centred.
But the particular glyph from Segoe MDL2 Assets font is designed to be like that. I'll see what I can do

**Comment by ShankarBUS** [comment]
![image](https://user-images.githubusercontent.com/63704247/96332882-222c7b00-1084-11eb-90af-eec8e0dc3e5e.png)
**\uE870 ("Signal Bars 5")** vs **\uEC3B ("Mob Signal 5")**.
We can use **\uEC3B ("Mob Signal 5")** for the airplane mode off icon.

**Comment by ShankarBUS** [comment]
![image](https://user-images.githubusercontent.com/63704247/96333078-771cc100-1085-11eb-93b1-8f59f45dc28f.png)

Does this make any difference?

**Comment by Cyberdroid1** [comment]
Yup! This looks desired!
