### ISSUE TITLE
Discussion: Change default top bar mode to `Auto Hide`

### ISSUE THREAD

**Issue by Samuel12321** [ShankarBUS/ModernFlyouts#125]
Store feedback

**Comment by ShankarBUS** [comment]
I don't agree with this. It just takes a click to hide the topbar (you can click on the **`Unpin TopBar`** button next to the drag area to auto hide it).

TopBar will be helpful for new users, that's why I kept it on by default. What are your opinions @Samuel12321?

**Comment by Samuel12321** [comment]
I have mixed feelings about this, perhaps more feedback from others would be helpful.

**Comment by ShankarBUS** [comment]
Let's keep this issue open for feedback from users then.

**Comment by justintaddei** [comment]
As someone who just installed ModernFlyouts for the first time, I like the current behavior. Had it been hidden by default I probably never would've known any of those controls existed and it was trivial to unpin it after I learn about them. My vote is on keeping it how it is.

**Comment by Samuel12321** [comment]
Seems it's best to leave it as it is. The addition of the OBE will further ensure users are aware of how to customise this.
