### ISSUE TITLE
Proposal: Make the flyout remember the last position

### ISSUE THREAD

**Issue by elenmerbau** [ShankarBUS/ModernFlyouts#13]
Currently the flyout doesn't remember the position which the users set after a restart, it resets to default position instead.

**Comment by ShankarBUS** [comment]
Haha, I was waiting for someone to point this out 🤣🤣🤣. I knew it from the start while implementing this.

Saving the position could be done. But when the display resolution changes or primary display is switched, thinks get complicated.

I'll find a way to do this.

But is this necessary for you?

**Comment by elenmerbau** [comment]
I wanted to place it in the upper middle of the screen since its default blocks buttons on some websites like YouTube and etc, it's not a big deal though.

**Comment by Cyberdroid1** [comment]
When will this issue be fixed?

**Comment by ShankarBUS** [comment]
v0.5.0? Next week? Maybe but I can't assure you 🤷‍♂️

**Comment by Cyberdroid1** [comment]
Ok, take your time. No problem in delay as this feature is nice to have, not that much of an essential feature.

**Comment by ShankarBUS** [comment]
Implemented in 7d11d27fa1dd8fa91fa0d8e7e05842f95e7a28bb.

And will be available in v0.5.0
