### ISSUE TITLE
Bug: Win10 Sometimes Bug

### ISSUE THREAD

**Issue by NotoChen** [ShankarBUS/ModernFlyouts#132]
**OS Version:**
 - Windows 10 Version: Windows10 Last Version

**ModernFlyouts Version:**
 - Version: Last Version

**Additional context:**
Window10 running for a period of time will be stuck or even crash, the taskbar icon can not be clicked,
And Open software black screen

**Comment by Samuel12321** [comment]
duplicate of #116

**Comment by NotoChen** [comment]
thank you
