### ISSUE TITLE
Bug: This app will force exit when watching YouTube Videos.

### ISSUE THREAD

**Issue by bobliboya** [ShankarBUS/ModernFlyouts#133]
This app not work when watching a YouTube video. I can change my volume/brightness/CapsLock/NumLock from my keyboard but there is no reaction on the screen (even the System default is not there).

**Comment by Samuel12321** [comment]
Hi, which browser are you using and windows version.

**Comment by Samuel12321** [comment]
duplicate of #116 and possibly #100

**Comment by bobliboya** [comment]
> Hi, which browser are you using and windows version.

Google Chrome 86.0.4240.111
Windows 10 1909

**Comment by Samuel12321** [comment]
Thanks, see #116 for further updates on this issue
