### ISSUE TITLE
Beta Signup form privacy error 

### ISSUE THREAD

**Issue by Cyberdroid1** [ShankarBUS/ModernFlyouts#137]
![image](https://user-images.githubusercontent.com/51435948/97080033-1574cd80-1616-11eb-9683-c0d07497a03e.png)

Though we can register, this page can demotivate.

**Comment by Cyberdroid1** [comment]
Though we can register, this page can demotivate.

**Comment by ShankarBUS** [comment]
@Samuel12321 FYI

**Comment by ShankarBUS** [comment]
Wait what beta signup?
When did this happen?

**Comment by Samuel12321** [comment]
@Cyberdroid1 is it fixed now?

**Comment by Samuel12321** [comment]
@ShankarBUS Just opened it.
Trying rolling out the updates in different flights to catch major bugs before they go to the 'Stable' release. Especially as they go to the MS Store before GitHub.

**Comment by Samuel12321** [comment]
As we have 12,861 users, when something goes wrong on the 'Stable' Release, i get a lot of notifications.

**Comment by ShankarBUS** [comment]
12,000+ users? 🤯

**Comment by Cyberdroid1** [comment]
@Samuel12321 Yes, it is fixed now.

**Comment by Samuel12321** [comment]
great

**Comment by Cyberdroid1** [comment]
![image](https://user-images.githubusercontent.com/51435948/99795834-71b60900-2b52-11eb-8870-9a1aea5aab6e.png)

Small issue, but if can be corrected, it would be great. 😁

**Comment by Samuel12321** [comment]
done.
Sorry 1AM spelling
