### ISSUE TITLE
Modern flyout become invisible

### ISSUE THREAD

**Issue by delvynHosea** [ShankarBUS/ModernFlyouts#1373]
### ModernFlyouts Version

0.9.3.0

### Windows version

Windows 11 Home

### Platform

x64

### Area(s) with issue?

General

### Steps to reproduce

When I press the volume up or down button, the modern layout should be on the top right on my screen, but it become invisible. I'm still able to press it, but the layout is invisible

### ❌ Actual Behavior

Modern flyout windows become invisible

**Comment by prakharb5** [comment]
Please switch to 0.10 beta 5
