### ISSUE TITLE
не появляется всплывающее окно

### ISSUE THREAD

**Issue by stexx1k** [ShankarBUS/ModernFlyouts#1376]
### ModernFlyouts Version

0.9.3.0

### Windows version

"Windows 11 24H2"

### Platform

x86

### Area(s) with issue?

Audio Flyout

### Steps to reproduce

почините пожалуйста всплывающее окно

### ✔️ Expected Behavior

Управление переключения музыки

### ❌ Actual Behavior

окно не появляется

**Comment by prakharb5** [comment]
Can you try the 0.10 beta 5 and report again here?
