### ISSUE TITLE
Bug: Settings window is not automatically in focus.

### ISSUE THREAD

**Issue by Cyberdroid1** [ShankarBUS/ModernFlyouts#138]
**Describe the bug:**
Whenever the Settings window is opened, it is always hidden behind an already-open window.

**To Reproduce:**
I guess it is self explanatory.

**OS Version:**
 - Windows 10 Version: 2009

**ModernFlyouts Version:**
 - Version: 0.7.1

**Comment by ShankarBUS** [comment]
Thanks @Cyberdroid1!

**Comment by Samuel12321** [comment]
@Cyberdroid1 Fixed in 0.8.0

**Comment by ShankarBUS** [comment]
Oh I forgot to link this issue to the commit 🤪🤦‍♂️.

Thanks @Samuel12321! 🤝🤗
