### ISSUE TITLE
Recommended behaviour modification when no audio output device is connected

### ISSUE THREAD

**Issue by Samuel12321** [ShankarBUS/ModernFlyouts#14]
When no audio output device is connected, and the volume is muted or changed via keys ModernFlyouts displays the last volume before device was unplugged, which doesn't change if the increase/ decrease or mute keys are pressed. 
If the user doesn't realise the speaker has disconnected, it makes it seem like ModernFlyouts has frozen.

It may be better if this behaviour is modified so when no audio device is connected and the volume keys are pressed, the flyout displays "No connected Audio device" or something similar.

**Comment by ShankarBUS** [comment]
@Samuel12321, Thank you for your suggestions!

Your request has been implemented in fdf6f130f0b1617f16f08893b052b565c812677f

**Comment by Samuel12321** [comment]
just tested, no flyout appears?

**Comment by ShankarBUS** [comment]
No flyout should appear! that's the correct behaviour (while pressing the volume keys). But if you press the media keys (previous, next, play/pause), you will see a message saying "No Connected Audio Devices" instead of showing the useless volume control

**Comment by Samuel12321** [comment]
i personally think it should show the no connected audio devices message when volume keys pressed as well.

**Comment by ShankarBUS** [comment]
Yes it should be! But there is no way to detect the volume trigger (when no audio devices are connected) with the current SHELL_HOOK method, we'd need to fallback to the old method (i.e. LL Key Hook) to detect the volume keys even when no audio devices are connected.
