### ISSUE TITLE
Bug: No way to recover volume flyout if the default position is set to go offscreen

### ISSUE THREAD

**Issue by erayrafet** [ShankarBUS/ModernFlyouts#141]
**Once a position higher than the height and width of the display is set, the flyout can no longer be seen:**

**To Reproduce:**
1. Go to the settings.
2. Scroll down to Flyout Default Position
3. Enter X,Y values of 1920,1080.
(That's the resolution of my display.)
4. Press one the volume keys.
5. Click on 'Align to default position.'
5. Repeat step 4.
6. No flyout.

**Settings screenshot:**
![image](https://user-images.githubusercontent.com/34194191/97099647-e56c0f80-1693-11eb-9c6c-0d7256af9b36.png)

**OS Version:**
 - Windows 10 Version: 20241

**ModernFlyouts Version:**
 - Version: v0.7.5

**Additional context:**
I'd like to have the flyouts displayed in the bottom-right corner, like in Chrome OS. Maybe a default option to place those on each display corner & limiting the X and Y axis bounds to the display width & height would help.

**Chromium OS (CloudReady 85.3) screenshot:**
![image](https://user-images.githubusercontent.com/34194191/97099885-a25f6b80-1696-11eb-866c-51a6296b7c09.png)

**Comment by ShankarBUS** [comment]
> Once a position higher than the height and width of the display is set, the flyout can no longer be seen

The one and only workaround you can do currently is to reset the app's data.

Go to the installed apps page on Windows Settings. Find the app and reset its app data and restart the app.

Guide : https://www.howtogeek.com/264824/how-to-reset-an-apps-data-on-windows-10/

One downside is that all your settings will be cleared 😅.

 > I'd like to have the flyouts displayed in the bottom-right corner, like in Chrome OS. Maybe a default option to place those on each display corner & limiting the X and Y axis bounds to the display width & height would help.

#74 and #71 is what you're looking for.

This is planned for v0.9

I'll try to do this ASAP 😄

**Comment by erayrafet** [comment]
Thanks!
I did the reset multiple times already.
One strange thing I noticed that setting X=1800 also renders the flyout offscreen.
Note that this is on 13" display with 125% scaling.

**Comment by ShankarBUS** [comment]
1920x1080 / 1.25 = 1536x864.

So setting 1800 will sure hop it out of the screen.

This is WPF's default behaviour. Window size scale up with increase in Dpi.

Screen size will scale down with increase in Dpi.

You have to be careful with the values.

**Comment by Tropix126** [comment]
Maybe simply have a "Reset to defaults" button at the bottom of the settings panel?

**Comment by ShankarBUS** [comment]
@Tropix126,

Yes, that would be a good idea.

**Comment by erayrafet** [comment]
Speaking of a reset button, this one doesn't do anything.
![image](https://user-images.githubusercontent.com/34194191/97524122-903e3f80-19ac-11eb-9fe6-7ad39377cabf.png)

**Comment by ShankarBUS** [comment]
@erayrafet,

There is a misunderstanding here.

That option will only restore the windows built-in flyout.

It says "Restore Default" not "Reset to Defaults".

I should change the term to "Restore legacy flyout" to reduce confusion.

**Comment by Samuel12321** [comment]
> I should change the term to "Restore legacy flyout" to reduce confusion.

Agreed

**Comment by ShankarBUS** [comment]
@erayrafet @Tropix126
Are these new options enough for you?

![image](https://user-images.githubusercontent.com/63704247/99568888-f2132780-29f5-11eb-8c91-b8f51bc38eca.png)

**Comment by erayrafet** [comment]
@ShankarBUS Should do. Thanks!

**Comment by ShankarBUS** [comment]
Wow that was quick 😂.

Thank you for letting me know such an issue exists.
GitHub issues let us track our progress and prioritize our work.
I must thank you for opening this issue!
