### ISSUE TITLE
Bug: Media Controls doesn't show thumbnails

### ISSUE THREAD

**Issue by pav2805** [ShankarBUS/ModernFlyouts#142]
**Describe the bug:**
I don't see images in media control
(In Chrome, Edge or Groove music, everywhere)

**Screenshots:**
![image](https://user-images.githubusercontent.com/14258733/97103397-cfbb1200-16b4-11eb-91b1-5df0300b72e5.png)

**OS Version:**
 - Windows 10 Version: 20H2

**ModernFlyouts Version:**
 - Version: v0.7.5

**Comment by ShankarBUS** [comment]
This is intentional.

We have disabled the thumbnails temporarily due to another bug (#100)

**Comment by ShankarBUS** [comment]
Oops!!! Sorry, forgot that this issue even existed 😅. Didn't link this issue to the commit.

I fixed this in 531aa6770cce142ad09b08bb82b5de99eae2e83f.
You have to wait till the next release 😊.
