### ISSUE TITLE
Feature Request: ability to toggle flyout on a per lock-key basis

### ISSUE THREAD

**Issue by Samuel12321** [ShankarBUS/ModernFlyouts#144]
Store reported feedback:

> This app is a must-have as a modern update to your system, but also as a useful tool. I absolutely love the notifications that pop out when I toggle Caps Lock. I only wish there was a way in the settings to toggle this flyout on a per-key basis. I often use the "insert" key in apps like Outlook to flag/mark complete items, and don't really need the flyout to pop up for this key in particular. Unfortunately, I can only enable/disable the feature entirely (including caps lock) as of yet.

**Comment by ShankarBUS** [comment]
Yup, I already planned it and said I will implement this on another issue.
https://github.com/ShankarBUS/ModernFlyouts/issues/91#issuecomment-704750188

It's good that we are reorganising the settings window.

**Comment by ShankarBUS** [comment]
Didn't plan to do this in v0.8 😅 2dd91390bc2d06382ae4fad3c12adb967a6d2b56.

But the lock keys page in settings looked empty so I decided to implement this together with other features 😁.
