### ISSUE TITLE
Bug: Missing settings spacer. [Settings UI]

### ISSUE THREAD

**Issue by Tropix126** [ShankarBUS/ModernFlyouts#150]
**Describe the bug:**
This is a very minor bug in the UI. When going to settings, there is a missing spacer between the language dropdown and the "Default Flyout" subheading. This doesn't really effect user experience, but sort of looks strange.

**To Reproduce:**
1. Open a settings window.
2. Locate the language dropdown.

**Screenshots:**

![image](https://user-images.githubusercontent.com/42101043/97592368-91806400-19ce-11eb-8039-d05c3766bdb2.png)

**OS Version:**
 - Windows 10 Version: 2004 (x64)

**ModernFlyouts Version:**
 - Version: 

**Additional context:**
None.

**Comment by ShankarBUS** [comment]
I fixed it locally. The UI doesn't look like that now.

I moved settings here and there. Now, they are much more organized and neat.
I will push the changes to GitHub once I'm done.

**Comment by Samuel12321** [comment]
Closed as fixed/no longer valid in 0.8.0

**Comment by ShankarBUS** [comment]
Sorry for the delay 😅.

Finally committed and pushed the changed to GitHub in 2dd91390bc2d06382ae4fad3c12adb967a6d2b56
