### ISSUE TITLE
Feature Request: Ability to set App theme.

### ISSUE THREAD

**Issue by Samuel12321** [ShankarBUS/ModernFlyouts#155]
Ability to set App theme.
We have the ability to set the Flyout theme, so it could also be nice to be able to set settings App theme

**Comment by ShankarBUS** [comment]
That's actually easier than implementing Flyout theme 😂

**Comment by ShankarBUS** [comment]
@Samuel12321,

I completed the parts you left to hook up. Now we can change the settings window theme for real.
