### ISSUE TITLE
Feature Request: Ability to set how long the flyout shows before dismissing

### ISSUE THREAD

**Issue by Nuzza** [ShankarBUS/ModernFlyouts#158]
**Is your feature request related to a problem? Please describe:**
Basically, it would be great if we could set how long the flyout stays on screen before automatically dismissing.

**Describe the solution you'd like:**
Having an input box which would allow the user to enter a number for the number of seconds the flyout is shown for. Also, if the user sets the number to 0, the flyout won't automatically dismiss and will remain on screen until manually closed/dismissed by the user.

**Describe alternatives you've considered:**
Currently, the flyout automatically dismisses after 4 seconds and there is no way to change that.

**Additional context:**
Just a quick mock-up I came up with for how this could be displayed in ModernFlyouts Settings:
![ModernFlyouts Concept](https://user-images.githubusercontent.com/29596317/97794852-1679b080-1c4f-11eb-83dd-975012c8f055.png)

**Comment by Samuel12321** [comment]
Great minds think alike. This has already been implemented in V0.8.0, which is already flighting to beta testers.

**Comment by Samuel12321** [comment]
This will be available for public release within a few days.

**Comment by Samuel12321** [comment]
duplicate #53

**Comment by Nuzza** [comment]
Ok, sounds great, thanks!

**Comment by ShankarBUS** [comment]
I guess your request is related to #53.

As @Samuel12321 said it's already implemented in v0.8

But your request is the exact opposite of #53.

#53 requests time for hiding the flyout

You request time for showing the flyout.

Aren't these mutually exclusive?

**Comment by Samuel12321** [comment]
yes
