### ISSUE TITLE
Add some gap between the settings window borders and the top heading

### ISSUE THREAD

**Issue by Cyberdroid1** [ShankarBUS/ModernFlyouts#160]
![image](https://user-images.githubusercontent.com/51435948/97795572-10bfa300-1c2e-11eb-9783-4eadfbc0b655.png)

![image](https://user-images.githubusercontent.com/51435948/97795674-c1c63d80-1c2e-11eb-9fc6-efe75bfdaf2a.png)
(red line not included, obviously)

What do you say?

**Comment by ShankarBUS** [comment]
Ok, according to UWP design guidelines what you suggested is the officially the correct design.

I thought the space was empty so I moved them up.

Let's keep our design in accordance to the official guidelines 😁.

**Comment by Cyberdroid1** [comment]
Oi, I didn't know about the guidelines 😂.  Just had this thought as it looked odd.

**Comment by Samuel12321** [comment]
How does it look now?

**Comment by ShankarBUS** [comment]
@Samuel12321, thanks!
