### ISSUE TITLE
WIKI IS HERE

### ISSUE THREAD

**Issue by Cyberdroid1** [ShankarBUS/ModernFlyouts#162]
The wiki is ready. I repeat, the wiki is ready. Check it out now!

**Comment by Samuel12321** [comment]
YAY 👍😁

Not a Bug😂

**Comment by Cyberdroid1** [comment]
Pin this issue for a few days to the top. So that people get to know.

**Comment by ShankarBUS** [comment]
Link to the Wiki is mentioned on the README.md, isn't it?

**Comment by Cyberdroid1** [comment]
The link was always there. Bolden the statement which has the link. But, let's keep it pinned for a week. After that, unpin it.
