### ISSUE TITLE
MalwareBytes' AI engine marks ModernFlyouts as malware

### ISSUE THREAD

**Issue by toineenzo** [ShankarBUS/ModernFlyouts#163]
![image](https://user-images.githubusercontent.com/4921397/97816680-16050800-1c97-11eb-9355-58f000a91005.png)
Hi, today my MalwareBytes started showing ModernFlyouts as malware. It is detected by the AI engine, so i don't know if this (hopefully) false positive has to do with that or with the new 0.7.8.0 update, because as soon as i updated the app, malwarebytes gave me this detection.

**Comment by Samuel12321** [comment]
Thanks for letting us know @toineenzo.
Yes the detection is false . I have contacted Malwarebytes.

**Comment by Samuel12321** [comment]
Malwarebytes has reported this as fixed.
Please reopen if this is not resolved.

**Comment by ShankarBUS** [comment]
@Samuel12321,

> I have contacted Malwarebytes.

How?????

**Comment by Samuel12321** [comment]
on their website they have a way to report false positives
