### ISSUE TITLE
Feature: Support for other languages

### ISSUE THREAD

**Issue by peter9811** [ShankarBUS/ModernFlyouts#17]
I want help to translate

**Comment by ShankarBUS** [comment]
Yes, you can 😃. But not now 😅. Currently the texts defined in code are only available in English. That will require Strings.cs resource for each supported language. And some other method for xaml, I guess. More features and changes will be made in future releases. Which may require change in xaml/code and new texts can be introduced.
You can make translations once we reach v1.0

Thanks for your contribution 👏.

**Comment by peter9811** [comment]
Oh ... I get it. I tried to do some translations, but I understand perfectly what you say

I will be following the project and when there is the possibility to contribute, I will

**Comment by ShankarBUS** [comment]
Thanks, I'll contact you then 😄

**Comment by peter9811** [comment]
I will wait for your email 

Check this. Maybe can help...
https://www.transifex.com/
https://crowdin.com/
https://weblate.org/

**Comment by peter9811** [comment]
What I need translate?

**Comment by ShankarBUS** [comment]
Not yet my friend 😅. @Samuel12321 closed the PR. I will contact you when this app is stable and ready for public.

**Comment by peter9811** [comment]
@ShankarBUS 
I can't install 0.4.0... And I can't use the .msix I tried change to msi, but impossible to install):

**Comment by ShankarBUS** [comment]
@peter9811
What Windows version do you use?

**Comment by peter9811** [comment]
@ShankarBUS 
I'm on Windows 10, 2004, x64

**Comment by ShankarBUS** [comment]
What error did you get when you installed the *.msix file?

**Comment by peter9811** [comment]
@ShankarBUS 
Don't open, basicaly don't run. Show like an unsable file 

"Windows can't open this type of file"

![image](https://user-images.githubusercontent.com/22783445/93258718-bdbc8a00-f76c-11ea-8db3-fe6ce1a50400.png)

**Comment by ShankarBUS** [comment]
Wierd 🤔. It should atleast show the associated windows app installer. This is how it shows on my machine.

![image](https://user-images.githubusercontent.com/63704247/93259130-f97f4000-f7bc-11ea-92d6-b079cf2be5dc.png)

Do you have App Installer on your computer?

**Comment by peter9811** [comment]
@ShankarBUS 
Hmmm... I think no... I used an "Windows debloat", may this delete it...

I can't use MS Store either. Any form to install 'App Installer'? 
Or some possible form to convert msix to msi?

**Comment by ShankarBUS** [comment]
> Or some possible form to convert msix to msi?

There is no idea of going back to msi packaging due to difficulties maintaining two different distribution methods 😅.

I would recommend you to install the AppInstaller

**Comment by Samuel12321** [comment]
The App installer is actually a necessary windows component, without it .msix packages wont work

**Comment by ShankarBUS** [comment]
> I can't use MS Store either. Any form to install 'App Installer'?

If MS Store somehow works, you can install the App Installer from there - https://www.microsoft.com/en-us/p/app-installer/9nblggh4nns1?activetab=pivot:overviewtab

**Comment by Samuel12321** [comment]
I think there is a powershell command to reinstall it

**Comment by ShankarBUS** [comment]
@Samuel12321,

> I think there is a powershell command to reinstall it

I'm not an expert on that field. But if MS Store works for him, he can install AppInstaller (I'm not sure whether this will work or not)

**Comment by Samuel12321** [comment]
This is now the most requested feature on the MS-Store

**Comment by ShankarBUS** [comment]
Oh my god! I never thought this would blow up.

I will finish the v0.7 work ASAP and implement at least some basic support for globalization and localisation.

**Comment by Samuel12321** [comment]
@peter9811 multi-lingual support has been added and will be released in 0.7.0
can you check the Spanish translation?

Thanks
