### ISSUE TITLE
Move back button to title bar

### ISSUE THREAD

**Issue by Poopooracoocoo** [ShankarBUS/ModernFlyouts#172]
It doesn't look right being aligned with the heading :/

ModernFlyouts version: 0.8.0.1
Windows 10 version: 20H2

**Comment by Cyberdroid1** [comment]
Oh yes! That's why it looked weird to me.

**Comment by ShankarBUS** [comment]
Oh now I remember why I moved the Page Header to the title bar #160.

It was because of this issue 🤦‍♂️.
