### ISSUE TITLE
Pressing and dragging outside of an item in the navigation pane still switches to that page

### ISSUE THREAD

**Issue by Poopooracoocoo** [ShankarBUS/ModernFlyouts#173]
![DzivYhq7iZ](https://user-images.githubusercontent.com/51363864/97948108-a3557300-1de3-11eb-8280-9ebd26fe20f7.gif)

ModernFlyouts version: 0.8.0.1
Windows 10 version: 20H2

**Comment by Samuel12321** [comment]
i don't think there is a lot we can do about this as it is one click open. 
Is it really a problem?

**Comment by Poopooracoocoo** [comment]
>Is it really a problem?

nah :p

this must be a ModernWPF issue
