### ISSUE TITLE
Feature Request: tell users what the default flyout timeout is

### ISSUE THREAD

**Issue by Poopooracoocoo** [ShankarBUS/ModernFlyouts#174]
**Is your feature request related to a problem? Please describe:**

If you change the flyout timeout you don't know what the default is

![image](https://user-images.githubusercontent.com/51363864/97948373-7b1a4400-1de4-11eb-9d8f-db4094df34fd.png)

**Describe the solution you'd like:**

A little i icon with a tooltip like the default flyout position

![image](https://user-images.githubusercontent.com/51363864/97948427-b0269680-1de4-11eb-8a5e-4fa109a1a39a.png)

**Describe alternatives you've considered:**

A reset button

Put the default in the description of the setting: "Flyout timeout (ms) (default: 2750)" (or something like that)

**Additional context:**

ModernFlyouts version: 0.8.0.1
Windows 10 version: 20H2

**Comment by Samuel12321** [comment]
Agreed, very easy to fix.

**Comment by ShankarBUS** [comment]
Ever used properties tool window in VS?

If a property's value is changed from default, it will show the value in bold. After reverting it to default it will turn back to normal.

Would something like it be good?

**Comment by Cyberdroid1** [comment]
But a button to reset would be required, no?

**Comment by Samuel12321** [comment]
Even simpler solution would be to add [Default 2070] to the text above the box

**Comment by Cyberdroid1** [comment]
What about adding this text when the box is empty, as a hint in greyish color (I don't know what they are called).

**Comment by Poopooracoocoo** [comment]
@Cyberdroid1 
> What about adding this text when the box is empty, as a hint in greyish color (I don't know what they are called).

fyi those are called placeholders :) There are so many articles about forms. One I've read recently is this one: https://gerireid.com/forms.html

**Comment by ShankarBUS** [comment]
@Samuel12321,

> Even simpler solution would be to add [Default 2750] to the text above the box

That wouldn't be good.

We can use placeholders though 🤷‍♂️.

**Comment by Cyberdroid1** [comment]
@Poopooracoocoo Thanks!

So, we can add placeholder text "2750".

**Comment by ShankarBUS** [comment]
@Samuel12321, we can also use `ui:ControlHelper.Description` for this purpose.

**Comment by Poopooracoocoo** [comment]
Would the default flyout position setting use a placeholder instead of a tooltip too?

**Comment by Cyberdroid1** [comment]
> Would the default flyout position setting use a placeholder instead of a tooltip too?

I think no, as we have to tell the user how to type the position settings, as X,Y. I don't think it would be appropriate.

**Comment by ShankarBUS** [comment]
Unfortunately, **"Placeholders"** wouldn't work for number boxes (as the value has to be cleared to show the placeholder, they are only valid for textboxes).

We may need to use the description property for this. We can show something like **"Default - 2750"**
@Samuel12321, should we localize this one too?

**Comment by ShankarBUS** [comment]
![image](https://user-images.githubusercontent.com/63704247/99768512-e83f1080-2b2a-11eb-8a62-0c91bd477039.png)

What about this?

**Comment by Samuel12321** [comment]
Great, however probably best to be a bit clearer and change the star to "Default:"

**Comment by ShankarBUS** [comment]
The reason I chose a star instead of text is the struggle localization!
We have to introduce a new entry just for this one!

The default value could be changed internally and will easily be updated with this method.
However if we were to use a string we have to hard code this value (2750) into the multilingual resources. Thus, making it hard to update it in the future.
We can work this around by making the string like this "Default: {0}" (some cultures keep the numerical values first and description at last, it depends).

A start however is universally understandable to everyone and easy for us to maintain.

**Comment by Samuel12321** [comment]
good point.

**Comment by ShankarBUS** [comment]
So, Is it okay?
Shall I close this now?

**Comment by Samuel12321** [comment]
yes close and merge. 😁

**Comment by ShankarBUS** [comment]
Great!

Hey @Samuel12321,

Do you know what time it is?

**Comment by Samuel12321** [comment]
This means that V0.8.2 is done. 
Will release to beta testers soon.

> Do you know what time it is?

Where?

**Comment by ShankarBUS** [comment]
> Do you know what time it is?

It's 🥳 🎉 R E L E A S E  T I M E!

> Where?

Bruh!

> This means that V0.8.2 is done, WELL DONE EVERYONE.
> Will release to beta testers soon.

Was just about to say this!

**Comment by Samuel12321** [comment]
Oh, jokes on me. Totally misinterpreted that. :)

**Comment by Samuel12321** [comment]
Just waiting on your commit with the default flyout timeout.

**Comment by ShankarBUS** [comment]
Give me a minute 😅.
I didn't see you committed 3 commits to the origin. My local clone is messed. I will clean it up and commit the changes again.
It did 3 unnecessary merge commits due to the changes I made to the packaging project.

**Comment by ShankarBUS** [comment]
I guess we may have to do git rebasing once in a while. Not for now next month maybe?

Look at this abomination 🤣🤣🤣
![image](https://user-images.githubusercontent.com/63704247/99771209-bd56bb80-2b2e-11eb-98cc-3e9be2098988.png)

**Comment by Samuel12321** [comment]
ouch

**Comment by ShankarBUS** [comment]
If I did merge the origin onto my local and committed it, it would look much worse. Nothing wrong on your side.
I should have pulled origin before committing it 😅.
