### ISSUE TITLE
Feature Request: Use inline spin buttons on flyout timeout NumberBox control

### ISSUE THREAD

**Issue by Poopooracoocoo** [ShankarBUS/ModernFlyouts#175]
ModernFlyouts version: 0.8.0.1
Windows 10 version: 20H2

**Comment by ShankarBUS** [comment]
For the NumberBox?

Well it did was like that at first. I had to shrink it. Are you suggesting this because the popup doesn't light dismiss?

I do agree that's annoying 😂.

**Comment by Poopooracoocoo** [comment]
no. not just because the popup doesn't light dismiss :P

**Comment by Samuel12321** [comment]
@ShankarBUS Have already done this locally, will push soon.

**Comment by ShankarBUS** [comment]
Great!
