### ISSUE TITLE
Bug: You can't un-focus the flyout timeout control by clicking outside of it

### ISSUE THREAD

**Issue by Poopooracoocoo** [ShankarBUS/ModernFlyouts#176]
**Describe the bug:**

You can't un-focus the flyout timeout control by clicking outside of it

**To Reproduce:**

**Screenshots:**

ModernFlyouts:
![xgt4xFBWVW](https://user-images.githubusercontent.com/51363864/97949133-c7ff1a00-1de6-11eb-8dec-72c8ef5a8d5d.gif)

WinUI:
![1Q203b8rXT](https://user-images.githubusercontent.com/51363864/97949136-c9c8dd80-1de6-11eb-8ea1-9e3d0bb2b197.gif)

**OS Version:**
 - Windows 10 Version: 
Windows 10 20H2

**ModernFlyouts Version:**
 - Version: 
v0.8.0.1

**Additional context:**

**Comment by Cyberdroid1** [comment]
Yes, I have also faced this bug. Even after closing and opening the window again, it remains like that. I thought it was normal. 😅

**Comment by Samuel12321** [comment]
![Screenshot 2020-11-03 172830](https://user-images.githubusercontent.com/35312698/97949935-0baf4f00-1dfa-11eb-9345-ebb22866ccec.png)
Will be fixed in 0.8.2 by changing to inline buttons

**Comment by Poopooracoocoo** [comment]
#175

**Comment by Poopooracoocoo** [comment]
@ShankarBUS is this an issue with ModernWPF? should i file an issue there?

**Comment by ShankarBUS** [comment]
Yup! It's related to ModernWpf
