### ISSUE TITLE
Feature Request: Use headers instead of pivot in audio flyout page 

### ISSUE THREAD

**Issue by Poopooracoocoo** [ShankarBUS/ModernFlyouts#177]
**Is your feature request related to a problem? Please describe:**

I was really confused to see the pivot because there are only a few things there. 

**Describe the solution you'd like:**

Headers

**Describe alternatives you've considered:**

**Additional context:**

**Comment by Cyberdroid1** [comment]
But, it allows more flexibility IF there would be more options in future, right?

**Comment by ShankarBUS** [comment]
Yup, that's half the reason.

Let's say we add features like per-app volume control, audio page will grow enormously 😶.

We wouldn't be able to add sub headers here and there.

It will look unorganized.

**Comment by Samuel12321** [comment]
i agree with @Cyberdroid1 and @ShankarBUS

**Comment by ShankarBUS** [comment]
So, we're cool right?

Imma close this now. Please re-open if you have a different opinion.
