### ISSUE TITLE
Feature Request: Add an option to set the flyout to default position directly from settings.

### ISSUE THREAD

**Issue by Cyberdroid1** [ShankarBUS/ModernFlyouts#179]
**Is your feature request related to a problem? Please describe:**
In case someone, by mistake, sets an odd value for the flyout which makes it appear out of display, this setting can help.

**Describe the solution you'd like:**
(see title)

**Additional context:**
This can fix a few issues.

**Comment by ShankarBUS** [comment]
Clone the align button from the flyout's top bar into the settings?

Sounds good!

**Comment by Cyberdroid1** [comment]
It will help to fix #141 .

**Comment by ShankarBUS** [comment]
@Cyberdroid1,

![image](https://user-images.githubusercontent.com/63704247/99569279-6cdc4280-29f6-11eb-81ee-51054c7cb997.png)

Did it as you said mate!
