### ISSUE TITLE
Feature Request: Change options in media section of audio page to radio buttons

### ISSUE THREAD

**Issue by Poopooracoocoo** [ShankarBUS/ModernFlyouts#180]
Apologies for deleting the template. It's too much work lol. 

![image](https://user-images.githubusercontent.com/51363864/97950007-8f147480-1de9-11eb-88a1-1ddf3cb8fffc.png)

These options are pretty confusing. 

The thumbnail alignment option is similar to this issue: https://github.com/microsoft/Xaml-Controls-Gallery/issues/436

**Comment by ShankarBUS** [comment]
Just changing two lines of xaml would solve this 😂.

**Comment by Poopooracoocoo** [comment]
Here's one more that would benefit from either being a radio button or being renamed:
![image](https://user-images.githubusercontent.com/51363864/97951768-642d1f00-1def-11eb-8538-8c8a0bdf29aa.png)

could be renamed to "Use coloured tray icon" and the description beside it could be on and off

**Comment by ShankarBUS** [comment]
@Poopooracoocoo

> "Use coloured tray icon"

Sounds good!

**Comment by Cyberdroid1** [comment]
Wait wait, when we turn it off, the toggle becomes monochrome-based, which seems fitting.

**Comment by Poopooracoocoo** [comment]
@ShankarBUS It looks like you didn't change the thumbnail alignment option. Could you please change that to use radio buttons instead of a toggle switch? :) <3

**Comment by ShankarBUS** [comment]
> @ShankarBUS It looks like you didn't change the thumbnail alignment option. Could you please change that to use radio buttons instead of a toggle switch? :) <3

Ok
