### ISSUE TITLE
简体中文

### ISSUE THREAD

**Issue by bangwb** [ShankarBUS/ModernFlyouts#181]
**What version of ModernFlyouts are you using:**

**Comment by Samuel12321** [comment]
can you provide more information please.

**Comment by Poopooracoocoo** [comment]
didn't imgradeone translate it to simplified chinese?

**Comment by Samuel12321** [comment]
yes + machine translations

**Comment by imgradeone** [comment]
翻译者来报道一下：
ModernFlyouts 已经有简体中文版本，如果软件没有显示中文，可以右击任务栏图标 `Settings`（设置），在设置界面选择 `中文（简体）`，重启 ModernFlyouts 试试。
![image](https://user-images.githubusercontent.com/30969327/99147142-76de0880-26b9-11eb-8339-c58e71829430.png)
