### ISSUE TITLE
 Brightness adjustment does not display frame

### ISSUE THREAD

**Issue by bangwb** [ShankarBUS/ModernFlyouts#182]
屏幕顶端用“”ctrl+鼠标滚轮“”调节亮度时，不显示亮度调节框

**Comment by Samuel12321** [comment]
translation: When the brightness is adjusted with ""ctrl+mouse wheel"" at the top of the screen, the brightness adjustment frame is not displayed

**Comment by ShankarBUS** [comment]
What?

**Comment by Cyberdroid1** [comment]
What is the adjustment frame?

**Comment by Poopooracoocoo** [comment]
It's unfortunate that @bangwb hasn't provided much information :( This reminds me of #4

**Comment by ShankarBUS** [comment]
They could be saying that mouse wheeling doesn't change the brightness slider's value?

I do have some inconvenience while mouse wheeling on either the brightness or volume sliders. Touch pad scrolling doesn't work but a mouse wheel does change it.
Sometimes the slider gets stuck while wheeling and sometimes it doesn't get the wheel inputs.

@bangwb, Could you provide more info?

**Comment by Poopooracoocoo** [comment]
>Touch pad scrolling doesn't work but a mouse wheel does change it.

Touchpad scrolling works for me. I have a precision touchpad. When you hover over the slider and swipe up or down it'll change the volume or brightness.

**Comment by ShankarBUS** [comment]
Well mine (Synaptics) doesn't work.

**Comment by Samuel12321** [comment]
closing as a duplicate of #4
