### ISSUE TITLE
Bug:Mute is automatically cancelled after restarting the system

### ISSUE THREAD

**Issue by smoadrareun** [ShankarBUS/ModernFlyouts#185]
**OS Version:**
 - Windows 10 Version:20H1/20H2

**ModernFlyouts Version:**
 - Version: 0.8.0.1

**Comment by Samuel12321** [comment]
@smoadrareun do you mean the flyout incorrectly changes, or the system unmutes.

**Comment by ShankarBUS** [comment]
Did this happen before installing ModernFlyouts?

**Comment by smoadrareun** [comment]
> @smoadrareun do you mean the flyout incorrectly changes, or the system unmutes.

The system is unmuted after log out or restart

**Comment by smoadrareun** [comment]
> Did this happen before installing ModernFlyouts?

No, when I exit the app, everything is ok

**Comment by ShankarBUS** [comment]
Ohhhhhhhhh! I get it now.

Now I know why this issue occurs.

On startup our app sends virtual volume key press signals to create the native flyout and replaces it.

While sending the signal, the system will automatically unmute.

I'll see what I can do.

**Comment by Cyberdroid1** [comment]
> Ohhhhhhhhh! I get it now.
> 
> Now I know why this issue occurs.
> 
> On startup our app sends virtual volume key press signals to create the native flyout and replaces it.
> 
> While sending the signal, the system will automatically unmute.
> 
> I'll see what I can do.

Instead of volume buttons, trigger a caps lock on-off signal.

**Comment by ShankarBUS** [comment]
> Instead of volume buttons, trigger a caps lock on-off signal.

Windows doesn't have a flyout for lock keys!
Brightness and Airplane mode signals can't be stimulated.
The only option to capture the native flyouts is to send either volume keys or media keys.

While sending media key signals is non-problematic, the native flyout will only respond to media keys when there is atleast one media playback session. Which is not possible at startup.

So sending the volume key signals was the only way.

**Comment by Cyberdroid1** [comment]
Oh ok. So impossible instead of simple. 😂

**Comment by ShankarBUS** [comment]
No, not **"impossible"**. We can fetch the native window while it's being created on its own and store the handles instead of us forcing it to be created. But I'm not sure though.

**Comment by ShankarBUS** [comment]
Fixed by 0dbf40f88b7619aca1eead72ca375ccbf603c6d5.

I assure you it won't happen again.
