### ISSUE TITLE
[Suggestion] Add flyout Lock-keys button "Insert"

### ISSUE THREAD

**Issue by S1ROZHA** [ShankarBUS/ModernFlyouts#19]
I think everyone understands me

**Comment by ShankarBUS** [comment]
Arghh.... How did I forget this key🤦‍♂️. I always hit the **Insert** key most of the time accidentally instead of the arrow keys. This will be a nice a feature.

Are there any other keys that can be toggled?

Thanks for suggesting this.

**Comment by ShankarBUS** [comment]
Hey @S1ROZHA,

When the insert key is on, the flyout will say "Overtype Mode."
And when it is toggled, the flyout will say "Insert Mode."

Is this the desired behavior?

**Comment by ShankarBUS** [comment]
But there is a problem, some text editors won't sync with what this app shows.
Because some text editors handle the insert key only when they are in focus and they won't be synced with the global toggle.

**Comment by ShankarBUS** [comment]
Implemeted in a12f3f65e7c07ff4dc9074f23bd9bbd7d9236639.

And will be available in v0.5.0
