### ISSUE TITLE
Bug: When I adjust the volume with the touchpad, the standard Windows version is displayed instead of the ModernFlyouts.

### ISSUE THREAD

**Issue by ShintakuNobuhiro** [ShankarBUS/ModernFlyouts#196]
When I adjust the volume with the touchpad, the standard Windows version is displayed instead of the ModernFlyouts.

**To Reproduce:**
1. Use the touchpad to increase or decrease the volume.
2. Windows standard ones are displayed instead of ModernFlyouts.

**OS Version:**
 - Windows 10 Version: Windows 10 Version 20H2

**ModernFlyouts Version:**
 - Version: v0.8.0.1

**Additional context:**
This issue does not occur when using the volume control keys on the mouse or keyboard.

**Comment by Samuel12321** [comment]
Hi, thanks for letting us know. 
Will close this as it is a duplicate of #4. See #4 for more updates on thus issue.
