### ISSUE TITLE
Japanese Translation: "Personalization" -> "個人設定", "簡易" -> "ライト", "暗い" -> "ダーク"

### ISSUE THREAD

**Issue by ShintakuNobuhiro** [ShankarBUS/ModernFlyouts#197]
v.0.8.0.1
・"Personalization" -> "個人設定"
・"簡易" -> "ライト"
・"暗い" -> "ダーク"

![image](https://user-images.githubusercontent.com/11265280/98491533-7d631f00-2278-11eb-9bc5-c018509a8dcb.png)

**Comment by Samuel12321** [comment]
Hi @ShintakuNobuhiro Thanks for letting us know. It turns out that we forgot to set the personalisation text as translatable (so it wasn't translating into any language).
Have fixed this and applied your other suggestions. They should be visible in the next release 0.8.2
