### ISSUE TITLE
Transition animations

### ISSUE THREAD

**Issue by elenmerbau** [ShankarBUS/ModernFlyouts#2]
Hey, can you add some nice transition animations between tracks? And sometimes it flickers when I change songs, at least for Spotify, didn't test anything else.

**Comment by ShankarBUS** [comment]
Are you referring the thumbnail or the labels?

What kind of transitions do you want?

And what parts do you want transitions to be applied?

**Comment by elenmerbau** [comment]
I'm referring to this area. Any simple fading animation will do the job :)
![image](https://user-images.githubusercontent.com/23418072/87229088-f1dd8e00-c36a-11ea-8527-f8c3c80e8475.png)

**Comment by ShankarBUS** [comment]
I was also asking about that. Do you want the thumbnail to be animated or the artist and album textblock to be animated or both? I need some idea to work with 😁

**Comment by elenmerbau** [comment]
Animating artist and album textblock would be nice. Can probably animate the thumbnail and the background only when they change, for example when you change albums, but it'll be probably hard thing to do.

**Comment by ShankarBUS** [comment]
It has been [implemented](https://github.com/ShankarBUS/ModernFlyouts/commit/74ea89370d0794daed6af96c9a33259081c10f2e) and will be available in the next release.

**Comment by elenmerbau** [comment]
Fade effect sounds good, thanks!
