### ISSUE TITLE
Add Animation when changing the slider

### ISSUE THREAD

**Issue by akhilesh-balaji** [ShankarBUS/ModernFlyouts#20]
Hi,
First of all, this is an Amazing App!! But, when I change the volume of the device using my keyboard, the transition is quite staccato: There is no transition between the position of the slider. It would be amazing  if you could add a sliding keyframe animation in between the two positions. For reference, this is a video of the slider progressing:
https://we.tl/t-39YRFW1cMb
I know this isn't a very good description, but I tried my best.

**Comment by ShankarBUS** [comment]
Nice suggestion 😃. But that is the default behaviour of the WPF slider control. I don't if other slider controls are animated within Windows. I will try my best to implement fluid transitions all over the app.

**Comment by ShankarBUS** [comment]
Hey @akhilesh-balaji, this is a nice suggestion but the said transition won't be practically good. I can't find a way to smooth it.

So this suggestion may not be implemented
