### ISSUE TITLE
Thumbnails for YouTube and similar don't display well

### ISSUE THREAD

**Issue by Samuel12321** [ShankarBUS/ModernFlyouts#208]
Presumably they are referring to the thumbnail image not scaling to the space provided.
![Screenshot 2020-11-11 091356](https://user-images.githubusercontent.com/35312698/98728546-87168f00-23fe-11eb-8458-7aa129957549.png)
See grey space above and below thumbnail image.

**Comment by ShankarBUS** [comment]
The thumbnail just uniformly fills the given area.

Do they want it to stretch fit?

I mean, it's the source app's side issue!
They provide it this way. Spotify is even worse.
