### ISSUE TITLE
Bug: App not running at startup (Store app only)

### ISSUE THREAD

**Issue by oscargb1** [ShankarBUS/ModernFlyouts#21]
Although the settings option is enabled, the app isn't running on startup. It neither shows up in the Task Manager Start tab nor in the Run registry key.

App Version : 0.3.0 (Microsoft Store)
OS Version: 19041.450

**Comment by ShankarBUS** [comment]
This is a known limitation of the store version.
You can **Wait for the next store release**

Or follow these to have it immediately:
1. Download the setup from GitHub, install it and uninstall the store version.
2. If you still want to use the store version and want it to run at startup, You can create a shortcut in the startup folder or manually create a registry key (in HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run, add a string called "ModernFlyouts" with location to the exe as the value) for that.

**Comment by Cyberdroid1** [comment]
Where would the exe file be located in the file explorer? It would be helpful to know.

**Comment by ShankarBUS** [comment]
Fixed on v0.4.0
