### ISSUE TITLE
if change the volume with a touchpad gesture, a default flyout appears

### ISSUE THREAD

**Issue by klopspafaf** [ShankarBUS/ModernFlyouts#210]
**Describe the bug:**

if change the volume with a touchpad gesture, a default flyout appears

**To Reproduce:**
Use touchpad gesture

**OS Version:**
 - Windows 10 Version: 

**ModernFlyouts Version:**
 - Version: 0.8.1

**Additional context:**

**Comment by Samuel12321** [comment]
duplicate of #4
