### ISSUE TITLE
Bug: Main menu language does not get updated when language is changed

### ISSUE THREAD

**Issue by Hymian7** [ShankarBUS/ModernFlyouts#214]
When you change the language manually in the app, the main menu does not get updated. Also, the current page is not updated. If you select another page, it is shown in the correct language.

1. Go to Settings
2. Change language to anything different than the current
3. See the new selected pages being updated, but not the main menu

![grafik](https://user-images.githubusercontent.com/38748117/99120713-9dd60500-25fb-11eb-921c-47fa41e3dc64.png)

Windows 10 Version: 20H2
Modern Flyouts 0.8.0.1

**Comment by Samuel12321** [comment]
Hi, did you restart the app?

**Comment by Hymian7** [comment]
Nope, but maybe you can get the behaviour consistent? Either everything updates right after change or everything updates after restart.
Otherwise another label or prompt would be useful to inform that language is updated after restart.

**Comment by Samuel12321** [comment]
would #209 Fix this

**Comment by Hymian7** [comment]
This would definetly help! But then the consequence should be that the old language is maintained until the user manually restarts the app.

**Comment by ShankarBUS** [comment]
@Hymian7,

> This would definetly help! But then the consequence should be that the old language is maintained until the user manually restarts the app.

Wow! That's a great idea! We should definitely do this 👍

**Comment by ShankarBUS** [comment]
@Hymian7,

From now on (f909f55806d778e80ab5cfcad865324ddd622c9d), the language change won't be applied until the app has been restarted. Changing the language would show a notif like this. Restarting the app will update the language fully.

![image](https://user-images.githubusercontent.com/63704247/99570348-cdb84a80-29f7-11eb-9cf5-f4301db1eaa8.png)
