### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by yang05051** [ShankarBUS/ModernFlyouts#216]
**Describe the bug:**
When I change the volume via touchpad gesture, the modernflyout will not appear, instead the system flyout will appear.

**OS Version:**
 - Windows 10 Version:  Windows 10, 20257.1 (fe_release)

**ModernFlyouts Version:**
 - Version:  v0.8.0.1

**Comment by Samuel12321** [comment]
Hi thanks for letting us know.
Closing this as a duplicate of #4 
Please see #4 for further updates on this issue.
