### ISSUE TITLE
Feature request: Remember flyout position from previous run

### ISSUE THREAD

**Issue by oscargb1** [ShankarBUS/ModernFlyouts#22]
I changed the flyout position for it to be more close to the border, but every time I close and open the app again it returns to the default position. So it would be great to have a feature to remember our preferred position.

**Comment by ShankarBUS** [comment]
Thanks for the suggestion 😊. But there's already an issue regarding this please see #12. I may have to close this issue as a duplicate.

**Comment by ShankarBUS** [comment]
Just so you know, this feature will be available in v0.5.0
