### ISSUE TITLE
Feature request: Is it possible to support the "show hidden icons" window in the taskbar

### ISSUE THREAD

**Issue by PyGroot** [ShankarBUS/ModernFlyouts#220]
On the right side of the taskbar of Windows 10, there is an upward arrow. After clicking the arrow, the hidden icon will be displayed in a small window.

The style of ModernFlyouts is very beautiful, can it be applied to this small window?

**Comment by ShankarBUS** [comment]
I assume that you're referring to the system tray area.

No, we don't plan to do this currently.

But our good friend & team member @ADeltaX is creating a custom shell for Windows 10 (custom taskbar, custom task view, custom system tray & etc).

@ADeltaX's DynamicShell (not yet released and no one knows when it will be) is what you're looking for.

Please wait till I get some info on DynamicShell from that person.

**Comment by Samuel12321** [comment]
Closing as currently out of scope.
