### ISSUE TITLE
Bug: Flyouts default position entering problem

### ISSUE THREAD

**Issue by OlegPapka2** [ShankarBUS/ModernFlyouts#223]
**Bug:**
In the settings menu Additional I cannot enter the point in the proper format as it automatically corrects in the way 'X;Y' not 'X,Y'.
I've tried already changing input language (system language Ukrainian and input language Ukrainian and English US), copying and pasting proper format of data. But even by default as I start program it set in the wrong way (picture added)

**Screenshots:**
![bug](https://user-images.githubusercontent.com/60508074/99221617-8fe5d700-27e9-11eb-9992-4e3ec983fae1.png)

**OS Version:**
 - Windows 10 Home Single language Version: Windows 10 1909

**ModernFlyouts Version:**
 - Version: 0.8.0.1

**Comment by ShankarBUS** [comment]
Thanks for reporting.

I will look into it.

I guess this mostly occurs due to regional or cultural conventions.

I need some time to fix this 😅.

**Comment by Samuel12321** [comment]
This not the first issue to be reported relating to the flyout default position setting. Perhaps how this is adjusted needs to be re-evaluated.

**Comment by Samuel12321** [comment]
i wonder whether this needs to be 2 separate smaller boxes to avoid comer and other localisation errors.

**Comment by ShankarBUS** [comment]
I thinking of separating it into two inputs like @Cyberdroid1 suggested a while ago.

Two number boxes could be used in place of the single texbox.

**Comment by ShankarBUS** [comment]
Fixed in e5c91d4094fcfb42a3929eb17d3ee499314ba9d8.

**Comment by ShankarBUS** [comment]
![image](https://user-images.githubusercontent.com/63704247/101665213-b7d7fb80-3a72-11eb-9c84-2ecde28915bb.png)

This is how it looks.

**Comment by Samuel12321** [comment]
Looks great, the only possible potential improvement is do the boxes need to be so wide?

**Comment by Cyberdroid1** [comment]
Boxes are bit too wide though. Anything that can be done?

**Comment by Cyberdroid1** [comment]
Also, what happens when the window's width is highly reduced? Do we have to scroll horizontally or would the Y coordinate box come under the X coordinate box?

**Comment by ShankarBUS** [comment]
It would wrap

![image](https://user-images.githubusercontent.com/63704247/101721593-534a8a00-3ace-11eb-94fa-6722d7efcabd.png)

What width do you guys suggest? It is currently 240 px wide (consistent with other inputs in the settings).

**Comment by Cyberdroid1** [comment]
Wide enough for just 6 digits. I guess that would explain.

**Comment by delano8** [comment]
Question, I don't have these default position boxes at all, were they removed? (I'd like to change it)
