### ISSUE TITLE
Grey out the volume bar when muted.

### ISSUE THREAD

**Issue by Cyberdroid1** [ShankarBUS/ModernFlyouts#23]
When the volume is muted through keyboard shortcut, it only shows the leftmost icon as muted. 
Instead, we can grey out the volume bar and number but not the dragger to make it look different from when not muted. It would help in visiblity.

**Comment by ShankarBUS** [comment]
Thanks for the suggestion!

**Comment by Cyberdroid1** [comment]
I have made a demo.

![volumebar](https://user-images.githubusercontent.com/51435948/91631412-f2071b00-e9f6-11ea-97ce-2a42a966c400.png)

(I had tried making in Paint, sorry for that 😅)

**Comment by ShankarBUS** [comment]
You want the slider-track's background and the text faded and the thumb-grip of the slider to be same, Am I right?

I thought you wanted to disable the slider when muted. Like this ⬇️
![image](https://user-images.githubusercontent.com/63704247/91631937-1ebd3180-e9fb-11ea-84b6-80f2535872d5.png)
![image](https://user-images.githubusercontent.com/63704247/91631999-693eae00-e9fb-11ea-8a8e-15a3751ed2fb.png)

So, the slider shouldn't be disabled but faded out. Like this ⬇️
![image](https://user-images.githubusercontent.com/63704247/91632203-ec143880-e9fc-11ea-9007-1f846c669a5d.png)
![image](https://user-images.githubusercontent.com/63704247/91632195-e3236700-e9fc-11ea-8052-4a7d1477c0ce.png)

**Comment by Cyberdroid1** [comment]
Hmmm, now I think that if we grey out the sider too (like the grey in your second image), that would be better, after seeing your examples.

Would love to see that implemented.

**Comment by ShankarBUS** [comment]
I don't clearly understand what you're trying to say.

Do you want the slider to be grey (both thumb and track) (1st pair dark/light) or only track faded (2nd pair dark/light)

The first option (disabling the slider) is easier than the second one (fading the track)

**Comment by Cyberdroid1** [comment]
Sorry for confusing, I liked the first 2 drawings shared by you. 

When we grey out the bar, it still doesn't look that distinctive.

I am not saying that we disable, we can just change the color to grey. It will unmute when clicked upon.

**Comment by Cyberdroid1** [comment]
Any updates? Which design are you choosing for the fix?

**Comment by ShankarBUS** [comment]
The grey colored track design is what I'm leaning towards (i.e. the 1st pair)

**Comment by Cyberdroid1** [comment]
All-grey one? 

You said to use the flyout again, we would first have to unmute. Will it be the issue there?

**Comment by ShankarBUS** [comment]
Then what way would you like?

**Comment by Cyberdroid1** [comment]
I have a doubt. When muted, we can't use the flyout to change volume, right? But, for example, I change volume through keyboard shortcut while muted, will the flyout work properly?

**Comment by ShankarBUS** [comment]
You can use the flyout and the volume will be updated. But you won't be able to change the volume using the slider. I will try to find an efficient way.

**Comment by Cyberdroid1** [comment]
I think you should go for this. We rarely touch the flyout to change volume. If it doesnt work when muted to use slider, let it be. (I think)

**Comment by ShankarBUS** [comment]
Ok then.

**Comment by Samuel12321** [comment]
I like the greyed out slider and number of the first one, however i think the slider should still reflect the current system volume (as in the second pair)

**Comment by ShankarBUS** [comment]
That was just a mock up. The values they show are just arbitrary.

Are you saying that you like the grey slider and faded out text? The flyout will show the real volume and will sync with it no matter what. This is just a design mock up.

**Comment by Samuel12321** [comment]
Yes the updated 2nd one looks good.
Sorry I miss understood the picture earlier (I thought you were trying to show a faded out and disabled slider).

**Comment by Cyberdroid1** [comment]
The second set doesnt look much different, though.

**Comment by Cyberdroid1** [comment]
Text from second text and volume slider from first would be great.

**Comment by Samuel12321** [comment]
> Text from second set and volume slider from first would be great.
agreed

**Comment by ShankarBUS** [comment]
That's what I said pals 😂

**Comment by ShankarBUS** [comment]
Done! eebf2a104d125f1d6125f86ff8a70dfb48fec1d1
Will be included in v0.5 and will be released tomorrow.
