### ISSUE TITLE
Feature Request: Documentation for third party STMC support and plugins

### ISSUE THREAD

**Issue by GoldenHashtag** [ShankarBUS/ModernFlyouts#230]
As title says, some 3rd party software does not integrate with windows global media controls, therefore they don't show up in ModernFlyouts either.

VLC and PotPlayer are the most known and used video players on Windows, supporting those are huge plus.

**Comment by ShankarBUS** [comment]
This is something that the media players have to do unfortunately 😢.

There's nothing we can do on our side 😅.

Can you request the owners of the media players you mentioned instead?

**Comment by Samuel12321** [comment]
As @ShankarBUS said, the media players have to support this.
I believe VLC is Opensource and does accept feature requests, not sure about the others. Perhaps we can open a request with them.

**Comment by GoldenHashtag** [comment]
> This is something that the media players have to do unfortunately 😢.
> 
> There's nothing we can do on our side 😅.
> 
> Can you request the owners of the media players you mentioned instead?

As of VLC, there were people suggesting this to VideoLAN but no reply from them at all. [Link](https://forum.videolan.org/viewtopic.php?t=154509)
I don't think PotPlayer developer will ever accept a feature request, they do accept issue reporting though.
![image](https://user-images.githubusercontent.com/40300931/99517599-74b0ce00-2987-11eb-8f9c-81743dffa1e7.png)

Guess I've asked something unachievable.

**Comment by Samuel12321** [comment]
Have created a feature request for VLC https://trac.videolan.org/vlc/ticket/25258#ticket
Perhaps if lots of people say they want this it will be added.

**Comment by GoldenHashtag** [comment]
> Have created a feature request for VLC https://trac.videolan.org/vlc/ticket/25258#ticket
> Perhaps if lots of people say they want this it will be added.

![image](https://user-images.githubusercontent.com/40300931/99606852-7370b700-2a02-11eb-8047-065571be45f4.png)
![image](https://user-images.githubusercontent.com/40300931/99607072-f42fb300-2a02-11eb-9b7d-3d2e38b43d43.png)

I believe the WinRT port means the version that are available on Xbox and Windows Phone, which already have support for STMC. Many people prefer the legacy version though.
![image](https://user-images.githubusercontent.com/40300931/99606993-c34f7e00-2a02-11eb-85ec-2400db47b1fb.png)
![image](https://user-images.githubusercontent.com/40300931/99607021-d3fff400-2a02-11eb-87f7-f3826556a78a.png)

**Comment by GoldenHashtag** [comment]
BTW [MusicBee](https://www.microsoft.com/en-us/p/musicbee/9p4clt2rj1rs) doesn't have STMC support but can be enabled with a plugin. [Link](https://github.com/ameer1234567890/mb_MediaControl)
![image](https://user-images.githubusercontent.com/40300931/99607399-a4052080-2a03-11eb-9f60-0a060d31a159.png)

You may add this to README.md as well as store description so people can see. It's also the music player I recommend.

**Comment by ShankarBUS** [comment]
We can have a section in the README which describes which apps are supported, which are not and which are with plugins/extensions.

Like a list of major apps which are currently supported such as
- Spotify [Store version],
- Groove Music
- Movies & TV
- Dopamine-Windows
- Microsoft Edge
- Chrome
- Firefox
- And some other major media players and browsers which make use of the SMTC feature...

Another list of apps which can support SMTC with the help of 3rd party plugins or extensions or add-ons such as MusicBee with the plugin you said and blah blah.

A final list of currently unsupported apps
- VLC
- blah blah...

**Comment by xzsk2** [comment]
You can try this for foobar [foo_mediacontrol](https://github.com/Hual/foo_mediacontrol)

**Comment by ShankarBUS** [comment]
So, the only thing missing is a VLC plugin.

I would love to know that there's a VLC plugin for the media controls.

VLC is the media player I use most of the time to watch offline movies or videos.

I hate that they don't support it out-of-the-box.

Please let me know if there's one.

**Comment by GoldenHashtag** [comment]
I've just tried foobar2000 v1.6.2 (from store), turns out it already has SMTC integration builtin.
![image](https://user-images.githubusercontent.com/40300931/99761789-e2c3d500-2aee-11eb-8375-bde287507f00.png)
![image](https://user-images.githubusercontent.com/40300931/99761856-07b84800-2aef-11eb-8748-3cf2be7da21e.png)

So for now VLC & PotPlayer has no way to support SMTC, MusicBee has plugin while foobar supports it out of the box.

**Comment by GoldenHashtag** [comment]
> Have created a feature request for VLC https://trac.videolan.org/vlc/ticket/25258#ticket
> Perhaps if lots of people say they want this it will be added.

Ticket still has issue:
![image](https://user-images.githubusercontent.com/40300931/99762130-b5c3f200-2aef-11eb-96ae-95fcec280538.png)
The only version available on store is WinRT port, desktop version only available from offical website. 
![image](https://user-images.githubusercontent.com/40300931/99762275-05a2b900-2af0-11eb-9ae6-2ee71fd870c7.png)
![image](https://user-images.githubusercontent.com/40300931/99762286-0d625d80-2af0-11eb-836e-37b1e13eaad9.png)

[Official download of VLC media player, the best Open Source player - VideoLAN - ](https://www.videolan.org/vlc/)
[Official Download of VLC media player for Windows Store - VideoLAN - ](https://www.videolan.org/vlc/download-winrt.html)

**Comment by Cyberdroid1** [comment]
> We can have a section in the README which describes which apps are supported, which are not and which are with plugins/extensions.
> 
> Like a list of major apps which are currently supported such as
> - Spotify [Store version],
> - Groove Music
> - Movies & TV
> - Dopamine-Windows
> - Microsoft Edge
> - Chrome
> - Firefox
> - And some other major media players and browsers which make use of the SMTC feature...

You should add text "Chromium based browsers e.g. Chrome, Microsoft Edge, Brave, etc."

**Comment by ShankarBUS** [comment]
> You should add text "Chromium based browsers e.g. Chrome, Microsoft Edge, Brave, etc."

That's true. But **"noob"** users wouldn't even be able to distinguish between Chrome and Chromium lol.

How would they know that Opera, Brave, MS Edge are all Chromium derivatives?

/s

The list I made was just for discussion 😂😂😂. We need more feedback and information before making the support list.
I'll sure make it like you suggested.

**Comment by Riajyuu** [comment]
I confirmed after AIMP also supports this as a 3-p plugin

![image](https://user-images.githubusercontent.com/16912240/99866608-74b20780-2bed-11eb-921c-124490fc7c64.png)

https://www.aimp.ru/?do=catalog&rec_id=1097

@ShankarBUS Maybe we shall explicitly document common-named programs that need a plugin to work (especially how).

**Comment by ShankarBUS** [comment]
> Perhaps add this there (but I have no permission to).

This is what I told you. Remember?

**Comment by ShankarBUS** [comment]
@Riajyuu,

Please wait.

I'll add a document in the docs folder within this repository.

You can then edit it and do a pull request.

**Comment by xzsk2** [comment]
> 1.5.1
Reworked integration with Windows 10 Universal Volume Control. Enabled by default once again.
...
[foobar2000 change log](https://www.foobar2000.org/changelog)

It seems from 1.5.1 foobar offically added SMTC support, works well ~~but not showing player name~~.
![image](https://user-images.githubusercontent.com/20642596/99869647-b3ed5200-2c07-11eb-894e-f14c56b514ee.png)

and this is the store ver, everything works fine.
![image](https://user-images.githubusercontent.com/20642596/99869629-a33cdc00-2c07-11eb-85f6-503d17f173b2.png)

I noticed im running windows10 dev (20262.1), tried foobar(exe ver) and aimp(with plugin), none of them can show player name(like the first image i pasted), only uwp apps like foobar(store ver) and groove somehow displays well😲

**Comment by Poopooracoocoo** [comment]
@xzsk2 check out issue 184.

**Comment by Samuel12321** [comment]
Other option would be to allow people to edit the Wiki:
https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/changing-access-permissions-for-wikis#:~:text=Only%20repository%20collaborators%20can%20edit,account%20to%20edit%20your%20wiki.

**Comment by ShankarBUS** [comment]
@Samuel12321,

We already talked about this somewhere else in this repo.
But I'm saying it again.
There's no way to the review or cancel changes to a Wiki page! (And no would be able to fork it and make a PR!)

People may do anything! They may put anything there and we won't be able to close it like a PR or review it and ask them to correct it. We would need to correct it on our own.

It's better to keep Wiki off from outsiders.

That's why I told you to use a document within this repo! (Anyone can fork the repo, make a PR, we can review and request any changes from them and merge or close the PR based on its need)

**Comment by Samuel12321** [comment]
Have added a document listing app support for STMC. 
If any one wants to edit it they can make a pull request. 
@xzsk2 @Riajyuu, @GoldenHashtag ; @ShankarBUS

**Comment by Cyberdroid1** [comment]
@Samuel12321 Desktop version of Spotify fully works with Modernflyouts. No need to add tag of Store version.

**Comment by ShankarBUS** [comment]
Hey everyone! Sorry for disturbing you 😅.

I've updated the 3rd party SMTC app support doc. It's now here.
https://github.com/ModernFlyouts-Community/ModernFlyouts/blob/main/docs/GSMTC-Support-And-Popular-Apps.md
If I missed anything, please let me know.

You can now make PRs to update the list with your app[s] of interest included.

Bye!

**Comment by Poopooracoocoo** [comment]
>Bye!

??

**Comment by ShankarBUS** [comment]
> > Bye!
> 
> ??

![](https://i.kym-cdn.com/entries/icons/mobile/000/029/405/jordan.jpg)

**Comment by Nerixyz** [comment]
🎉 [Chromium now supports timeline information and seeking](https://chromium-review.googlesource.com/c/chromium/src/+/4029072).

**Comment by ShankarBUS** [comment]
Yeahhh Boi!!!!

**Comment by naturbrilian** [comment]
Jellyfin Media Player also support this
![image](https://github.com/ModernFlyouts-Community/ModernFlyouts/assets/9246423/57de96b6-44f3-45bb-8db8-04e1bf5324e6)
