### ISSUE TITLE
Feature Request: Replace the windows default notifications

### ISSUE THREAD

**Issue by Bennik2000** [ShankarBUS/ModernFlyouts#232]
**Is your feature request related to a problem? Please describe:**
The animations of the windows notifications are buggy and do not look modern.

With "notification" I mean the popup in the lower right corner: 
![grafik](https://user-images.githubusercontent.com/8039939/99585381-8a091500-29e6-11eb-9e74-c6f890adf74b.png)

**Describe the solution you'd like:**
Replace the windows notifications with a modern fluent design comparable to the audio flyout. Moreover,

**Comment by ShankarBUS** [comment]
Unfortunately this is out of our scope for now.

Windows team is making a solid progress towards making the Windows shell better.

So there is a good chance the notification popup will get updated with Project **'Sun Valley"** in the next year.

We don't want to invest our time and effort in something that will officially done by the 1st party in the near future.

Sorry 😅.

But our team mate @ADeltaX is building a custom shell called **"Dynamic Shell"** for Windows 10 which will include revamped TaskBar and Notification popups.

I'll keep you updated.

But us making this is nearly impossible 😅.
