### ISSUE TITLE
Bug when opening settings

### ISSUE THREAD

**Issue by Cyberdroid1** [ShankarBUS/ModernFlyouts#24]
When opening settings by right-clicking on notification icon and selecting Settings, sometimes the page opens like this - 

![image](https://user-images.githubusercontent.com/51435948/91633444-ecfd9800-ea05-11ea-9fb3-6ec96469f40f.png)

And there is no animation on even the minimize, close button when hovered by mouse. Please see to this issue.

**Comment by ShankarBUS** [comment]
This is weird 🤔. How can I replicate this bug?

**Comment by Cyberdroid1** [comment]
After this happens, I can't trigger the context menu for a while.

**Comment by Cyberdroid1** [comment]
I dont know how. It sometimes happens, sometimes does not.

**Comment by ShankarBUS** [comment]
When it happened, was the window's title bar responsive?

Did it work after sometime?

**Comment by Cyberdroid1** [comment]
No, it seemed as if the app hanged. That might explain. Though, the flyouts still worked fine.

**Comment by Cyberdroid1** [comment]
Yes it works properly after sometime.

**Comment by ShankarBUS** [comment]
So there is already an issue regarding this please carry new comments over to #12. I may have to close this as duplicate.

**Comment by Cyberdroid1** [comment]
ok
