### ISSUE TITLE
Enable smooth scroll in Settings app

### ISSUE THREAD

**Issue by Cyberdroid1** [ShankarBUS/ModernFlyouts#25]
Please enable smooth scrolling in the settings app of Modern-Flyouts. Currently, its jaggy and not smooth. Or you can redesign it to reduce the need for scrolling.

**Comment by Cyberdroid1** [comment]
I have drawn an example.

![setting app](https://user-images.githubusercontent.com/51435948/91686883-13454400-eb7c-11ea-84f7-54c26f1496e2.png)

**Comment by ShankarBUS** [comment]
It's a WPF app. UWP apps are much smoother. But this is WPF's default behaviour. I will see what I can do.

**Comment by Cyberdroid1** [comment]
You can also redesign the settings page to reduce need for scrolling, like the design above given by me.

**Comment by ShankarBUS** [comment]
But what if the window is resized to be small. If controls are stacked horizontally we will need to show a horizontal scrollbar. Having a horizontal scrollbar will be ugly and people are used to vertical scrolling. So stacking controls vertically is a good option.

And also changing controls orientation with respect to available space is possible. But it's just a single window no one will use the settings once the app's settings has been set.

It's not a primary priority for now.

**Comment by Cyberdroid1** [comment]
When the window's width is reduced, the menu bar on the left can be reduced by clicking on the 3-line button. 

You can also make it dynamic, change it according to width of window. (as you said)

**Comment by Cyberdroid1** [comment]
@ShankarBUS Are you planning to redesign the settings page as discussed above?

**Comment by ShankarBUS** [comment]
@Cyberdroid1,

I think we should go with smooth scrolling instead of changing the layout (may cause unwanted issues).
Also I'm adding some new options to the settings so I think Vertical smooth scrolling will be the best method.

**Comment by Cyberdroid1** [comment]
New options, i see. Nice.

Ok. Can you rename the Module names to remove the "-flyout" text? It doesnt look that good with this text. And we know what Audio module, brightness module, etc. mean. Just a consideration.

**Comment by ShankarBUS** [comment]
> Ok. Can you rename the Module names to remove the "-flyout" text? It doesnt look that good with this text. And we know what Audio module, brightness module, etc. mean. Just a consideration.

😁 Sorry. They didn't have the `-flyout` suffix originally but I added them later for convenience of new users

**Comment by Cyberdroid1** [comment]
Oh, didnt know that. Now I know.

**Comment by ShankarBUS** [comment]
@Cyberdroid1, Done!

> Note : GIF may not be smooth and won't represent the real performance. It will be stuttering and laggy. But I assure you that there is some improvement.

![ModernFlyouts](https://user-images.githubusercontent.com/63704247/93322395-e27a3580-f830-11ea-9e08-a37a17348364.gif)

**Comment by ShankarBUS** [comment]
@Cyberdroid1, Thank you so much my friend. You have opened some feature requests and gave some suggestions for improvements. Feel free to open new feature requests/proposals 😄🙏

**Comment by Cyberdroid1** [comment]
@ShankarBUS, Is it as smooth as UWP? I dont expect it to be that smooth. Hope to see this version soon.

BTW, I am your country-mate. 😄 Didnt tell you.

**Comment by ShankarBUS** [comment]
> Is it as smooth as UWP? I dont expect it to be that smooth. Hope to see this version soon.

TBH even I didn't expect it to be that smooth 😂

> BTW, I am your country-mate. 😄 Didnt tell you.

I know it. I saw it on your GitHub profile when you opened your first issue. Namaste!👋

**Comment by Cyberdroid1** [comment]
Namaste!

BTW, when will v0.5 be out?

**Comment by ShankarBUS** [comment]
> BTW, when will v0.5 be out?

Next week probably 😉

Where are you from?

**Comment by Cyberdroid1** [comment]
Lets meet on Telegram.

**Comment by ShankarBUS** [comment]
Implemented in 7d11d27fa1dd8fa91fa0d8e7e05842f95e7a28bb.

And will be available in v0.5.0

**Comment by Poopooracoocoo** [comment]
hey is there a wpf issue about this?

**Comment by ShankarBUS** [comment]
> hey is there a wpf issue about this?

No I guess. We can't expect new features in WPF anymore. So I had to do a stupid workaround (not original copied from HandyControls lol 😁)

**Comment by Poopooracoocoo** [comment]
The scrolling is much nicer! :D 

It feels slow however and trying to overscroll looks like this: 

![3RaPVgz7Nv](https://user-images.githubusercontent.com/51363864/93846970-f5857d80-fce8-11ea-9435-030779265126.gif)

**Comment by ShankarBUS** [comment]
The scrolling will be so slow when done with a trackpad/touchpad. But for a mouse wheel it will be much better than the default behaviour. There is a minor issue with this impl, you have to scroll the wheel too fast and too much to move by a relatively small distance.

There are space for improvements on this specific feature. Didn't spend time on this because it must supported by WPF or some UI library out-of-the-box not ourself.

I'm planning to request this feature either on ModernWpf or WPF.

**Comment by Cyberdroid1** [comment]
It is actually too smooth now! 😂
Yeah, there is some difficulty in scrolling with touchpad. When scrolling slowly with touchpad, it goes very slow but with speed, it is fine.

**Comment by Poopooracoocoo** [comment]
hey @ShankarBUS. could you chime in on that WPF issue :)

**Comment by ShankarBUS** [comment]
What am I supposed to do? 😂

**Comment by Cyberdroid1** [comment]
> > hey is there a wpf issue about this?
> 
> No I guess. We can't expect new features in WPF anymore. So I had to do a stupid workaround (not original copied from HandyControls lol 😁)

**Comment by Sylvain2703** [comment]
Hi!
This WPF issue is very annoying since almost all WPF apps that are affected 😢

The [solution proposed by Microsoft](https://docs.microsoft.com/en-us/windows/win32/w8cookbook/windows-precision-touchpad-devices) is to set `ultraHighResolutionScrollingAware` to `false` in the `app.manifest` file.

I don't really like this solution/workaround and don't understand why WPF doesn't handle that out-of-the-box...
Did any of you find a GitHub issue about this on the official WPF repo?
