### ISSUE TITLE
When im playing Spotify Music, i sometimes don't see music control bar.

### ISSUE THREAD

**Issue by Adamalcaide1030** [ShankarBUS/ModernFlyouts#252]
When im playing **Spotify Music**, i sometimes _don't see_ music control bar.

**Comment by Poopooracoocoo** [comment]
Could you explain more? Like which version of Spotify? Did you install it from the MS Store? Which version of Windows 10? etc.

**Comment by Lukasz-egg** [comment]
You must turn off and again on music control bar in spotify settings, that's spotify problem, sometimes it isn't displayed in build-in media control too 😉

**Comment by Samuel12321** [comment]
> You must turn off and again on music control bar in spotify settings, that's spotify problem, sometimes it isn't displayed in build-in media control too 😉

Will close, as answer seems to be above. Happy to re open if needed.
