### ISSUE TITLE
Feature Request: Switch Between Media Players

### ISSUE THREAD

**Issue by mbeps** [ShankarBUS/ModernFlyouts#257]
**Is your feature request related to a problem? Please describe:**
When there are multiple media sources, allow the user to switch between them. Currently, the app only shows one one media player at a time even if there are multiple sources. This will allow users to manage multiple streams of audio without going to each individual app. 

**Describe the solution you'd like:**
- Add buttons on each side of the media player to switch between players. 
- Add swipe gestures for touch devices to switch between devices.

**Describe alternatives you've considered:**
Haven't got any alternatives. 

**Additional context:**
![image](https://user-images.githubusercontent.com/58662575/100334524-d0083f00-2fcb-11eb-8021-1aae6078400a.png)
This includes buttons on the left and right side of the player to switch between streams.

**Comment by ShankarBUS** [comment]
There's a button to switch between media session controls since v0.3!

You can also stack multiple sessions vertically (only vertical orientation supports stacking not horizontal)

You can see #6 for more information.

**Comment by mbeps** [comment]
Ok, I understand. I found out that it does not work when you have multiple streams of media playback from the same app. I tried YouTube Music and normal YouTube on Microsoft Edge and it was not working. I also tried on the original flyout and it does not work. Thanks  From: ShankarSent: 26 November 2020 09:48To: ShankarBUS/ModernFlyoutsCc: Maruf Bepary; AuthorSubject: Re: [ShankarBUS/ModernFlyouts] Feature Request: Switch Between Media Players (#257) There's a button to switch between media session controls since v0.3!You can also stack multiple sessions vertically (only vertical orientation supports stacking not horizontal)You can see #6 for more information.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ShankarBUS** [comment]
> I found out that it does not work when you have multiple streams of media playback from the same app

Yes! Exactly!

This is something that we are trying to workaround by creating an extension for browsers (currently Chrome and MS Edge are our primary targets).

We're planning to make a Chromium extension which will interop with the browser and our app inorder to get full integration with the media sessions of each tabs in all the windows of the browser (instead of just the media session of the active tab of the active window)

You can keep up with #170 for more information and future updates.

**Comment by Poopooracoocoo** [comment]
please star https://crbug.com/1153108

**Comment by ShankarBUS** [comment]
Thanks @Poopooracoocoo!

**Comment by ShankarBUS** [comment]
I'm closing this issue.

You can keep up with
- #170 (for multiple sessions support) &
- #258 (for touch input support)
