### ISSUE TITLE
ModernFlyouts not overwriting the DefaultFlyouts

### ISSUE THREAD

**Issue by abracadam** [ShankarBUS/ModernFlyouts#259]
Even if I install from Windows store, even if I install it directly from the .msix package, it just doesn't overwrite the default flyouts on my desktop (RTX 2060, I5 9600k). I am running Windows 20H2 and it is running just fine on my Windows 20H2 Surface Laptop 3.

**Comment by ShankarBUS** [comment]
Is the running in the background?

**Comment by ShankarBUS** [comment]
Desktops wouldn't have brightness and airplane made flyouts.

But audio and lockkeys flyouts could be shown if the app runs properly without crashing.

**Comment by abracadam** [comment]
Yes it is running in the background and I don't care at all about the brightness and airplane mode flyouts, I am talking about the basic volume and key state changing ones.

**Comment by abracadam** [comment]
I am only talking about the volume and lockkeys flyouts, but for some reason I only see it in details, not background processes.

**Comment by ShankarBUS** [comment]
#4 maybe?

We're still investigating on that issue.
