### ISSUE TITLE
ModernFlyouts stopped working.

### ISSUE THREAD

**Issue by Cyberdroid1** [ShankarBUS/ModernFlyouts#26]
When trying to reduce volume through keyboard shortcut, the app crashed. 

I got this from reliability monitor - 

![image](https://user-images.githubusercontent.com/51435948/91796999-2240fa80-ec3f-11ea-8311-93d087c77b7c.png)

**Comment by ShankarBUS** [comment]
![meme](https://imgflip.com/i/4df8b2)

**Comment by ShankarBUS** [comment]
![Meme](https://i.imgur.com/PZKiK8p.jpg)

**Comment by ShankarBUS** [comment]
Does restarting the app fixes the bug?

**Comment by Cyberdroid1** [comment]
Yeah it does

**Comment by Cyberdroid1** [comment]
Because the app had quit itself after the crash.

**Comment by ShankarBUS** [comment]
Any more info?

**Comment by Cyberdroid1** [comment]
When I tried to change the volume with keyboard shortcut, I noticed that the flyout had frozen after coming out. I tried to click on it to check for responsiveness. Instead, the flyout vanished and the notification tray icon also vanished.

**Comment by Samuel12321** [comment]
Seems to be a bug with the store app, my poor repackaging probably to blame.
Have got 217 notifications about this, and two other bugs.
Just for curiosities sake, try the .exe version and see if that fixes the problem.
I am working on properly implementing the MS Store version, and hope to release an update later this week.

**Comment by Cyberdroid1** [comment]
Alright, i will try it out.

**Comment by Cyberdroid1** [comment]
When running the setup file from the releases page, I got this - 

![image](https://user-images.githubusercontent.com/51435948/91936781-2a1ba000-ed0e-11ea-802a-9eb5e12e46a0.png)

Anyways, I am installing it. Will let you know if this bug happens again.

**Comment by Samuel12321** [comment]
This is quite common with less distributed software. The MSI may not have been signed correctly, shouldn't affect usability, but something to investigate

**Comment by Cyberdroid1** [comment]
I will update this issue if I face the bug again. No crash until now. (That crash was also rare.)

**Comment by ShankarBUS** [comment]
@Cyberdroid1, I guess this bug could be caused due to the registry dependency and some other app config things. The MSI version may possibly work. Since I don't have any bugs in both the store and GitHub versions, could you give me more info on how often it happens

@Samuel12321, Once we move to MSIX packaging, a single .MSIX file could be used for both the store and sideload versions (only the distribution method is different but the installation will be same). That may help us to correct the package for the store (since both version are packaged, bugs can be tracked easily we can use some UWP APIs for app configs, start menu tiles instead of tray icon, proper start up method & logos).

We won't need a .MSI setup anymore and both the store and sideload versions will work exactly the same.

**Comment by Cyberdroid1** [comment]
Well, the crash happened only once till now. So I don't know if it would happen again, as I have switched to non-store version.

**Comment by ShankarBUS** [comment]
@Cyberdroid1, I wouldn't recommend the non store version since it doesn't update automatically. The store version keeps your install clean. So, be up to date of this repository and you can switch to the store version once bugs are fixed.

**Comment by Samuel12321** [comment]
That will make things much easier, have been having trouble trying to make both MSI and MSIX work. Makes sense anyway if we are only targeting Windows 10, no need to have the MSI. Will also prevent SmartScreen / security issues as that is all taken care of with store distribution.

@ShankarBUS I was wondering if I could become a collaborator on this project. I would love to be able to contribute more to this great idea, and it would make it easier for making small adjustments for any MS Store requirements. With that being said, i understand if you wish to remain the only collaborator on this project.

**Comment by ShankarBUS** [comment]
@Samuel12321

> I was wondering if I could become a collaborator on this project. I would love to be able to contribute more to this great idea, and it would make it easier for making small adjustments for any MS Store requirements.

Yes! I was thinking the exact same about a minute ago (saw your fork and thought you won't need a fork if you're a collaborator). You may require to delete your fork (I'm not sure though). You helped me a lot!

> With that being said, i understand if you wish to remain the only collaborator on this project.

No, I always want contributors. ADeltaX is already a collaborator. I didn't want to disturb you. That's it.

**Comment by ShankarBUS** [comment]
@Samuel12321, done! sent you an invite.

**Comment by Samuel12321** [comment]
@ShankarBUS Thanks

**Comment by ShankarBUS** [comment]
> @ShankarBUS Thanks

I'm really happy to have online pals 😁

**Comment by ShankarBUS** [comment]
So @Cyberdroid1,
I guess the bug won't come again 😉. If you experience this bug again in the future, feel free to re-open this issue 👋

**Comment by Cyberdroid1** [comment]
Yeah, I haven't this issue again yet. Will open if I face this.
