### ISSUE TITLE
Bug: When try to adjust volume from headset,it shows old layout.

### ISSUE THREAD

**Issue by Sahiru2007** [ShankarBUS/ModernFlyouts#260]
**Describe the bug:**

**To Reproduce:**

**Screenshots:**

**OS Version:**
 - Windows 10 Version: 

**ModernFlyouts Version:**
 - Version: 

**Additional context:**

**Comment by ShankarBUS** [comment]
Duplicate of #4.

I'll close this issue. You can get further information on #4.
