### ISSUE TITLE
Bug: ModernFlyouts does not like EGYPT

### ISSUE THREAD

**Issue by Samuel12321** [ShankarBUS/ModernFlyouts#264]
![Screenshot 2020-11-28 214920](https://user-images.githubusercontent.com/35312698/100497950-9b5ed800-31c3-11eb-8825-c803203a0e4b.png)

Just saw this massive spike of issues in Egypt, not sure what could be causing this.

**Comment by ShankarBUS** [comment]
Why? what the heck?

What's up with Egypt? There are no regional specific code (except localisation).

Why would the bug happen just to a specific region?

**Comment by Samuel12321** [comment]
no idea, i am confused. I almost wonder if this may be a store reporting bug?

**Comment by ShankarBUS** [comment]
It says memory failure. What does that mean? Are they crashes or just non-crashing failures? What're the criticality of this failures?

**Comment by Samuel12321** [comment]
no idea, Store doesn't tell me.
That's why I'm working on App centre integration.

**Comment by ShankarBUS** [comment]
What's an App Center?

I don't even understand what a Partner Center is.

Care to explain?

**Comment by Samuel12321** [comment]
Sure:
https://azure.microsoft.com/en-us/services/app-center/ - basically a way to monitor app crashes + other monitoring / dev tools if we want in the future.
Partner centre is the tool / web site to add an app and manage an app on the MS Store.

**Comment by ShankarBUS** [comment]
Oh they are mutually exclusive!

The terminology confused me.

They should have swapped the names like this

App Center: for publishing and managing apps on MS Store
Partner Center: for diagnostics and analytics of the application.

Why would they use such confusing names????🤦‍♂️

**Comment by Samuel12321** [comment]
Because its Microsoft and it wouldn't be right if naming was logical.

I believe Partner centre came first (when the store was first release), i think app centre is new.

**Comment by Cyberdroid1** [comment]
I guess people's PCs have some overheating issues there in Egypt. Crashing the memory...😂

JK

**Comment by Samuel12321** [comment]
I think it may have been a partner centre bug or something, as it is not occurring now.
Will close this for now, but will open if it happens again
