### ISSUE TITLE
Flyout appears when button is pressed instead of when functions are enabled

### ISSUE THREAD

**Issue by IAmNotAJerk** [ShankarBUS/ModernFlyouts#265]
I'm currently using [Capslock Plus](https://github.com/wo52616111/capslock-plus) which allows macro hotkeys when long pressing capslock key in combination with other keyboard buttons. Capslocks should not be locked or unlocked according to the set up, but Modern Flyout always appears to remind me the current state of capslock whenever the key is long pressed. Sometimes it even messed to the old set up and forced enabled unlock/lock capslock for me (which is not the case when Modern Flyout is not installed.)

**Comment by ShankarBUS** [comment]
FYI:
We don't control the key. The app won't affect the lock state. It just shows a flyout. That's it.

I agree with you. The flyout shouldn't be shown just after pressing but should be shown after the key has been released.

Great suggestion!

**Comment by ShankarBUS** [comment]
Tah tah tah,

Caps, Num and Scroll lock are toggled at the instant of the key press and won't care of long press or key up.

We show a flyout just after the key state has been toggled.

IMO our current behaviour is correct.

One shouldn't rely on long key press to run a script or macro TBH.

Changing this behaviour (i.e. showing flyout after key up) will still affect your ahk setup. It will also affect other users.

So, for your case, you can disable the caps lock key flyout in our app's settings.

**Comment by Samuel12321** [comment]
Agreed

**Comment by IAmNotAJerk** [comment]
Agree, I'll keep using both the AHK script and Modern Flyout maybe as suggested. 
I used to use the Capslock indicator from my laptop manufacturer, it work just fine without the problem stated. Not sure if that is only possible on the BIOs side and not applicable to this program, might worth investigating. Anyways, thanks.
