### ISSUE TITLE
The present problems of the Modern Flyouts

### ISSUE THREAD

**Issue by Gaoyifei1011** [ShankarBUS/ModernFlyouts#267]
1.Modern Flyouts在后台运行打开设置时会卡住，有时候就显示成黑屏，不管是拖动窗口还是点击按钮都无法进行操作，过几秒后就可以进行操作了
2.Modern Flyouts有一个选项没有汉化，就是Personalization，应该翻译成“个性化”。
1. Modern Flyouts runs in the background to open the Settings will be stuck, sometimes will show black screen, drag the window or click on the button can't operate, after a few seconds can operate
 2. Modern Flyouts an option not localization, Personalization is, should be translated as "个性化".
![image](https://user-images.githubusercontent.com/49179966/100519365-5c844e80-31d2-11eb-860e-b7540d929dac.png)

**Comment by Cyberdroid1** [comment]
Are you on latest version? If not, please update.

**Comment by Gaoyifei1011** [comment]
Yes,it has been up to date.The installed version of the Modern Flyouts is 0.8.1

**Comment by Cyberdroid1** [comment]
> Yes,it has been up to date.The installed version of the Modern Flyouts is 0.8.1

The latest version 0.8.2 would be reaching you sometime soon. Please do update to that version and update this issue according to that.

**Comment by Gaoyifei1011** [comment]
OK.I know.I am waiting for the new version to arrive

**Comment by Samuel12321** [comment]
Fixed in 0.8.3. 
Has been submitted to store, should be rolling out soon.
