### ISSUE TITLE
Feature Request:Hope to be able to turn on the switch of laptop touchpad and a modern layout

### ISSUE THREAD

**Issue by Gaoyifei1011** [ShankarBUS/ModernFlyouts#268]
笔记本上面有一个触摸板的开关用来打开或者关闭触摸板，但目前Windows并没有这一方面的按钮开关显示，希望Modern Flyouts能够为笔记本触摸板开关添加一个现代布局
Laptop with a touchpad switch is used to open or close the touch pad, but the current Windows didn't this aspect of the button switch, according to hope that Modern Flyouts to add a Modern laptop touchpad switch layout

**Comment by Cyberdroid1** [comment]
> 笔记本上面有一个触摸板的开关用来打开或者关闭触摸板，但目前Windows并没有这一方面的按钮开关显示，希望Modern Flyouts能够为笔记本触摸板开关添加一个现代布局
> Laptop with a touchpad switch is used to open or close the touch pad, but the current Windows didn't this aspect of the button switch, according to hope that Modern Flyouts to add a Modern laptop touchpad switch layout

Apparently, many of these specific keys are OEM managed, not all functions can be added to the app. There are various OEM keys like these. Even if it were possible, it would not be worth it. I hope you understand.

**Comment by Samuel12321** [comment]
i know the button you are referring to, unfortunately this is managed by firmware and is not passed on to the os. 
Because of this we cant do anything about it.
