### ISSUE TITLE
Small request - Change the animation of LockKeys flyout

### ISSUE THREAD

**Issue by Cyberdroid1** [ShankarBUS/ModernFlyouts#27]
The animation of LockKeys flyout is different from flyouts of Sound and Brightness. While Sound and Brightness flyouts come into view by fading in from top, while LockKeys come in by fading in from bottom. Can you please change this animation? It might be a small fix. Or did you intend it to be that way?

**Comment by ShankarBUS** [comment]
It is intended 😉. The volume and brightness will be attached to the top bar (and will slide down). The media controls, airplane and lock key flyouts will slide up. It will be boring to have the same effects, so I thought it would be nice to do some tweaks.

![Audio_Light](docs/images/Audio_Light.png)
_(see how the volume control is fused with the top bar)_

![LockKey_Caps_Light](docs/images/LockKey_Caps_Light.png)
_(this is separated from the top and animates differently)_

**Comment by Cyberdroid1** [comment]
Oh, thanks for telling. But the downward animation when fading out doesn't look that nice (IMO, no offense). It would be cool if it fades out sideways (if it's possible). Though the decision depends on you. Just a mere suggestion.

**Comment by ShankarBUS** [comment]
I'm always welcome to suggestions. The design may change depending on new features. You can see yourself how much has changed since v0.1

Will investigate on this topic. Anyways, thanks for the suggestion

**Comment by ShankarBUS** [comment]
Hey @Cyberdroid1,

Any opinions

![image](https://user-images.githubusercontent.com/63704247/93195247-a4b0da80-f766-11ea-9f3a-36c90ac450ad.png)

![image](https://user-images.githubusercontent.com/63704247/93195321-bd20f500-f766-11ea-8bd7-539a9a65f58f.png)

I made some more changes to make the open/closing animations smooth.
What do you think?

**Comment by Cyberdroid1** [comment]
Is this a gif?. Looks good, btw. Will it have the same animation as others?

**Comment by ShankarBUS** [comment]
No it's a stable image. I made new smooth animations for open/close.

Can't provide a gif because it won't be smooth.

All the flyouts now have the same animation.

Before this the media card and the volume will slide opposite to each other. Now they animate as a single entity.

Thanks for your feedback

**Comment by Cyberdroid1** [comment]
Ohk, thanks! Will this be added in v0.5 ?

**Comment by ShankarBUS** [comment]
Yes!

**Comment by Cyberdroid1** [comment]
YAY!! Looking forward to it!! 🎉🎉

**Comment by ShankarBUS** [comment]
Implemeted in a12f3f65e7c07ff4dc9074f23bd9bbd7d9236639.

And will be available in v0.5.0

**Comment by ShankarBUS** [comment]
![ModernFlyouts](https://user-images.githubusercontent.com/63704247/93300326-3165a200-f814-11ea-9f5f-8aea652b54eb.gif)

Sneak peek 😁. So can I close this issue now?

**Comment by Cyberdroid1** [comment]
Does it look laggy due to being a gif?

Sure, you can close it. Thanks a lot for taking this into consideration.

**Comment by ShankarBUS** [comment]
> Does it look laggy due to being a gif?

Yes! That's what I said.

> Can't provide a gif because it won't be smooth.

**Comment by Cyberdroid1** [comment]
Ok, thanks.
