### ISSUE TITLE
Bug: Default Y value always reverts to 1

### ISSUE THREAD

**Issue by Robzyy** [ShankarBUS/ModernFlyouts#271]
**Describe the bug:**
Default Y value always reverts to 1

**To Reproduce:**

**Screenshots:**

**OS Version:**
 - Windows 10 Version: 20H2

**ModernFlyouts Version:**
 - Version: 0.8.0.1 

**Additional context:**
The 'Flyout default position' setting has a red outline, what is that supposed to mean? Couldn't make it go away.

**Comment by ShankarBUS** [comment]
Post a screenshot

**Comment by Cyberdroid1** [comment]
https://github.com/ShankarBUS/ModernFlyouts/issues/274#issuecomment-735652418

Should fix.

**Comment by ShankarBUS** [comment]
This issue is related to #223.

Please keep up with that issue.
