### ISSUE TITLE
Not displaying with full screen mode in Movies & TV (standard Windows 10 app)

### ISSUE THREAD

**Issue by pav2805** [ShankarBUS/ModernFlyouts#272]
Not displaying with full screen mode in Movies & TV (standard Windows 10 app)

**Comment by Samuel12321** [comment]
Hi, thanks for reporting this.
We are aware of this issue (#32). Please see #32 for further updates on this issue.

**Comment by ShankarBUS** [comment]
Duplicate of #32.

I do understand your pain because I too experience this issue 😅😂.

We've turned all our focus into this issue and you may expect a quick fix within a couple of weeks.
