### ISSUE TITLE
0.8.2 release from GitHub: Untrusted App

### ISSUE THREAD

**Issue by GoldenHashtag** [ShankarBUS/ModernFlyouts#279]
![image](https://user-images.githubusercontent.com/40300931/100695981-67570300-33cd-11eb-97c1-dd7b1e9ea0d9.png)
![image](https://user-images.githubusercontent.com/40300931/100696089-a84f1780-33cd-11eb-9d2e-7408ccf0c55c.png)

Either provide the corresponding public key to use with installation or repackage a new release with Microsoft certificate.

**Comment by Samuel12321** [comment]
new package will be released soon
