### ISSUE TITLE
Some problems about the version 0.8.2

### ISSUE THREAD

**Issue by Gaoyifei1011** [ShankarBUS/ModernFlyouts#285]
Some problems about the version 0.8.2
关于版本0.8.2的一些问题
Now on making the Releases interface saw 0.8.2 version information, but did not see the Microsoft Store and making post 0.8.2 version of the installation file, is what's the problem?
目前在GitHub的Releases界面上面看见了0.8.2的版本信息，但是目前并没有看见在Microsoft Store和GitHub上面发布0.8.2版本的安装文件，是发生了什么问题？

**Comment by Samuel12321** [comment]
having some trouble with store certification, 0.8.2 will be properly released to store and GitHub shortly.
