### ISSUE TITLE
Feature Request: Add support for brightness control of external monitors

### ISSUE THREAD

**Issue by Bourbon0212** [ShankarBUS/ModernFlyouts#286]
**Support for brightness control of external monitors through DDC/CI**

Your app create a very beautiful control panel for monitor's brightness, but that functionality will only work for laptops.
To control brightness of desktops' monitors or external monitors,  still need another app (e.g. [emoacht/Monitorian](https://github.com/emoacht/Monitorian))

So what I'm suggesting here is that maybe you can implement DDC/CI control within your app, making basic brightness control possible besides alter the layout panel?

Though this request may be out of your scope (totally not user-interface related), I still hope this feature can be implemented in the future. Anyway, I really love this beautiful app ❤

**Comment by ShankarBUS** [comment]
Already planned.

There's already a feature request regarding this.

See #102.

I'll close this as a duplicate.
