### ISSUE TITLE
Bug:about an error default position

### ISSUE THREAD

**Issue by ZhReimu** [ShankarBUS/ModernFlyouts#288]
**Describe the bug:**
when the Flyout default position was set to invisible position,then it would be can not saw anymore until reset data

**To Reproduce:**

**OS Version:**
 - Windows 10 Version:  Windows 10 1909]

**ModernFlyouts Version:**
 - Version:  v0.8.0.1

**Comment by ShankarBUS** [comment]
Update the app.

We have added the ability to reset just the position of it in a newer release IIRC.
