### ISSUE TITLE
Proposal|Question: Use JumpList instead of Tray/Notification Area Icon?

### ISSUE THREAD

**Issue by ShankarBUS** [ShankarBUS/ModernFlyouts#30]
We are currently using the **Tray/Notification Area Icon** as a place to interact with the apps settings or to terminate it.

The **Tray/Notification Area** has been there since the initial stages of Windows OS and were a great way for background apps to interact with users without any additional windows opening.

But they are now considered as obsolete or old tech and UWP apps are already using different APIs to compete with the tray icon (such as [JumpList](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.StartScreen.JumpList), live tiles and toast notifications & etc.)

Since by plan we are eventually moving to MSIX, it will be an opportunity for us to do the same **"Modern methods"** that UWP apps do.

**For context :**

![image](https://user-images.githubusercontent.com/63704247/91955990-a075cd80-ed21-11ea-9b82-79478117a60f.png)
_Current method using tray icon for hosting the menu_

![image](https://user-images.githubusercontent.com/63704247/91955954-90f68480-ed21-11ea-8bd6-0de59e900b0e.png)
_MS Edge Dev's context menu containing jump list tasks for opening new windows_

This issue is not only a proposal but a question for users about what they think. And to travel the path which they favour.

Also the Tray/Notification Area won't be visible in **Tablet mode**. So the proposed method will be a modern and viable alternative.

There are still some issues surrounding this topic :
[Proposal: Have WinUI Desktop support the UWP Jumplist API](https://github.com/microsoft/microsoft-ui-xaml/issues/2005)
[Proposal: System tray icon for WinUI 3 Desktop (Win32 and .NET Core)](https://github.com/microsoft/microsoft-ui-xaml/issues/2020)

**Comment by ShankarBUS** [comment]
Hey @ADeltaX, @Samuel12321, @Cyberdroid1 and others (if there are) any opinions?

**Comment by Cyberdroid1** [comment]
If the notification tray icon would be removed, jump lists would be cool. Just that we must inform the user that to access settings, one must right-click on the app icon and select settings to open it.

If the notification tray icon stays, better to keep the context menu for it.

**Comment by ShankarBUS** [comment]
Should we keep both methods?

**Comment by Samuel12321** [comment]
I personally have mixed thoughts about this, on one hand it is a familiar and expected app interaction method, but i am also all for using the most modern methods. 
The migration to MSIX is the best time to do it , however it is probably is the lowest priority

**Comment by Samuel12321** [comment]
keeping both methods might be best, but enhance the context menu and allow the tray icon method to be disabled (default enabled)

**Comment by Cyberdroid1** [comment]
Initially, I think we can, for a couple of releases. Let people get accustomed to it, and then maybe remove the tray icon (after proper information). But, is it possible that the app would run in background even after removing the tray icon?

**Comment by Samuel12321** [comment]
> If the notification tray icon stays, better to keep the context menu for it.

agreed

**Comment by ShankarBUS** [comment]
The tray icon doesn't affect the app running, it's just a way to tell the users whether the app is running or not and let them interact without opening additional windows.

**Comment by Cyberdroid1** [comment]
I read those proposals given above. I don't think the system tray would be removed in the near future. Still, I think we should remove the tray icon. And probably fix the start on boot for store version of app. That would be great.

**Comment by Samuel12321** [comment]
> I read those proposals given above. I don't think the system tray would be removed in the near future. Still, I think we should remove the tray icon. 

i still think both methods might be best, but enhance the context menu and **allow the tray icon method to be disabled** (default enabled)

>And probably fix the start on boot for store version of app. That would be great.

already working on it for 0.4

**Comment by ShankarBUS** [comment]
@Cyberdroid1

> If the notification tray icon stays, better to keep the context menu for it.

There will be no reason to keep the tray icon without the menu, it's the only reason to have it.

@Samuel12321

> enhance the context menu

Can you elaborate?

**Comment by ShankarBUS** [comment]
Thank you all for feedback. Both JumpList and TrayIcon now work.

**Comment by Cyberdroid1** [comment]
Can the Tray Icon be hided with a setting in v0.4 ?

**Comment by ShankarBUS** [comment]
The tray icon is a must that shouldn't be taken away. While it is easy to implement an option to hide it, it shouldn't be. I wanted to provide an alternative approach incase the tray goes away.

**Comment by Cyberdroid1** [comment]
Hm, ok. Thanks for telling.

**Comment by ShankarBUS** [comment]
Thanks for feedback! Try v0.4.0 once it's out
