### ISSUE TITLE
Playback status not updating properly.

### ISSUE THREAD

**Issue by Cyberdroid1** [ShankarBUS/ModernFlyouts#33]
Whenever I am playing some music, the playback status comes properly in system volume flyout, but not for Modern Flyouts. It sometimes hangs on the same thing and does not update. Relaunching fixes this issue but I have to adjust the flyout position again and again to my likes. 

Please see to it.

**Comment by ShankarBUS** [comment]
I'm sorry that you're experiencing this bug.

What Windows 10 version are you using?

If you're using Windows 10 2004, then see #29. This is a known limitation and will be fixed in the future.

**Comment by Cyberdroid1** [comment]
I am using Windows 10 2009 (Beta Channel). Maybe mostly similar to Win10 2004. 

Ok, when will it be fixed?

**Comment by ShankarBUS** [comment]
The required API has been broken in the **"OS"** since Windows 10 2004. So there are chances it being in the latest Windows version.

It could be somehow fixed. So this is a duplicate of #29

**Comment by Cyberdroid1** [comment]
Ok, I will close this.

**Comment by ShankarBUS** [comment]
It's one of main feature of this app.

It should be & will be fixed in the near future.
