### ISSUE TITLE
clr_exception_system.overflowexception_80131516_modernflyouts.exe!unknown

### ISSUE THREAD

**Issue by Samuel12321** [ShankarBUS/ModernFlyouts#35]
Microsoft Partner centre app analytics has revealed that this is the second most common bug:
clr_exception_system.overflowexception_80131516_modernflyouts.exe!unknown
[stackTrace.txt](https://github.com/ShankarBUS/ModernFlyouts/files/5217248/stackTrace.txt)
Bug occurred on OS build: 10.0.19041.508

@ShankarBUS Any ideas what might be causing this?

**Comment by ShankarBUS** [comment]
I really don't know a bit about it 😅. How can I reproduce this on my machine?

**Comment by Samuel12321** [comment]
I'm not sure, unfortunately that's all MS store provides

**Comment by ShankarBUS** [comment]
Does the app even work?

**Comment by Samuel12321** [comment]
Seems to, over 400 users who haven't reported a problem.

**Comment by ShankarBUS** [comment]
400 users? Really?

Has the v0.4.0 been released?

**Comment by Samuel12321** [comment]
489 total installs, 20 reported crashes, 89 inactive users (uninstalls)

**Comment by Samuel12321** [comment]
not yet was waiting to fix non x86 bug first

**Comment by Cyberdroid1** [comment]
When will v0.4 be out in MS Store? I know it takes a while. Next time, @ShankarBUS , release the MS Store version first. When it comes out, then release GitHub version. It will help in consistency.

**Comment by ShankarBUS** [comment]
> When will v0.4 be out in MS Store?

@Samuel12321, is it out yet?

> Next time, @ShankarBUS , release the MS Store version first. When it comes out, then release GitHub version. It will help in consistency.

Yes! that's how it should be

**Comment by Cyberdroid1** [comment]
I checked on MS Store right now, it still has version 0.3.3. I think it might take a while.

**Comment by ShankarBUS** [comment]
Yes the same for me. But please be patient 😁

**Comment by Samuel12321** [comment]
i released the update to the MS store this morning (8 hours ago) but it is still in certification testing.
Usually the change is published within an hour, but it can take up to 3 days.

**Comment by ShankarBUS** [comment]
Why is this closed @Samuel12321?

Is it fixed?

**Comment by Samuel12321** [comment]
My mistake, i was looking through store failures log, and this one had disappeared. Turns out it was just on the second page that didn't see.

**Comment by ShankarBUS** [comment]
Hey @Samuel12321,

I guess these exceptions shouldn't happen now.

Could you verify?

**Comment by ShankarBUS** [comment]
The bug must have been fixed with #113.

I'm kinda sure this wouldn't happen in the future.

Please verify 😄.

**Comment by Samuel12321** [comment]
yes this is no longer being reported.
