### ISSUE TITLE
Monochrome tray icon

### ISSUE THREAD

**Issue by Cyberdroid1** [ShankarBUS/ModernFlyouts#39]
@ShankarBUS, can we use a monochrome color tray icon for the system tray? It would look better and feel consistent with other system tray icons. 

![image](https://user-images.githubusercontent.com/51435948/93464293-96012980-f906-11ea-95f7-5e0c8fd391d6.png)

Due to being colored, the icon is not properly visible. We can keep the start menu icon colored but the tray icon be monochrome.
Have a look at the QuickLook icon in the pic above.

**Comment by ShankarBUS** [comment]
Nice suggestion!

But doesn't PowerToys, Windows Defender have coloured tray icons?

**Comment by Cyberdroid1** [comment]
Yeah, I agree. But this app's icon is blue in color, and it suits. But it doesnt look that good when in small. Try making an out line icon and add gray shades.

**Comment by Cyberdroid1** [comment]
Windows Security icon is also blue (coming soon). But I think it doesn't look good. For Powertoys, their icon has multiple colors but a white base, which is still good.

**Comment by ShankarBUS** [comment]
Good thing that I still have the original PSD. I can create a monochrome variant.

**Comment by ShankarBUS** [comment]
Hey @Cyberdroid1,

I'm not an expert artist or experienced in photo editing. The output seems to be low quality and looks ugly.

I'm attaching the original PSD file with this comment. If anyone wants to contribute, they can use the PSD file and generate the required images and attach them in a new comment or do a PR.

[ModernFlyouts_LOGO_PSD.zip](https://github.com/ShankarBUS/ModernFlyouts/files/5241192/ModernFlyouts_LOGO_PSD.zip)

**Comment by Cyberdroid1** [comment]
I tried a bit.

![ModernFlyouts](https://user-images.githubusercontent.com/51435948/93556954-7d8d1f80-f997-11ea-9840-9708542dc108.png)

What do you think?
We just have to keep it grayscale. Nothing much.

**Comment by ShankarBUS** [comment]
It shouldn't be grey scale. Only those outlines must be present.

**Comment by Cyberdroid1** [comment]
Hmm, but that would lead to less visibility in the system try, no? Windows supports colorful system trays. Going with grey scale would be better. Can you try this locally?

**Comment by ShankarBUS** [comment]
Will try it

**Comment by ShankarBUS** [comment]
> Hmm, but that would lead to less visibility in the system tray, no?

That's why I couldn't make it work and then uploaded the PSD. It shouldn't be grey scale, it be either black or white outlined not filled

That's criteria for high contrast icons

**Comment by Cyberdroid1** [comment]
Transparency would cause problem in tray. BG color might bleed through and ruin the look (IMO). 

Try using both transparent and the greyscale icons one by one. Lets see how it would look.

**Comment by Samuel12321** [comment]
On a black / dark tray/ taskbar, the blue icon actually looks quite good, and a grey one would be hard to see

**Comment by ShankarBUS** [comment]
@Samuel12321,

Yes! It's gotta be either black(for light theme)/white(for dark theme) not grey.

**Comment by Cyberdroid1** [comment]
I played a bit colors and have 2 examples.

![mf 1](https://user-images.githubusercontent.com/51435948/93573801-36158c00-f9b5-11ea-9ada-df3ed93baddd.png)
(for light theme)

![mf 2](https://user-images.githubusercontent.com/51435948/93573862-46c60200-f9b5-11ea-86e2-4c875c689d42.png)
(for dark theme)

![mf 3](https://user-images.githubusercontent.com/51435948/93574365-f4391580-f9b5-11ea-863a-948b8c5e2047.png)
(dark theme second try)

Tell me what is wrong and what if right.

**Comment by Samuel12321** [comment]
I personally think it may be better to just leave it as it is (blue) to reduce complexity and so it is visible with both dark and light themes. Currently also matches with new windows icon styling.

**Comment by Samuel12321** [comment]
and matches with icons through the rest of the app

**Comment by Cyberdroid1** [comment]
But the thing is, its visibility is low on coloured system tray ( see first comment).

**Comment by ShankarBUS** [comment]
@Cyberdroid1, the 1st are good indeed.

@Samuel12321, has a good point though

**Comment by Cyberdroid1** [comment]
![image](https://user-images.githubusercontent.com/51435948/93574852-8f31ef80-f9b6-11ea-8a0b-c81eaebca4f5.png)
(dark)

![image](https://user-images.githubusercontent.com/51435948/93574932-a375ec80-f9b6-11ea-81b0-61da63d4c9ff.png)
(light)

**Comment by Cyberdroid1** [comment]
I agree that the current icon is good, but on colored taskbars, it blends with other accent colors like blue. Keeping it monochrome would remove this issue altogether. Also, having the icon dynamic would be great to look.

**Comment by Cyberdroid1** [comment]
Hey, I had a look at the icons again. The first one would look good on both light and dark theme of Windows. Choosing any other would not be great.
What do you think?

**Comment by ShankarBUS** [comment]
Yes! We can use for tray since they are small the should be filled (and the outlines will be cut out like holes) instead of outlined. For the start menu icons in high contrast we can use outlined icons (complement to tray icons).

This is planned post v0.5.0

**Comment by Cyberdroid1** [comment]
Please don't change the Start menu reaction. Keep it the way it looks. It looks nice in blue for start menu.

**Comment by ShankarBUS** [comment]
Not the normal one only the **"high contrast"** ones

**Comment by Cyberdroid1** [comment]
Oh, I see. I hadn't understood earlier.

Yeah, go ahead with the plan!

**Comment by ShankarBUS** [comment]
@Cyberdroid1
It's my turn (heavily inspired by your work 😅😁)
**Light :**
![ModernFlyouts_Black_1024](https://user-images.githubusercontent.com/63704247/93679063-e5905280-faca-11ea-89e8-677ee2245e14.png)
**Dark :**
![ModernFlyouts_White_1024](https://user-images.githubusercontent.com/63704247/93679239-f4770500-faca-11ea-8488-c84bef910024.png)

I really like the 1st and 2nd ones you posted. But they don't match the contrast guidelines, they have colors other than black/white. While mine's just black/white images with holes punched (Why didn't I think of this earlier, thanks @Cyberdroid1 for your inspiraton 😁)

@Samuel12321, can we also include these in the packager (for Badge logo)?

**Comment by Cyberdroid1** [comment]
Won't the background color of task manager bleed through it?

**Comment by ShankarBUS** [comment]
No I guess, It shouldn't.

These icons are all just monochrome, the task bar color doesn't bleed through them

![image](https://user-images.githubusercontent.com/63704247/93685556-c1824080-facd-11ea-9d76-8c6c7d87ab19.png)

**Comment by ShankarBUS** [comment]
We may need extra care for 16x16 and 24x24 size images, so that they are crystal clear. We may have to do a pixel art just for the low res images that are going to used in the TaskBar tray area icon

**Comment by Cyberdroid1** [comment]
> We may need extra care for 16x16 and 24x24 size images, so that they are crystal clear. We may have to do a pixel art just for the low res images that are going to used in the TaskBar tray area icon

How is the current tray icon all clear? Was there a 16x16 icon for that?

**Comment by ShankarBUS** [comment]
> How is the current tray icon all clear? Was there a 16x16 icon for that?

The blue one. No it was just resized, not optimized for low res 😅

**Comment by ShankarBUS** [comment]
Tried some pixel art 😅. Not a good outcome though

**16x16 :**
![ModernFlyouts_Black_16](https://user-images.githubusercontent.com/63704247/93686562-aa931c80-fad4-11ea-9bb8-54b85c898b1c.png)

**Comment by Cyberdroid1** [comment]
Try the same with the white one.

**Comment by Cyberdroid1** [comment]
Thin down the borders and lines. Might work.

**Comment by ShankarBUS** [comment]
@Cyberdroid,

> Try the same with the white one.

That's relatively easy just invert `(Ctrl + I)` the color in Adobe Photoshop.

Didn't include it due to Github being light theme and it's mid night here 😅

**Comment by Cyberdroid1** [comment]
I was using GitHub in dark mode on my phone, and yes, its midnight here too.

**Comment by Samuel12321** [comment]
> @Samuel12321, can we also include these in the packager (for Badge logo)?

while i don't agree with the change, once they are up on GitHub i can add them.

**Comment by ShankarBUS** [comment]
Why @Samuel12321?

1. We're not gonna use them as tray icons by default, there will an option to choose it.

2. We need monochrome logos anyways for a packaged app (will be used in high contrast mode and others scenes)

What would you like my pal?

**Comment by ShankarBUS** [comment]
I also noticed there is a misalignment in the original blue logo, it's a bit offset. I fixed it in the PSD, have to update all the images.

Do we need a one with drop shadow for the start menu logo @Samuel12321? If so, which image should I replace so that just the start menu logo has drop shadow like others fluent design icons?

**Comment by Samuel12321** [comment]
> Why @Samuel12321?
> 
> 1. We're not gonna use them as tray icons by default, there will an option to choose it.
> 2. We need monochrome logos anyways for a packaged app (will be used in high contrast mode and others scenes)
> 
> What would you like my pal?

Sorry misunderstood, thought you were changing all the logos to monochrome as default.

**Comment by ShankarBUS** [comment]
> Sorry misunderstood, thought you were changing all the logos to monochrome as default.

That would be the worst idea 🤣

**Comment by Samuel12321** [comment]
> Do we need a one with drop shadow for the start menu logo @Samuel12321? If so, which image should I replace so that just the start menu logo has drop shadow like others fluent design icons?

not sure, I'm guessing its the one marked small tile

**Comment by ShankarBUS** [comment]
> not sure, I'm guessing its the one marked small tile

Thanks!

**Comment by ShankarBUS** [comment]
This is how it look folks :

### MonoChome :
**System Dark :**

![image](https://user-images.githubusercontent.com/63704247/93706945-a30d5b00-fb48-11ea-8495-df20993d82a9.png)

**System Light :**
![image](https://user-images.githubusercontent.com/63704247/93706996-ef589b00-fb48-11ea-9445-8115b067c2ba.png)

**System coloured taskbar :**

![image](https://user-images.githubusercontent.com/63704247/93707032-24fd8400-fb49-11ea-9534-5ccb5ecf5e9a.png)

### Coloured :

**System Dark :**

![image](https://user-images.githubusercontent.com/63704247/93707088-7d348600-fb49-11ea-9314-1fc8ca6a8f32.png)

**System Light :**

![image](https://user-images.githubusercontent.com/63704247/93707100-8de4fc00-fb49-11ea-8da3-d496be2cffad.png)

**System coloured taskbar :**

![image](https://user-images.githubusercontent.com/63704247/93707068-69891f80-fb49-11ea-872c-42fb84f0ac4e.png)

I'm aware that the monochrome icons and the coloured icon doesn't look the same. It was for contrast reasons 😅.

**Comment by Cyberdroid1** [comment]
Looks awesome to me! Looks different, but bold. Nice designing!

**Comment by ShankarBUS** [comment]
Thanks @Cyberdroid1 & @Samuel12321 for your involvement. It means a lot to me 👊🤗

**Comment by Cyberdroid1** [comment]
*Fistbump*

Which version will bring these new icons?

**Comment by ShankarBUS** [comment]
v0.6, since require additional options in setting.

**Comment by Samuel12321** [comment]
Looks Brilliant, Well done

**Comment by ShankarBUS** [comment]
@Cyberdroid1, what should the setting to contol monochrome/colored tray icon say?
For e.g. "Use monochrome tray icon", "Use colored tray icon", "Show monochrome icon on tray", "Show colored icon on tray".
Which will be user friendly?

**Comment by Cyberdroid1** [comment]
What about -

Tray icon ---
 (   )  Colored    
 (   )  Monochrome


Keep the sentences short and clean. That should be kind of a goal

**Comment by ShankarBUS** [comment]
Done! 7aa0c8c31562d9b407f8b628a913e0312a3d77ea

v0.6.0 bois
