### ISSUE TITLE
Double tap on tray icon opens blank window

### ISSUE THREAD

**Issue by Cyberdroid1** [ShankarBUS/ModernFlyouts#40]
When we double tap on app's tray icon, it opens a blank settings window which is completely unresponsive. Please fix this.

**Comment by ShankarBUS** [comment]
#12?

**Comment by Cyberdroid1** [comment]
Can be related to that.

**Comment by Cyberdroid1** [comment]
Can you reproduce this?

**Comment by ShankarBUS** [comment]
No! That's why I'm confused. I guess I have to set up a VM to test the app. I have no bugs in production.

**Comment by Cyberdroid1** [comment]
Why do I face these issues all the time? 😂😂😂

**Comment by ShankarBUS** [comment]
Shall we close this as a duplicate of #12. It's the same cause soo....

**Comment by Cyberdroid1** [comment]
Yeah, ok.

**Comment by ShankarBUS** [comment]
> Why do I face these issues all the time? 😂😂😂

You could be cursed 🤣🤣🤣

**Comment by Cyberdroid1** [comment]
🤣🤣🤣
