### ISSUE TITLE
Add support for Dopamine music player for Windows

### ISSUE THREAD

**Issue by Cyberdroid1** [ShankarBUS/ModernFlyouts#42]
Please add support for stop, repeat, shuffle, timeline info for the app Dopamine music player. 

Link - https://github.com/digimezzo/dopamine-windows

**Comment by ShankarBUS** [comment]
Is that supported by the stock windows flyout?

**Comment by Cyberdroid1** [comment]
Stock flyout just shows play/pause, previous, next. Same supported by ModernFlyouts. Don't know whether it supports skip, repeat, stop, etc.

**Comment by Cyberdroid1** [comment]
The repo is active. I will open the issue.

**Comment by ShankarBUS** [comment]
Found the target code to change. 
This is the class - https://github.com/digimezzo/dopamine-windows/blob/38caa8a21903a60b40e17692f3491d5ea64175b4/Dopamine/Services/Notification/NotificationService.cs

I'll do a pull request post v0.5

**Comment by Cyberdroid1** [comment]
Ok, thanks.

**Comment by Cyberdroid1** [comment]
A weird bug now. Whenever I launch this app and use shortcuts to skip, play/pause, etc. in this music player, the system UI pops up with the media flyout. ModernFlyout is not even showing the media flyout! It doesnt know whether music is playing or not.

**Comment by ShankarBUS** [comment]
Yep reopen it. Seems to be a different issues. But it may take weeks to fix this one.

**Comment by Cyberdroid1** [comment]
I don't have the button to reopen it, weirdly.

![image](https://user-images.githubusercontent.com/51435948/93707848-86c0ec80-fb4f-11ea-8231-fd4b6899f7b4.png)

**Comment by ShankarBUS** [comment]
Done!

**Comment by Cyberdroid1** [comment]
Thanks. I really think I am cursed sometimes because of the kinds of bugs I face. XD

**Comment by Cyberdroid1** [comment]
Can you try reproducing this issue on your side? I expect the same behaviour as mine.

**Comment by ShankarBUS** [comment]
Hmm.... weird 🤔🤔🤔. Not even Windows default flyout show me the media transport controls.

![image](https://user-images.githubusercontent.com/63704247/93708310-b58c9200-fb52-11ea-8885-5a1dbb517fa4.png)

Dopamine-Windows just hooked the media keys, not sure if they registered as a **GlobalSystemMediaTransportControlsSession** or use the **SystemMediaTransportControls**.

https://github.com/microsoft/ProjectReunion/issues/127

We can't do anything pal 😞

**Comment by Cyberdroid1** [comment]
😯  😞

**Comment by ShankarBUS** [comment]
Hey @Cyberdroid1 

Is this what you are saying?

![image](https://user-images.githubusercontent.com/63704247/93734832-86c8f700-fbf8-11ea-9bf4-c5710de3d393.png)

![image](https://user-images.githubusercontent.com/63704247/93734844-91838c00-fbf8-11ea-83b5-1fd113acf2b5.png)

Currently they doesn't support shuffle/repeat/stop externally, so we can't hook those controls.

I contacted @digimezzo, they are open for contributions. I will open a PR for this.

**Comment by Cyberdroid1** [comment]
Yes, I meant this only. 

Thanks so much!

**Comment by ShankarBUS** [comment]
@Cyberdroid1,

Done! Opened a PR on the target. I will close this issue, you can track the PR on that repo. If it gets merged, it will be good for us.

The PR : https://github.com/digimezzo/dopamine-windows/pull/1201

My part's done.

**Comment by ShankarBUS** [comment]
Hey @Cyberdroid1, the PR has been accepted & got merged by the Dopamine-windows team 🎊🎊🎊🎉🎉🎉

**Comment by Cyberdroid1** [comment]
Yay! Thanks so much, bro! Nice to see this get accepted!

**Comment by ShankarBUS** [comment]
@Cyberdroid1, I have also added timeline info support to it in https://github.com/digimezzo/dopamine-windows/pull/1206 

Let's hope this will also get merged
