### ISSUE TITLE
Feature: Ability to hide/ disable the media control widget

### ISSUE THREAD

**Issue by Samuel12321** [ShankarBUS/ModernFlyouts#43]
The user may want the media widget not to be displayed so that the flyout is less intrusive and takes up less space. I think the ability to disable it would be nice.

**Comment by ShankarBUS** [comment]
I was thinking of the same. We can implement a sub setting for this.

But even if they hide the media controls widget, the original one won't be shown. ModernFlyouts will just show the volume control. Is this a good behaviour?

**Comment by Samuel12321** [comment]
I think so, Could be re enabled if user wants it again.

**Comment by Poopooracoocoo** [comment]
I personally find it really annoying that the media controls show up when I change the volume and I'd be much happier if it were in the volume flyout. Microsoft has finally done something about that but ironically hasn't changed anything else.

**Comment by ShankarBUS** [comment]
I will provide an option to hide it permanently. When is Microsoft planning to add the media controls to tray?

**Comment by ShankarBUS** [comment]
I will provide an option to hide it in v0.6.

@Poopooracoocoo,

When is Microsoft planning to add the media controls to tray flyout?

Didn't know they were going to do this. Now I feel useless 😑😔

**Comment by Poopooracoocoo** [comment]
I know that there's a feature flag in the insider 21H1 builds but I'm not sure when they'll actually release it. 

It's not surprising that they only half did it and they'll probably release it with 22H1 in its current state, knowing MS :P

**Comment by ShankarBUS** [comment]
Hey guys, this feature would require reorganizing settings into multiple pages and groups.

As a temporary fix, this option would be controllable by a toggle switch under the "Additional" group in the General page.

We need to reorganize settings so that each module get their own page (if they need multiple options e.g. Audio) or a fused page (e.g. Brightness and airplane)

We won't be able to do that until v0.8. So please bear with the current implementation 😅

**Comment by ShankarBUS** [comment]
Ummm, another problem.... When we disable the media transport controls in ModernFlyouts, the stock flyout pops-up

What should we do?

**Comment by ShankarBUS** [comment]
Or How about this?

We should provide an option to show/hide **media transport controls** while pressing **volume keys** and another option to show/hide **volume control** while we press the **media keys**.

What are your thoughts guys?

**Comment by ShankarBUS** [comment]
Ummm, another problem.... When we disable the media transport controls in ModernFlyouts, the stock flyout pops-up while pressing the **media keys**

What would you want me to do?

Or how about this?

We should provide an option to show/hide **media transport controls** while pressing **volume keys** and another option to show/hide **volume control** while we press the **media keys**.

@Samuel12321, @Cyberdroid1, @Poopooracoocoo
What are your thoughts guys?

**Comment by Samuel12321** [comment]
sounds good to me

**Comment by ShankarBUS** [comment]
> sounds good to me

What sounds good to you? Can you mention what it is?

**Comment by ShankarBUS** [comment]
> We should provide an option to show/hide **media transport controls** while pressing **volume keys** and another option to show/hide **volume control** while we press the **media keys**.

In case you refer to this
We can only give an option to show/hide **media transport controls** while pressing **volume keys** currently. The other part could be done in v0.8

**Comment by Samuel12321** [comment]
the option to show/hide media transport controls while pressing volume keys was actually the only thing i was thinking about when i opened this, the idea to be able to control both sounded like a nice option to have. The second part can wait till 0.8

**Comment by Cyberdroid1** [comment]
Sounds good to me too!

**Comment by ShankarBUS** [comment]
Ok I will provide both options in v0.6 release. But we really need to do a lot of re-organization in the Settings Window and improve the usability of it

**Comment by Samuel12321** [comment]
> But we really need to do a lot of re-organization in the Settings Window and improve the usability of it

I think that needs to be the main focus of 0.8.

**Comment by ShankarBUS** [comment]
Yes that's what I said

**Comment by ShankarBUS** [comment]
Fixed in cb23bc2019831224f9f298b77207c3b2b6fd4d1a
