### ISSUE TITLE
Feature: Acrylic sidebar and reveal effect for settings app

### ISSUE THREAD

**Issue by Samuel12321** [ShankarBUS/ModernFlyouts#44]
I think this would look great, similar to the sidebar in the windows 10 settings app.
Obviously low priority.

**Comment by ShankarBUS** [comment]
We can either use FluentWPF for this purpose or re-add the code used for acrylic blur (which removed from this project while porting from AudioFlyout)

But there are some issue with non-UWP desktop (i.e Win32) apps and acrylic effect. This effect is achieved using an undocumented API (which is already being used by many project like EarTrumpet, TaskBarX, TranslucentTaskbar, FluentWPF & etc)

Which is fine, but there will be issues while dragging the window around, it will be stuttering. This subtle effect won't compensate the lag it causes. :(

But if in the future we move to WinUI, that could be possible (this is what PowerToys does).

**Comment by Cyberdroid1** [comment]
Yeah, I faced window drag issue in EarTrumpet app. Lets wait until WinUI 3 gets released.

**Comment by ShankarBUS** [comment]
> Yeah, I faced window drag issue in EarTrumpet app. Lets wait until WinUI 3 gets released.

See https://github.com/ShankarBUS/ModernFlyouts/issues/45#issuecomment-695173713

**Comment by Cyberdroid1** [comment]
Oh, hmmm. Didn't see that.

**Comment by Cyberdroid1** [comment]
Any updates on this?

**Comment by ShankarBUS** [comment]
The chances are too low 😔

**Comment by Samuel12321** [comment]
will close as this has been superseded by #167  and #66
