### ISSUE TITLE
Proper installer

### ISSUE THREAD

**Issue by elenmerbau** [ShankarBUS/ModernFlyouts#5]
Title.

**Comment by ShankarBUS** [comment]
It may take a while 😅😁, you may expect it in the next version.

**Comment by elenmerbau** [comment]
Oh, anything really. I guess the best option is to upload it to the Store, but I assume it's harder than just making a normal installer.

**Comment by ShankarBUS** [comment]
I created an MSI setup file which will automatically add it to the startup and start menu. It will be available in version 0.3.0. Checkout the releases page after I release v0.3.0

**Comment by ShankarBUS** [comment]
Checkout [v0.3.0](https://github.com/ShankarBUS/ModernFlyouts/releases/tag/v0.3.0) it has a setup file.

**Comment by ShankarBUS** [comment]
Hey @elenmerbau 
Just so you know, we have an [MS store version available to download](https://www.microsoft.com/store/apps/9MT60QV066RP). 

Thanks to @Samuel12321 for their help!
