### ISSUE TITLE
Settings window doesn't remember size and position

### ISSUE THREAD

**Issue by Poopooracoocoo** [ShankarBUS/ModernFlyouts#51]

**Comment by ShankarBUS** [comment]
This could be an easy implementation. But is this necessary? I mean it's just a single window, no one will use it after the first installation.

Anyways, Thanks for opening this issue 🤗

**Comment by Poopooracoocoo** [comment]
it's a very low prio issue :pppp don't even need this

**Comment by ShankarBUS** [comment]
But this probably will be a nice improvement tho

**Comment by Cyberdroid1** [comment]
Can we change the default window height to be a tad bit long and reduce the width?

**Comment by ShankarBUS** [comment]
Yes! A nice suggestion. What dimensions you think would be better?

**Comment by Cyberdroid1** [comment]
1260 by 950 ? What do you think?

(950 is height)

**Comment by ShankarBUS** [comment]
1260x950 is fine. But my display res is 1366x768. It will cover most of the screen for everyday users 😅

**Comment by Cyberdroid1** [comment]
What should be the max, according to you?

**Comment by Poopooracoocoo** [comment]
I love setting my windows to 1440x900 on my 1920x1080 screen.

**Comment by ShankarBUS** [comment]
You guys have big displays doesn't mean you must flex on me 😂.

> What should be the max, according to you?

The current res seems to be good IMO. We can implement this feature and you'll be able to save your preffered dimensions of the window.

**Comment by Cyberdroid1** [comment]
I didn't mean to! 😂😂

Ok, it would be nice!

**Comment by Poopooracoocoo** [comment]
It's just a 14" laptop screen haha

Thanks, Shankar!

**Comment by ShankarBUS** [comment]
Implemented in 4ecb9ca32fa1e69ffdb9742c5b5a1f157f7d0003.

Wait for the next release guys 🙂
