### ISSUE TITLE
Option to change the duration of flyout being visible

### ISSUE THREAD

**Issue by Cyberdroid1** [ShankarBUS/ModernFlyouts#53]
Please add a feature to be able to change the duration for which the flyout appears after summoning it.

**Comment by Cyberdroid1** [comment]
Keep it as low priority, but it will be a nice-to-have.

**Comment by ShankarBUS** [comment]
It's a really simple task 😉. But due to other high priority tasks (such as restore default flyout when this app crashes, show the flyout over every window and above lockscreen) this implementation could be delay to v0.8

**Comment by Cyberdroid1** [comment]
Ok, thanks.

**Comment by ShankarBUS** [comment]
You are not gonna believe what I planned for v1.0

Too many features planned. Gonna keep it a secret 😜

**Comment by Cyberdroid1** [comment]
Gotta keep the excitement up! Keeping them secret would be hard, no? 😜😁

**Comment by ShankarBUS** [comment]
It kinda is 😂. But I don't want to disappoint users by not implementing what was said. Better keep it secret ☺️.

**Comment by ShankarBUS** [comment]
Finally! I had the time to implement this feature 😁. Here you go 6b7c374f8d462803a609ab5f65323a6f13a7f9b6

One thing to notice is that, setting the flyout timeout lesser than **`2750 ms`** will result in overlap between this and the old flyout.

It will only happen once in a while with **Audio, Brightness & LockKeys** flyouts. But **Airplane Mode** flyout will exhibit this bug too often.

**Comment by Cyberdroid1** [comment]
Where is this option present in the settings? I cannot find it. 😅😅

**Comment by ShankarBUS** [comment]
# 🤦‍♂️

Soooo.... sorry, I forgot to stage the `AboutPage.xaml` file before committing. It was not uploaded to GitHub. I was busy cleaning up the commit history after that. So the changes must be been undone during the cleanup.

I will include it in v0.8.

**Comment by ShankarBUS** [comment]
Done in 2dd91390bc2d06382ae4fad3c12adb967a6d2b56 guys!
Now, there is a number box under the **Behavior** group in the new **Personalization** page. It has a minium limit of 100 ms (come on guys! you wouldn't want to set anything below 100 ms. If you do, you literally are a psycho).

![image](https://user-images.githubusercontent.com/63704247/97788130-88fd7880-1bdc-11eb-90ca-860dc517e849.png)

As I already said `1500 ms` could be considered as the best minimum value for the timeout.

**Comment by Cyberdroid1** [comment]
But you said there can be interference problem with values under 2750 ms.

**Comment by ShankarBUS** [comment]
@Cyberdroid1,

>×But you said there can be interference problem with values under 2750 ms.

Only for Airplane mode flyout.

**Comment by Samuel12321** [comment]
why specifically airplane mode?

We probably should put a warning below the settings box about this.

**Comment by ShankarBUS** [comment]
@Samuel12321,

> why specifically airplane mode?

Audio and brightness flyout shown only when the built-in flyout is triggered.

But airplane mode shows on its own. It actually triggers faster than the built-in one. Thus resulting in this issue.

**Comment by Cyberdroid1** [comment]
Any possible fix for this?

**Comment by ShankarBUS** [comment]
@Cyberdroid1, unfortunately I couldn't find one yet.
