### ISSUE TITLE
Change images in ReadMe

### ISSUE THREAD

**Issue by Cyberdroid1** [ShankarBUS/ModernFlyouts#55]
Hi, I have a request to merge many of the images in the ReadMe.md file to stay less cluttered. 
For example, images of Aeroplane mode with/without TopBar can be merged. 

It could result to be more clean. 

And also, the images in MS Store are not updated to the current one and still have the old pictures. Do update them.

**Comment by ShankarBUS** [comment]
> For example, images of Aeroplane mode with/without TopBar can be merged.

Shall I ask why?

> And also, the images in MS Store are not updated to the current one and still have the old pictures. Do update them.

@Samuel12321 FYI

**Comment by Samuel12321** [comment]
will update them this afternoon

**Comment by Cyberdroid1** [comment]
>Shall I ask why?

It would lead to a more cleaner look, otherwise we have to keep scrolling to find more images.

**Comment by Cyberdroid1** [comment]
Ok, if not for GitHub, can we atleast do this for MS Store?

**Comment by Cyberdroid1** [comment]
Because, images in MS Store are sometimes not in order. It looks all out of place if similar category images arent kept together.

**Comment by Samuel12321** [comment]
Updated the Store page text, and replaced a few images have created #58 for further work on store page (specifically images)

**Comment by Cyberdroid1** [comment]
Thought something.

![Audio](https://user-images.githubusercontent.com/51435948/94363121-ade26580-00dd-11eb-84e6-1b7d45a1495d.png)

![Audio_NoTop](https://user-images.githubusercontent.com/51435948/94363123-b044bf80-00dd-11eb-963d-381efc51e28a.png)

What do you say?

**Comment by ShankarBUS** [comment]
Cool idea! Would save a lot of space, looks professional & reduces data usage 😂

**Comment by Cyberdroid1** [comment]
Yes!
