### ISSUE TITLE
Media control widget suggestions

### ISSUE THREAD

**Issue by Dubzer** [ShankarBUS/ModernFlyouts#6]
HI. I just built new version from sources and it looks great! But you made a single media control widget with switches. Should we expect an option to switch between old and new variation in future versions? IMO the old one was quite handy when you have a lot of screen space 

![image](https://user-images.githubusercontent.com/18244287/88845938-8d855000-d1ed-11ea-8ef9-33b27b2f250c.png)

![image](https://user-images.githubusercontent.com/18244287/88845979-9d9d2f80-d1ed-11ea-96c2-cf7f52ca685c.png)

Also, it might be reasonable to hide a three dots button when additional player options are not available.

![image](https://user-images.githubusercontent.com/18244287/88846270-12706980-d1ee-11ea-922c-4c3b24390da4.png)

**Comment by ShankarBUS** [comment]
Well I wanted it to be similar to Windows 10X's UI. So instead of creating a separate UI, I recreated the Windows 10X Media control UI.

And I won't change my decision about this. (Would be consistent with win 10 once it's UI is updated)

Scrolling vertically would take up a lot of the available screeb space and my be irritating to users with small displays.

And for the **"three dots button"** it could be hidden (later) if no options are available.

**Comment by Dubzer** [comment]
We may have had a misunderstanding, so I made this concept:

![concept](https://user-images.githubusercontent.com/18244287/88853832-ff16cb80-d1f8-11ea-8d07-f65815551773.jpg)

So I'm not suggesting returning the old style.  

> Scrolling vertically would take up a lot of the available screen space and my be irritating to users with small displays.
I don't mean scrolling, but statically positioned. And because of small displays I suggest to make it **optional**. Something like "Always show all media sources", and it would switch between current behavior and suggested. 

Anyway, thank you for your job!

**Comment by ShankarBUS** [comment]
Hey @Dubzer, so you want to keep the new UI but need an option to show multiple session controls vertically and not one at a time in horizontal.

That could be done, it would be a nice little feature. It's also easy to be done.

**Comment by Dubzer** [comment]
It would be great if it was calculated according to screen height. But as it will require an additional work, I think 2, or maybe 3 is enough

**Comment by ShankarBUS** [comment]
Hey @Sameul12321, since this feature will require changes in settings (i.e. reorg). Can you move this issue from v0.7 project to v0.8?

**Comment by ShankarBUS** [comment]
Hey @Dubzer, the ability to auto hide  the **"More Controls"** button has been added in 8754e253e59ad9193493f9a71032cf4ace90f255

The 1st half of this request is postponed to v0.8 😅. But please be patient until your request is implemented.

**Comment by Samuel12321** [comment]
> Hey @Sameul12321, since this feature will require changes in settings (i.e. reorg). Can you move this issue from v0.7 project to v0.8?

sure

**Comment by ShankarBUS** [comment]
@Dubzer,

Sorry for taking too long (~3 months) to implement this 😅.
And thank you so much for proposing this idea ✌.

Your proposal has been implemented in 7e587f1fc7601021949f0bb943bc62722275b398

![image](https://user-images.githubusercontent.com/63704247/96373539-b7199c00-118a-11eb-9437-bd7c4406fbfd.png)

Currently the settings window is messed up, so all options are placed on a single page. I'm working on reorganizing it.
There won't be a 2px gap between those controls like it used to in v0.2.0

I hope I did what you wanted.

If you're still willing to use this app, wait till v0.8 is released. Feel free to propose new ideas 👍 😁

**Comment by Samuel12321** [comment]
definitely think the gap is needed.

**Comment by ShankarBUS** [comment]
Would you guys shut up now?

![image](https://user-images.githubusercontent.com/63704247/96399811-e06b1400-11ec-11eb-93af-b5f2e0cb3faf.png)

Could you see the 8px spacing?

**Comment by Samuel12321** [comment]
> Would you guys shut up now?

Sorry?

**Comment by ShankarBUS** [comment]
I was joking 😂. Do you guys like it?

**Comment by Samuel12321** [comment]
Sorry, i misinterpreted your statement.

Yes, it will be a good feature to have.

**Comment by Cyberdroid1** [comment]
Can we also reduce it to 1? And what's the behaviour, say I set it to 2, but I have 3 media sources. What will be the behaviour for that?

**Comment by ShankarBUS** [comment]
It will show scroll buttons if the controls are more than the max controls.

Why are you even confused about this 🤣?

I added the ability to switch between vertical and horizontal stacking. Only the vertical layout will have spacing and the ability to show multiple session controls.

**Comment by Cyberdroid1** [comment]
> Any suggestion for the sentence to show there?

I didn't get you. What sentence?

**Comment by ShankarBUS** [comment]
What should be the header for the new vertical media controls count option?

Currently it is `Maximum Number of Media Session Controls vertically`. It seems to be confusing. We need a replacement for that.

Any suggestions?

**Comment by Cyberdroid1** [comment]
I think 
`Maximum media session controls`

I say we hide this setting or grey it out when horizontal mode is selected.

**Comment by ShankarBUS** [comment]
No we shouldn't (we can but we shouldn't). They are independent of each other and should be independently controllable.

I added `vertically` to reduce confusion.

What about `Maximum Number of Media Session Controls to show vertically` then?

If you still insist on disabling it while choosing `Horizontal`, we can do that.

**Comment by Cyberdroid1** [comment]
Lets clear one point. Is this feature for multiple flyouts available in horizontal mode?

**Comment by ShankarBUS** [comment]
> Is this feature for multiple flyouts available in horizontal mode?

No, that's I've been saying all along

**Comment by Samuel12321** [comment]
I agree with @Cyberdroid1, the current terminology can be confusing.  i personally think the option to select the maximum number of vertical media controls should be disabled or hidden when set to horizontal. Otherwise it seems like this feature also occurs horizontally.

**Comment by ShankarBUS** [comment]
Ok that's cool, we already need to update some sentences to make them clean and professional.

We can do this together with that.

Hey @Samuel12321, we are getting translation PRs at unwanted times, what should we do?

Let's say i introduce  a temporary string like the previously mentioned one, people are updating the translations even for the temporary strings.

It is hard to maintain consistency across the resx files. The commit history will be unnecessarily filled. I am still confused about the past PRs, would they even work? Why merge them if they don't work?

How should they help us with multilingual support?

How and when should we accept translation PRs?

What about the xlf files & Multilingual App Toolkit?

**Comment by Samuel12321** [comment]
Found out how to make them work.
Regarding translation PR's i will review them and merge them when it suits.
