### ISSUE TITLE
Bug: Can't open app after updating my Insider Dev version

### ISSUE THREAD

**Issue by usta-tr** [ShankarBUS/ModernFlyouts#611]
**Describe the bug:**
I can't open the app. It comes up with an error message

**To Reproduce:**
1- Update the Windows
2- Open ModernFlyouts
3- See error

**Screenshots:**
![image](https://user-images.githubusercontent.com/56765276/117501816-45b70480-af87-11eb-960c-1944d3a6006d.png)

**OS Version:**
 - Windows 10 Home Single Language Insider Dev Build 21376.co_release

**ModernFlyouts Version:**
 - Version: 0.9.3.0

**Additional context:**

**Comment by ErenAKGUN2007** [comment]
Ben de VM içinde Insider Dev sürümünü kullanıyorum ama herhangi bir problem ile karşılaşmadım.
![Windows 10 Insider Preview-2021-05-07-23-15-09](https://user-images.githubusercontent.com/75967441/117503859-40a78480-af8a-11eb-9ab6-84ae40734d8b.png)

**Comment by ErenAKGUN2007** [comment]
Translation of error: The service cannot accept control messages at this time

**Comment by Samuel12321** [comment]
does this occur after rebooting the computer, sounds like a duplicate process issue.

**Comment by Cyberdroid1** [comment]
How about an app reinstall? Sometimes that fixes the issue.
