### ISSUE TITLE
Reorganize settings so that each module get their own page

### ISSUE THREAD

**Issue by Samuel12321** [ShankarBUS/ModernFlyouts#62]
> We need to reorganize settings so that each module get their own page (if they need multiple options e.g. Audio) or a fused page (e.g. Brightness and airplane)

**Comment by Samuel12321** [comment]
#43

**Comment by ShankarBUS** [comment]
Thanks @Samuel12321!

**Comment by Cyberdroid1** [comment]
Do also add a design and layout page too! For transparency, etc.

**Comment by ShankarBUS** [comment]
Shouldn't they be in the **UI** page?

I seriously don't have any idea what to do 😅.

Could you both help me with this?

**Comment by Cyberdroid1** [comment]
What pages do you have in mind?
I think we should have General, Design and Layout, Modules

**Comment by ShankarBUS** [comment]
Sounds good!

**Comment by Samuel12321** [comment]
👍

**Comment by ShankarBUS** [comment]
@Cyberdroid1,

How about this?

- General
- UI (or User Interface or Personalization)
- Modules
    - Audio
    - Brightness
    - Airplane mode
    - Lock keys

**Design and Layout** doesn't sound that great 😅. Design would be good, no problems with that. But for now, we don't have anything to consider as a setting for changing the **layout**.

Could we start a discussion?

**Comment by Cyberdroid1** [comment]
Let's call it Design and Interface. No need to create separate page for each module for now.

**Comment by ShankarBUS** [comment]
> No need to create separate page for each module for now.

We have to, each module may get new features in the future.

It's better to have separate pages.

We won't have much time to split the pages in the future.

The pages may be empty for now.

But it's better make them now.

No one mind if there are 10 options or 2 options on a settings page.

PowerToys have separate pages for each toys even though some of them have very few options.

If we have empty pages, we will have the motive to fill them later.

But if they are cluttered on a single page, we would feel lazy to reorg them again.

@Samuel12321, would you like to say anything?

**Comment by Cyberdroid1** [comment]
Hmm, you have a good point. I support ya!

**Comment by Samuel12321** [comment]
i agree

**Comment by ShankarBUS** [comment]
How about this bros?

![image](https://user-images.githubusercontent.com/63704247/97068569-4ccb8600-15e6-11eb-81ff-3bd54b1b4d55.png)

**Comment by ShankarBUS** [comment]
@Cyberdroid1, @Samuel12321,

Could you guys answer quickly? I'm waiting for your feedback

**Comment by Samuel12321** [comment]
Looks amazing

**Comment by Samuel12321** [comment]
is it a mock-up, or programmed?

**Comment by Cyberdroid1** [comment]
What is there in personalization?

**Comment by Stealnoob** [comment]
Seems great

**Comment by ShankarBUS** [comment]
Sorry for the delay guys

> is it a mock-up, or programmed?

It is not a mockup. I added empty pages to the real app to experiment with them before the actual implementation.

> What is there in personalization?

Nothing for now, all the pages are empty (except General and About pages).

Every thing related to UI or UX or layout will go into it.

**Comment by Cyberdroid1** [comment]
Can we rename the page `Audio` to `Audio and Media` ?

Because it would contain settings for media flyout also, right?

**Comment by ShankarBUS** [comment]
@Cyberdroid1, I'm still prototyping the settings window.

That's a nice suggestion 😄

**Comment by Cyberdroid1** [comment]
Wait wait, let's name it `Media and Volume`

**Comment by Cyberdroid1** [comment]
Because Media will contain videos and audios. Volume is a separate thing from both.

**Comment by ShankarBUS** [comment]
Hey guys my system shows `Flight mode` instead of `Airplane mode` everywhere when I switch from `English (United States)` to `English (India)`.

Is the term different for each language?

**Comment by Samuel12321** [comment]
i think the two are used interchangeably "Airplane mode" is probably American, every where else uses "flight mode"

**Comment by Cyberdroid1** [comment]
Well, it's machine language.

**Comment by Cyberdroid1** [comment]
It can also be like, that
The machine translation first converts the input the words to some language, and then use the words in that language to other languages.

Maybe...

**Comment by ShankarBUS** [comment]
@Cyberdroid1,

> It can also be like, that
> The machine translation first converts the input the words to some standard language, and then use the words in that language to other languages.
> 
> Maybe...

I was referring to the **legacy flyout** and **Windows system** (**Tray Network flyout, Windows Settings** & etc.). Only Windows inbuilt things show **"Flight mode"** not ModernFlyouts. ModernFlyouts still shows **"Airplane mode"**.

Our behaviour is different from Windows. What should we do?

> Wait wait, let's name it   `Media and Volume`

The term `**Audio** flyout` is used commonly all over the repo & even in the app's code. It became more like a brand for that module. Changing it now would be confusing. Let's re-consider this in the future.

However, we can introduce sub modules (new sub items in the navigation view) with the names `Volume` & `Media`. Any objections?

**Comment by ShankarBUS** [comment]
@Cyberdroid1,

![image](https://user-images.githubusercontent.com/63704247/97776473-5462d000-1b8e-11eb-8401-56f57e40a70e.png)

Like this maybe?

**Comment by Cyberdroid1** [comment]
Why complicate this simple stuff by creating extra options?

**Comment by Cyberdroid1** [comment]
Let's keep it just Audio then.

**Comment by ShankarBUS** [comment]
I'm not creating separate pages for the sub modules! 🤦‍♂️

I'm just providing a way to navigate to the tabs within the page

![image](https://user-images.githubusercontent.com/63704247/97777616-7e6cc000-1b97-11eb-9c26-099e0bff4b1c.png)
![image](https://user-images.githubusercontent.com/63704247/97777631-93495380-1b97-11eb-9221-7f048a2a999f.png)

> I don't think there would be so many settings in media and volume flyout that we need to separate the both.

That's what I thought in the past. Look now where we are! We can't believe there won't be any new features in the future.
They may grow in size in the future if #148, #114, #103 and #78 are implemented. That's why I split them into multiple tabs.

> Why complicate this simple stuff by creating extra options?

But they are all in a single page. So, there are won't be any complications, I guess?

**Comment by Cyberdroid1** [comment]
> ![image](https://user-images.githubusercontent.com/63704247/97777616-7e6cc000-1b97-11eb-9c26-099e0bff4b1c.png)

I did not see this one. This looks amazing!

**Comment by Cyberdroid1** [comment]
> I'm not creating separate pages for the sub modules! 🤦‍♂️
> 
> I'm just providing a way to navigate to the tabs within the page

Don't add that option, please.

**Comment by ShankarBUS** [comment]
> Don't add that option, please.

I'm not adding it TBH. It's just a mock-up and I just asked for an opinion. It's not easy BTW.

**Comment by ShankarBUS** [comment]
Implemented in 2dd91390bc2d06382ae4fad3c12adb967a6d2b56.

I hope I didn't disappoint any of you 😅.
