### ISSUE TITLE
Add a lock image for "CapsLock on / off"

### ISSUE THREAD

**Issue by Sav22999** [ShankarBUS/ModernFlyouts#63]
Add a lock icon aside to the message for "CapsLock on / off", like "Airplane mode"

**Comment by ShankarBUS** [comment]
Thanks for the suggestion pal!

I had this thought before but there were no icons for CapsLock or the related keys in the Segoe MDL2 Assets.

I tried to make them on my own (tried SVG image and a bitmap image) but couldn't make a icon similar to their style.

So I dropped the idea. I now have the motive to reimplement it again

**Comment by Samuel12321** [comment]
Request from store "Add some icons for lock-keys module so it's more distinct between caps-lock ON vs OFF"

**Comment by ShankarBUS** [comment]
That's what I mentioned in my previous comment

I had them initially (separate icons for caps/scroll/num lock - on/off) but they weren't suiting the design correctly and looked blurry so I removed them before open sourcing this project.

**Comment by Sav22999** [comment]
@ShankarBUS What do you think about Photon Icons? (Firefox)
https://design.firefox.com/icons/viewer/#, the "Secure" icon

**Comment by Samuel12321** [comment]
The secure icon looks fine for 'locked' but i don't think there is a suitable icon for unlocked

**Comment by ShankarBUS** [comment]
Umm... Guys the lock/unlock icons are already present in Segoe MDL2 Assets

![image](https://user-images.githubusercontent.com/63704247/94535706-80252a00-025f-11eb-897b-72ba2636ee86.png)

![image](https://user-images.githubusercontent.com/63704247/94535645-700d4a80-025f-11eb-89a3-b4f1995d0a5f.png)

That was not the problem, there was no indication of caps/scroll/num lock. That's why I made my own and dropped the idea

**Comment by Sav22999** [comment]
@ShankarBUS So, sorry, I didn't understand what's the problem :thinking:

**Comment by ShankarBUS** [comment]
We have the lock/unlock icon but it doesn't indicate if it's caps lock or num lock or scroll lock. (There will be text but the icon won't indicate it) 

We can just show either lock or unlock.

If you just want the lock/unlock icon, it's very easy & doable

**Comment by Sav22999** [comment]
@ShankarBUS Ok, basically the problem is: there are just Lock/Unlock icons, which should indicate both Caps and Lock and ScrollLock, right?

**Comment by ShankarBUS** [comment]
Yes!

**Comment by Sav22999** [comment]
Ok. So, a possible solution could be to add a number (for example [1]) inside the lock/unlock icon. So, it should indicate the Block Number. A letter [a] to indicate Caps. And without anything could indicate BlockScroll (or if you have in mind another icon in mind...)

**Comment by ShankarBUS** [comment]
That's what I previously did. But I can't create a neat icon. They looked blurry when scaled. WPF doesn't support SVGs. There were too many issues with this.

I guess just showing the lock icon will be enough for now

**Comment by Sav22999** [comment]
@ShankarBUS Ok, so I think a solution for now could be use just the lock/unlock icon... eventually in future you could use another one.

**Comment by ShankarBUS** [comment]
Yes that's what we should do 😁

**Comment by ShankarBUS** [comment]
Implemented in 79ab48ece0f265e11f2e113d31d7d98055c97fcc.

Thanks for being patient. This feature will be readily available in the v0.7 release
