### ISSUE TITLE
Ability to completely hide the top bar

### ISSUE THREAD

**Issue by Samuel12321** [ShankarBUS/ModernFlyouts#65]
Store app reviewer has asked for "Ability to completely hide the top bar", presumably asking for a way to hide the small bar at the top of flyout that opens top bar.

**Comment by ShankarBUS** [comment]
I knew someone would ask this. I already planned this for v0.8

Not a big deal, was just waiting for the re-org in settings

**Comment by ShankarBUS** [comment]
@Samuel12321,

Done 2dd91390bc2d06382ae4fad3c12adb967a6d2b56.

Could you publish v0.8.0.0-beta to beta flight users on Store ASAP?

Once no bugs are reported, just remove the `-beta` suffix from the version in the *.csproj and publish the v0.8.0.0 to stable users.

**Comment by Samuel12321** [comment]
HI @ShankarBUS,
Great work with the 0.8.0.0-Beta, looks great and feels a lot more polished. 
Have found 1 bug, so we will probably need to do a 0.8.0.1 release, and include the updated translations. 
![Screenshot 2020-11-01 092021](https://user-images.githubusercontent.com/35312698/97789432-562ba280-1c25-11eb-8b4e-d3ef0382d4d1.png)
Other than that, it is working well and looks great.
This is now flighting to the beta ring.

**Comment by Samuel12321** [comment]
@ShankarBUS, in future can you constantly push any change you make. (If necessary to a testing branch), so everyone can get an idea of the sort of changes incoming, just to reduce the amount of wasted and duplicate work. I have just had to ask the 4 pull requests to redo all their translation work, as none of it applies to 0.8.0. 

Just to clarify this is in no way a criticism, just a suggestion of how we can improve ModernFlyouts.
Thanks again for all your great work on the project, 0.8.0 is looking great.

**Comment by ShankarBUS** [comment]
@Samuel12321,

> in future can you constantly push any change you make. (If necessary to a testing branch), so everyone can get an idea of the sort of changes incoming, just to reduce the amount of wasted and duplicate work. I have just had to ask the 4 pull requests to redo all their translation work, as none of it applies to 0.8.0.

Yup! I understand how hard it is to tell contributors to redo their work.

It'll completely demotivate them 😔.

I'm sorry. I had to do all of them in a single commit because they are all tied up. I could commit them separately. I was confused 😅.

I promise I won't do this again in the future.

**Comment by ShankarBUS** [comment]
@Samuel12321,

> Have found 1 bug

Ok I'll do
