### ISSUE TITLE
Microsoft app certification kit recommendations

### ISSUE THREAD

**Issue by Samuel12321** [ShankarBUS/ModernFlyouts#68]
have been meaning to look into these for a while:
[Windows App Certification Kit - Test Results.pdf](https://github.com/ShankarBUS/ModernFlyouts/files/5296571/Windows.App.Certification.Kit.-.Test.Results.pdf)

**Comment by ShankarBUS** [comment]
I guess we won't pass the **"Package sanity test"** anytime because most of those (except one) arise from our dependencies.

But the **"Debug configuration test"** could be passed. **"BUSK.Markdown"** was one of my side projects dropped it on behalf of the **"https://github.com/ModernWpf-Community/ModernWpfCommunityToolkit"**

I guess I would need to work on them again. We can even create the reveal & acrylic effects there and use them in our app

**Comment by ShankarBUS** [comment]
Hey Sam, I can't see those reviews from my MS Store using my MS account. It doesn't show anything for me.

Are there any ways for me to see them? Will be somewhat motivating 😅😁

**Comment by Samuel12321** [comment]
I was rather confused as when i went onto the store i couldn't see them either until i found out that MS Store only shows reviews from users in the same region. I can only see them all through MS Dev portal.

Will upload a screenshot for you.

**Comment by Samuel12321** [comment]
[Reviews.pdf](https://github.com/ShankarBUS/ModernFlyouts/files/5296782/Reviews.pdf)

Pdf containing a printout of reviews page.
Seems like the review page is one of the only ones i cant export.

**Comment by Samuel12321** [comment]
we are at 625 active users from store

**Comment by ShankarBUS** [comment]
> we are at 625 active users from store

That's great! 🎉

**Comment by Samuel12321** [comment]
over 1300 installs total
By country:
1. Russia 700
2. United States 300
3. India
4. Spain
5. Brazil
6. UK
7. New Zealand
8. Canada

**Comment by ShankarBUS** [comment]
The reviews are great!

![](https://th.bing.com/th/id/OIP.PGje9zd1FhRcbLKWq3lbDQHaFJ?pid=Api&rs=1)

**Comment by ShankarBUS** [comment]
Has this been fixed @Samuel12321?

**Comment by Samuel12321** [comment]
i think so, from this the dpi awareness issue #69 was created. The issue with debug config was resolved with the removal of wpf community toolkit.
As i understand it the others cant really be resolved (and aren't really a problem except for windows 10S)
