### ISSUE TITLE
Reduce slider size for transparency

### ISSUE THREAD

**Issue by Cyberdroid1** [ShankarBUS/ModernFlyouts#70]
The current slider bar for transparency spans to the whole window width. It takes too much sliding then to reduce the transparency. 

Also, can we add steps to bar, like at every 5 or 10%, it would stick?

**Comment by ShankarBUS** [comment]
I will take a look at how other apps like Windows Settings handle scenes like this and we can replicate that. Since we are not experts on accessibility and usability, we may need to steal some ideas from professionals

**Comment by ShankarBUS** [comment]
Done in 79ab48ece0f265e11f2e113d31d7d98055c97fcc pal!

Thanks for filing this issue 😁.

**Comment by Samuel12321** [comment]
just moved this up to 0.7.0 as its already done 😁
