### ISSUE TITLE
Feature: Ability to Disable tray icon

### ISSUE THREAD

**Issue by duytonynguyen** [ShankarBUS/ModernFlyouts#72]
It would be great if there's an option to disable tray icon, since most people who use this app would want a more sleek and minimalistic theme, thus unlikely to access the settings frequently beyond the initial tinkering, or exit the app. On the other hand, launching the app can get us straight into the settings instead of doing nothing as of current version (0.6.0).

**Comment by ShankarBUS** [comment]
Great suggestion! We can hide the tray icon easily with a little amount of work.

 But there are some future plans to add a ability to summon the flyout (audio/brightness) near the sys tray (Thus could be considered as a replacement for the tray volume flyout).

By default the tray icon will be enabled. But the users will be able to change it later by themselves.

> On the other hand, launching the app can get us straight into the settings instead of doing nothing as of current version (0.6.0).

Oh my god! Again? It works fine only during development. After deployment it breaks!!!!???

I have to investigate on this. Thanks for notifying me of this.

**Comment by ShankarBUS** [comment]
A silly question 😁, Did you create a GitHub account just for opening this issue?

**Comment by duytonynguyen** [comment]
> A silly question 😁, Did you create a GitHub account just for opening this issue?

Yes, yes indeed. As a power user and a developer myself (albeit with not much experience), I rarely find any GitHub app that can use a suggestion. They are either too powerful with too many functions, or too simple that I don't know where to start suggesting, or if the devs can even implement what I have in mind. So I haven't had the urge to create an account until now, cause I'm aware that it's just a small adjustment, yet can greatly improve the experience.

**Comment by ShankarBUS** [comment]
Thanks pal!

**Comment by duytonynguyen** [comment]
> Thanks pal!

No, thank you. Keep up the good work!

**Comment by ShankarBUS** [comment]
@duytonynguyen,

Thank you for submitting this feature request!

Your request has been implemented in 2dd91390bc2d06382ae4fad3c12adb967a6d2b56,
These changes will be available in the v0.8.0 release. Please be patient until you receive the update via MS Store or this repo.

>On the other hand, launching the app can get us straight into the settings instead of doing nothing as of current version (0.6.0).

This bug has also been fixed in v0.7.8?

Please try to provide us more suggestions, feedbacks, bug reports or ideas about the app in the future. 😁
