### ISSUE TITLE
Volume increase or decrease in steps of one instead of 2

### ISSUE THREAD

**Issue by Samuel12321** [ShankarBUS/ModernFlyouts#80]
Store requested feature.
Pretty sure we can't fix this if i recall correctly, due to windows only having 50 different volume levels.

Just thought i would make the bug request encase any one has any brilliant ideas.

On a separate note perhaps we can have a setting to adjust by how much it changes when the volume up / down button is pressed.

**Comment by ShankarBUS** [comment]
The **change delta** (i.e. increase or decrease amount) is directly controlled by **Windows**. We shouldn't interrupt the process. This is out of our scope.

**Comment by Samuel12321** [comment]
thought so, just thought i would check

**Comment by ShankarBUS** [comment]
We can do some ugly hacks for this to happen i.e. manually store the volume and when the keys are pressed, change the volume and set it. But this would result in a double change in volume and will stutter. Even if there was a easy way to do it, our app is not designed for this. This is just out-of-scope

**Comment by MuhammetEminCakir** [comment]
I'm sorry for reopen this issue.
Another open source project [Volumey](https://github.com/G-Stas/Volumey) has this function.

You can change Volume adjustment step manually.
![Ekran görüntüsü 2022-02-02 052345](https://user-images.githubusercontent.com/64583157/152083646-2fda2cc6-374b-415b-b241-a6353a26d88e.png)
