### ISSUE TITLE
Add winget support

### ISSUE THREAD

**Issue by Samuel12321** [ShankarBUS/ModernFlyouts#81]
Add support for distribution via winget

**Comment by ShankarBUS** [comment]
Great idea!

Someone suggested this on Reddit too during v0.2 release

**Comment by ShankarBUS** [comment]
Hey @Samuel12321, Could you take care of this task?

I'll focus on coding and bug fixes in the mean time 😅😁

**Comment by Samuel12321** [comment]
sure, already started

**Comment by ShankarBUS** [comment]
Thanks pal you've been so helpful along the way. If you weren't here to help I would've dropped this project 👍❤️

**Comment by Samuel12321** [comment]
I have submitted the required files to the winget repo. just waiting for them to review.
https://github.com/microsoft/winget-pkgs/pull/3946

**Comment by ShankarBUS** [comment]
That's awesome 👍

What about the certificate issue?

**Comment by Samuel12321** [comment]
still working on that issue

**Comment by Samuel12321** [comment]
done

**Comment by ShankarBUS** [comment]
What about the two yaml files in two different directories?

**Comment by Samuel12321** [comment]
what?

**Comment by ShankarBUS** [comment]
See this https://github.com/ShankarBUS/ModernFlyouts/commit/49b249a798c6f4aca4443e46a816aa5f593b89c8#commitcomment-42990220
