### ISSUE TITLE
Proposal: Name change suggestion for headers of options in settings

### ISSUE THREAD

**Issue by Cyberdroid1** [ShankarBUS/ModernFlyouts#83]
Could you replace the **"Global System Media Transport Controls"** of the following section to **"Media Controls"** and **"Media Flyout"** respectively?

It is so lengthy and will be confusing for non-power users.

![image](https://user-images.githubusercontent.com/51435948/95012514-d1199180-0656-11eb-9777-bc9a9744aaf6.png)

**Comment by ShankarBUS** [comment]
1. 1st one could be easily done

2. I don't understand the 2nd request properly

**Comment by Cyberdroid1** [comment]
The second one is that-

You stretch the window to have a very huge width. The bar stretches to match the window width. It is tough to change the transparency then.

**Comment by ShankarBUS** [comment]
Oh we've talked about this already in another issue, right?

I will look into it.

**Comment by Cyberdroid1** [comment]
Ah okay. It would be better to close that issue.

**Comment by ShankarBUS** [comment]
No need to close it. Keeping this open would be helpful for tracking the work regarding the proposal.

**Comment by ShankarBUS** [comment]
#70 right?

Let's keep that the way it is. (based on priority)

We should modify this issue to only have the name change suggestion

**Comment by Poopooracoocoo** [comment]
But I like that users can easily Google the term and find heaps of other information. I wish I knew what it was called ages ago. It should be mentioned somewhere.

**Comment by ShankarBUS** [comment]
What about mentioning GSMTC within a parenthesis adjacent to the word **"Media"**?

**Comment by Cyberdroid1** [comment]
Or put the Media term in parenthesis?

**Comment by Poopooracoocoo** [comment]
Or mention GSMTC in the info page?

**Comment by ShankarBUS** [comment]
Sorry for the delay guys, it has fixed in 79ab48ece0f265e11f2e113d31d7d98055c97fcc. Forgot to notify you 😅.

It may not be what you had in mind but it could be easily replace as it has been decoupled from code.

I will keep this issue open till you're satisfied.

**Comment by Samuel12321** [comment]
@Cyberdroid1 and @Poopooracoocoo, this has changed again in the 0.8.0 release.
How does it look now?

**Comment by Stealnoob** [comment]
Not mentioned but have seen in the strings, and even if it starts to make a long label, I think it looks good.
(is GSMTC in parenthesis taken from what I did in one of my previous translations? just to be curious 🙃)

**Comment by ShankarBUS** [comment]
@Stealnoob, Thanks!

> (is GSMTC in parenthesis taken from what I did in one of my previous translations? even if it was also mentioned earlier... just to be curious )

Yes! 😁😅
