### ISSUE TITLE
Bug:Doesn't let me reuse the original windows "flyouts"

### ISSUE THREAD

**Issue by Lollo0754** [ShankarBUS/ModernFlyouts#847]
**Describe the bug:**

I tried to delete the app but then the original Windows ones don't work.

**To Reproduce:**

1. Click the windows flyouts option on the app
2. Click exit safely
3. Uninstall the app
4. Restart the PC
5. The normal windows flyouts don't work.
6. Reinstall the app and then it works only if the app is opened.

**Screenshots:**

**OS Version:**
 - Windows Version:  Windows 10 21H2 

**ModernFlyouts Version:**
 - Version:  v0.9.3.0 

**Additional context:**

**Comment by Samuel12321** [comment]
try restarting your computer
does the issue persist?
