### ISSUE TITLE
ModernFlyouts opens when click MB4 or MB5 when playing LoL

### ISSUE THREAD

**Issue by NeoShinra** [ShankarBUS/ModernFlyouts#88]
Hi! I just found that issue when playing LoL and is a little bit annoying. Every time I click MB4 or MB5, the volume slider opens like clicking the volume keys. In other games like Halo: MCC or other apps didn't happen. Hope you can solve it because I really love your app. Thanks for make Windows a better place ❤

**Comment by ShankarBUS** [comment]
Weird 🤔. I'll try to fix this

**Comment by yume-chan** [comment]
Continuing from #98, after I casting the `lParam` to `long` it "works" now.

From my observation, mouse side buttons (and maybe some other keyboard keys, inferring from the [doc](https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-appcommand)) also generates a shell message.

And it slipped through the check here:

https://github.com/ShankarBUS/ModernFlyouts/blob/1063dd4f27318ec0b913a5340ee86b19182b1e71/ModernFlyouts/Flyout%20Helpers/AudioFlyoutHelper.cs#L147-L149

where `isMediaKey` is `false` and `device` is not `null`. I don't understand why you inverted the `isMediaKey` here.

**Comment by ShankarBUS** [comment]
Thanks @yume-chan,

I didn't have time to debug and proper devices to test this. I am genuinely happy that you did the work for me 😄.

 > I don't understand why you inverted the isMediaKey here.

It's to check what the pressed key was (if it is not a media key i.e. it is a volume key, then check if the default audio device is present)

**Comment by ShankarBUS** [comment]
Would you like to contribute? 😁😅
