### ISSUE TITLE
Media Flyout no longer displaying media

### ISSUE THREAD

**Issue by JDar2K** [ShankarBUS/ModernFlyouts#89]
I'm currently using MusicBee, but I checked with Spotify as well and no dice.

**Comment by ShankarBUS** [comment]
Are you currently using Windows 10 2004/2009?

**Comment by JDar2K** [comment]
Yes

**Comment by ShankarBUS** [comment]
Then see #29.

The app has to restarted to show them

We are trying to find a way to tackle this bug

**Comment by ShankarBUS** [comment]
Duplicate of #29
