### ISSUE TITLE
Explanation / clarification for run at startup behaviour option

### ISSUE THREAD

**Issue by Samuel12321** [ShankarBUS/ModernFlyouts#9]
Inform user that the run at startup setting only triggers opening of settings app - does not affect weather Modern Flyouts will be applied after computer is restarted.

i think it is currently a bit ambiguous, and some users may turn it on, believing it necessary for the app to work after reboot

**Comment by ShankarBUS** [comment]
No, it will run the app at startup.

**Comment by ShankarBUS** [comment]
Why should there be an option to open settings window after the app is started. That will be annoying for the users.

**Comment by ShankarBUS** [comment]
I think, in your machine the app is started twice after Windows startup (the first one making the ModernFlyouts run and the second one triggering settings window). The app itself handles the startup logic via Registry startup. There could be another method (startup shortcut, startup task) [possibly made by you] which causes this second startup.

I would recommend you to check Task Manager's startup tab and report whether you see two entries of ModernFlyouts (with the run at startup enabled in the settings).

Turning of the Run at startup option will prevent your issue for now.

**Comment by Samuel12321** [comment]
Sorry, I was really puzzled by a setting which appeared to cause the settings window to open at boot.  It seemed like a really weird feature.
You were correct, a close look at start-up tab reveals that for some reason two entries were created, one in HKCU:Run (which is the one that the settings menu enables and disables) and another which appears in startup common. Not sure why, i never told it to. uninstalling then reinstalling doesn't remove the 'Startup common' entry. I suspect it may have been left over from a previous version as i had V0.2 installed prior to V0.3.
Disabling the "startup common" entry resolves the problems.

Sorry for the stupid bug and pull request
Thanks

**Comment by ShankarBUS** [comment]
> Sorry for the stupid bug and pull request
It's okay pal, you tried to help. I'm always welcome to contributors.
