### ISSUE TITLE
Flyout incorrectly displayed when hotkey combo is pressed

### ISSUE THREAD

**Issue by Cospui** [ShankarBUS/ModernFlyouts#90]
When using git / WSL, sometimes I type "Ctrl + Insert" or "Shift + Insert", but this software erroneous detected the "insert" and switched between "overtype mode" and "insert mode".

**Comment by ShankarBUS** [comment]
It won't switch between **"OverType"** or **"Insert"** mode.

It's just a overlay to indicate that the insert Key has been pressed. It does nothing else.

Coming to your problem, the flyout should be shown only when Insert Key is pressed and not when a hotkey combo is pressed.

I'll look into this.

**Comment by Samuel12321** [comment]
Can now be partially mitigated by the disabling of the insert key flyout or any other necessary lock key flyouts

**Comment by ShankarBUS** [comment]
@lsylusiyao @Cospui,

This bug has been fixed in 89723acb2846ed74c7d7c3036a5e82ee5ad86079.
Sorry for taking this long to fix this. I forgot that this bug exists. Thanks to @lsylusiyao for reminding me!
Thanks to @Cospui for being patient. Please wait till the next release.
