### ISSUE TITLE
Music information can not be displayed

### ISSUE THREAD

**Issue by holoscy** [ShankarBUS/ModernFlyouts#92]
Hey, buddy, this software can not show the current music information when I use FOOBAR'S WASAPI exclusive mode to output music, I wonder if you could  solve this problem :)

**Comment by ShankarBUS** [comment]
Are you the developer of the media player?

If so, do you use the `SystemMediaTransportControls` WinRT API aka **"SMTC"**?

 Windows won't recognise every audio output as media (most media player applications on Windows such as VLC don't use the **"SMTC"** APIs causing this trouble).

You have to use the **"SMTC"** API to actually register them as media playback that could be controlled by  the OS.

The WASAPI API only outputs audio through a audio device. We can't do anything regarding this.

But if yout app could use some WinRT APIs, you can solve this.

Go to the Dopamine-Windows repo to observe how they do this.

If you are confused I can help you.

Is that a OpenSource app? What framework/language is that built on?

**Comment by holoscy** [comment]
I am just a user of foobar2000.  This is its website：https://www.foobar2000.org/.

What puzzles me is that without using ModernFlyouts, the system can still display music information correctly even in Wasapi exclusive mode.

The third-party customized version I am using: https://drive.google.com/file/d/1BmjYnVST494dgKrEFQN6d2JeYHBzZyF0/view?usp=sharing

**Comment by ShankarBUS** [comment]
Oh! So the Windows default media flyout shows the playback info but ModernFlyouts doesn't show it, Am I correct?

I'll look into it

**Comment by Cyberdroid1** [comment]
This problem does not arise with Exclusive mode of Dopamine music player. 
--->  https://github.com/digimezzo/dopamine-windows

Might be something to do with the app itself.

**Comment by Concorde1234** [comment]
I'm having a very similar problem with Spotify which I download from the Microsoft store. The issue seems to come up a random but only goes away when I completely restart the app (Modern Flyover) but it comes back again still.

**Comment by Concorde1234** [comment]
![image](https://user-images.githubusercontent.com/72770340/96213502-01eaa800-0f2e-11eb-93aa-165eec585fa7.png)
 Here's a picture of what's happening

**Comment by ShankarBUS** [comment]
Yes pal, this is a known issue.

There's #93 which tracks this bug.

Please comment on that thread.

**Comment by holoscy** [comment]
The problem has been solved

**Comment by ShankarBUS** [comment]
@holoscy, thanks for the reminder!

Could you post a screenshot of the app? Please?

**Comment by ShankarBUS** [comment]
@Concorde1234, the bug you reported has been fixed.

Please try out, v0.7.5 once it is out.

**Comment by holoscy** [comment]
> @holoscy, thanks for the reminder!
> 
> Could you post a screenshot of the app? Please?
![11](https://user-images.githubusercontent.com/60059377/97096490-c96e6b00-169f-11eb-8a23-5dbb8ead14a5.png)

**Comment by ShankarBUS** [comment]
Wow!

That's great! TBH, I didn't really do anything to fix this bug 😅.

It must somehow automatically be fixed 🤷‍♂️.

Good for both of us 😄
