### ISSUE TITLE
Cannot connect to Spotify

### ISSUE THREAD

**Issue by PIndividual** [ShankarBUS/ModernFlyouts#96]
The media flyout cannot connect to the uwp version of Spotify , the media info is wrong and cannot adjust the progress bar.

**Comment by Cyberdroid1** [comment]
Please see issue #29

**Comment by ShankarBUS** [comment]
Do you mean the store version of Spotify?

By progress bar do you mean the volume control or the timeline infos?

The timeline info only shows the progress, seeking the time is currently not implemented.

The parts of this issue belongs to #29 and #93

We're working on it and will fix these issues ASAP

@Samuel12321 Should this issue be made into a feature proposal - (Add support for seeking or changing the progress of the media playback)?

Thanks @Cyberdroid1 🤗

**Comment by Samuel12321** [comment]
We can make it a feature proposal, at the moment it would be super low priority

**Comment by ShankarBUS** [comment]
Woah!

Made some slight changes and got some great improvements!

Spotify shows the icon and name now, clicking on them opens Spotify!

Spotify now completely compatible with ModernFlyouts (shuffle, repeat, stop & timeline infos.. all of them are working!)

![image](https://user-images.githubusercontent.com/63704247/95669683-edf71d00-0ba0-11eb-8b92-0e1faff041fd.png)
![image](https://user-images.githubusercontent.com/63704247/95669748-74136380-0ba1-11eb-9f0b-484c628dadf8.png)

They should have updated the app. Anyway, we still have #29. #93 is being worked on.

**Comment by Samuel12321** [comment]
brilliant

**Comment by ShankarBUS** [comment]
Well I didn't do anything 🤷‍♂️. They must have added the SMTC support themselves.

This is how it previously was

![image](https://user-images.githubusercontent.com/63704247/95669851-a1144600-0ba2-11eb-84e9-9bd02ef49d14.png)

Credits - @Dubzer in #6

**Comment by ShankarBUS** [comment]
I had a shitty method to find the process name from the app id. That's what caused spotify's icon and name to be invisible.
`var processName = AppId.Remove(AppId.Length - 5, 4);`

This method returns `Spotife` when the app id is `Spotify.exe` (It removed **"y.ex"** instead of **".exe"**. Thus, ModernFlyouts couldn't fetch the name and icon of the app 🤦‍♂️).

But it worked for MS Edge & Chrome without any problems because it will return `msedge` because `msedge.exe` has **"e"** at the end and before the **'.'**

Changing it to **"4"** fixed the issue.
```diff
- var processName = AppId.Remove(AppId.Length - 5, 4);
+ var processName = AppId.Remove(AppId.Length - 4, 4);
```

Sorry for this silly mistake 😅

**Comment by Samuel12321** [comment]
Seems to be done

**Comment by Dubzer** [comment]
> Changing it to **"4"** fixed the issue.
> 
> ```diff
> - var processName = AppId.Remove(AppId.Length - 5, 4);
> + var processName = AppId.Remove(AppId.Length - 4, 4);
> ```

Isn't it would be easier to just use?.. 

`var processName = AppId[..^4]`

**Comment by ShankarBUS** [comment]
`var processName = AppId[..^4];`

What in the tarnation is this syntax?

Is this even C#?

JK, take a look at this

https://github.com/ShankarBUS/ModernFlyouts/issues/93#issuecomment-707484567

Is the new approach correct atleast?

**Comment by Dubzer** [comment]
This is the range feature which was introduced in C# 8.0
![image](https://user-images.githubusercontent.com/18244287/97083959-4b1cb500-161c-11eb-83cf-c048ca00a00b.png)

**Comment by ShankarBUS** [comment]
@Dubzer, woah!

That's cool. Forgot that this thing even existed 🤦‍♂️. My mind is stuck with C# 6 🤦‍♂️. Read that thing in the C# 8 blog post. But not sure where to implement this 😅.

I will update this immediately. It looks cool.

**Comment by Vital7** [comment]
> This is the range feature which was introduced in C# 8.0
> 
> ![image](https://user-images.githubusercontent.com/18244287/97083959-4b1cb500-161c-11eb-83cf-c048ca00a00b.png)

To be honest, this is not the correct approach, since we rely on the length of the extensions, when we shouldn't care about it at all. I think it's possible to use `Path.GetFileNameWithoutExtension` in this case.

**Comment by ShankarBUS** [comment]
@Vital7,

I know another method that'll split the string with **'.'** as the delimiter, omit the final slice and return the process' name just the like method you suggested.

What you suggested is absolutely great!

But that would be unnecessary.

The length of the extension will never change. It will always be **".exe"** (4 characters). So no problems with his approach✌️.

**Comment by Vital7** [comment]
@ShankarBUS, thanks, and I understand that it may be unnecessary in this case - Windows has basically one executable extension, almost all programs use it (there are some very rare exceptions when executable might have another extension) and I don't think this program would be ported to Linux/other OS, so it should be good 👍

**Comment by THEREALDANTHEMAN11** [comment]
THE FLY OUT DOESNT SHOW UP ON MY SCREEN THIS APP IS SUCH BULLSHIT
